### ISSUE TITLE
Why not send new stratum job when namecoin block height has changed?

### ISSUE THREAD

**Issue by u2mithrandir** [btccom/btcpool#101]
I found that when namecoin block height has changed jobmaker doesn't build a new stratum job, and the stratum server will send the new job to the miners only when the hash of  bitcoin block has changed.
This will cause that the miners are always calculating the hash of the old namecoin block, and blkmaker will get rpc fail (error code: 500) when calling rpc getauxblock(blockhash, auxpow), because the current height of namecoin has already changed.
I want to know why not send the new job with isClean=true to the miners to calculate with the new namecoin block height?

**Comment by YihaoPeng** [comment]
I have tried to fix it in d6ce00a and it needs test.
```
# policy used to determine the pace of merge mining jobs to be sent.
  # 0: merge mining `getwork` does not trigger job updates (RSK and Namecoin).
  # 1: update job when the `notify` flag in RSK `getwork` is true or the block height in Namecoin `getwork` higher than before.
  # 2: update job when the current block hash of a merge mining `getwork` is different from before (RSK and Namecoin).
  merged_mining_notify = 1; # (1 is recommended and default)
```
