### ISSUE TITLE
*** Check failure stack trace: ***

### ISSUE THREAD

**Issue by banjochose** [btccom/btcpool#11]
For now while just testing I am running only one zookeper with --replication-factor 1

since launch all instanced died

supervisor> status
blkmaker                         FATAL      Exited too quickly (process log may have details)                                                                                                                                                    
gbtmaker                         FATAL      Exited too quickly (process log may have details)                                                                                                                                                    
jobmaker                         FATAL      Exited too quickly (process log may have details)                                                                                                                                                    
sharelogger                      RUNNING    pid 23082, uptime 0:06:06                                                                                                                                                                                      
slparser                         FATAL      Exited too quickly (process log may have details)                                                                                                                                                              
sserver                          FATAL      Exited too quickly (process log may have details)                                                                                                                                                              
statshttpd                       FATAL      Exited too quickly (process log may have details)

When I run it manually

------------------------------------------------------------------

root@localhost:/work/btcpool/build# /work/btcpool/build/run_sserver/sserver -c /work/btcpool/build/run_sserver/sserver.cfg -l /work/btcpool/build/run_sserver/log_sserver
F1214 22:36:24.403488 23670 Kafka.cc:192] Failed to acquire metadata: Local: Timed out
*** Check failure stack trace: ***
    @     0x7f8e858b8bcd  google::LogMessage::Fail()
    @     0x7f8e858bab48  google::LogMessage::SendToLog()
    @     0x7f8e858b8763  google::LogMessage::Flush()
    @     0x7f8e858bb47e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4477c5  KafkaConsumer::checkAlive()
    @           0x437ad8  JobRepository::setupThreadConsume()
    @           0x438f4d  Server::setup()
    @           0x439916  StratumServer::init()
    @           0x431d40  main
    @     0x7f8e839fdf45  __libc_start_main
    @           0x433aa3  (unknown)
Aborted

**Comment by banjochose** [comment]
Some help with this ?

**Comment by hyperwang** [comment]
Could you post the config files or other components' log output?
