### ISSUE TITLE
SegWit signalling

### ISSUE THREAD

**Issue by stefment** [btccom/btcpool#13]
Hi, im trying to get an understanding of why miners are not signalling segwit yet. Can you share any details as to why btc.com pool is not signalling yet?

Thank you in advance, and my apologies if this is the improper place to ask. Have a nice day.

**Comment by bitkevin** [comment]
hi, signalling segwit or not is not a tech issue. sorry I can't answer your question.

**Comment by stefment** [comment]
Hi bitkevin :) Thanks for your reply. Do you know who i can ask about this?

**Comment by bitkevin** [comment]
oh, you can find my boss Jihan on Twitter.

**Comment by stefment** [comment]
Thanks :) I think i know who it is. Have a nice day.
