### ISSUE TITLE
Hashrate?

### ISSUE THREAD

**Issue by webchi** [btccom/btcpool#130]
Hi, guys. 
How is possible to count hashrate of miners? I see in database only accepted/rejected shares. But as I know also share difficulty needed to count hashrate, insn't it?

Thanks.

**Comment by SwimmingTiger** [comment]
Yes, you can compute it from hashrate and time:
```
hashrate (hash/s) = accepted_share * 4294967296 (hash) / time_past (s)
```
`4294967296` is `2^32`.

Example:
accept_1h = 1048576
hashrate = 1048576 * 4294967296 / (60 * 60) = 1250999896491 (hash/s) = 1.25 TH/s

**Comment by webchi** [comment]
Thanks! It works!
