### ISSUE TITLE
请问博主found_blocks表中is_orphaned是否与出块和确认块有关？

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#136]
您好，我在代码中没发现有对found_blocks表中is_orphaned字段的改动，请问这个字段是否是对于出块的确认再改动，我们通过什么机制去确认我们出的块被接受确认出块成功了的，谢谢博主。

**Comment by YihaoPeng** [comment]
该字段需要外部程序更新。目前我们编写了一个脚本，在爆块60秒后去查询 btc.com 区块浏览器的数据来判断是否为孤块，然后更新该字段。
参考实现：
https://gist.github.com/YihaoPeng/b828532e89db10bc5ecef2edc3c934c8

**Comment by sslazio2009** [comment]
> 另外有脚本监控更新，不在btcpool代码中

感谢两位总监指点
