### ISSUE TITLE
 list_id_api lib missing?

### ISSUE THREAD

**Issue by frndxyz** [btccom/btcpool#15]
project doesn't have api lib for below?

$ curl http://xxx.xxx.xxx/GetUserList?last_id=0

**Comment by frndxyz** [comment]
got answer , its statshttpd

**Comment by bitkevin** [comment]
No, this API didn't include in this project. So you need to implement by yourself.

request URL: 

```
https://example.com/get_user_id_list?last_id=0
```

return json string:

```
{"err_no":0,"err_msg":null,"data":{"jack":1,"terry":2}}
```

**Comment by frndxyz** [comment]
which database it related too?

**Comment by bitkevin** [comment]
oh, you may create you own database, it's not part of pool, what stratum server need is the HTTP API which returns json string.

**Comment by YihaoPeng** [comment]
https://github.com/btccom/btcpool/issues/16
