### ISSUE TITLE
请问这个benchmark大家有详细测试吗？

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#154]
我在内网开2个sserver，4个测试客户端，每个模拟25000台矿机，sserver位于一台物理机上，4个客户端分别位于2台物理机上，日志显示25000会1000左右连不上，然后把sserver放云服务器上，客户机在本地，做相同测试，模拟矿机会大量连接不上有50%多吧，sysctl 里面也都改了，是否是测试方式不对呢，大家有这样测试过吗？

**Comment by YihaoPeng** [comment]
1. 检查`sserver`的stderr输出（如果用supervisor，通常被重定向到了一个文件里），看看是否有`too many open file`。
2. 检查`simulator`（测试客户端）的stderr输出，看看是否有`too many open file`。
3. 如果两者都没有，还需要考虑TCP连接建立时的可用临时端口不足等问题。比如，通过NAT方式联网会占用网关（家用路由器）公网IP上的TCP端口，如果端口耗尽，则不能建立新的连接，所以同一个内网里的机器共享最大连接数。并且，某些家用路由器本身的实现具有更低的最大TCP连接数。
4. 连接建立时的性能问题也是需要考虑的。与真实的矿机上线不同，`simulator`会在一瞬间建立25000个连接。而这么快速的连接建立，很可能不只是对`sserver`的一种冲击，更是对网络基础设施（比如家用路由器，或者Linux的TCP协议栈）的一种冲击。连接很可能在还没有到达`sserver`的时候就已经失败了。
5. 当然，`simulator`本身也有缺点，它与真实矿机不同，在连接失败时不会重试，在断线之后不会重连。如果由于连接建立时的性能问题导致失败，重试很可能可以解决问题。

所以我的建议是：
1. 减少`simulator`的并发连接数，增加进程数。
2. 在连接失败后重试。
3. 如果测试客户端通过NAT，则需要考虑网关的性能，可以考虑分散测试客户端到不同的内网。

**Comment by sslazio2009** [comment]
谢谢博主的详尽解答和建议，应该就是博主说的原因3和4，难怪一直出现的现象是
1.日志里面的错误数据加上已经建立的连接和要小于模拟的矿机总数
2.旧的模拟客户端连接数稳定了，新建一个旧的连接就都掉线崩了
simulator我加了usleep(1000)都没能解决上述的问题，所以担心是机器的吞吐能力太低。
simulator模拟的并发一瞬间建立主要是想模拟这么一个场景，如果sserver1崩了，大量掉线的矿机去连接运行中的sserver2，所以部分测试没有去sleep。

**Comment by YihaoPeng** [comment]
issue因最近没有新反馈而关闭。如果有相关反馈，可以重新打开。
