### ISSUE TITLE
能用山寨币对btcpool在主网测试吗

### ISSUE THREAD

**Issue by Haoran** [btccom/btcpool#162]
您和，基于btcpool开源版本搭建了一个系统，但是无法有这么多算力在主网做测试，有建议什么方法做整套方案测试的吗？目前我想的是找一个山寨币来做测试，风险低一些。不清楚这个方案可行吗？

假如我需要对山寨币的主网做测试，需要对代码做哪些方面的改动吗？

谢谢

**Comment by YihaoPeng** [comment]
你准备使用哪种山寨币？

**Comment by bitmainhjyu** [comment]
如果只是需要测试系统，可以使用 bitcoind 的 regtest 模式（启动 bitcoind 时加上 -regtest 参数或者在配置文件里设置 regtest=1）组建一个私有的网络，这样就不会有算力的问题。

**Comment by Haoran** [comment]
> 你准备使用哪种山寨币？

LitecoinCash(LCC)和Universal（UNIT）

我是参照https://www.smzdw.org/asic  找到一些全网低算力，而且爆块时间短的。

**Comment by Haoran** [comment]
> 如果只是需要测试系统，可以使用 bitcoind 的 regtest 模式（启动 bitcoind 时加上 -regtest 参数或者在配置文件里设置 regtest=1）组建一个私有的网络，这样就不会有算力的问题。

感觉这个和测试网做测试是一样呀？我再了解一下。

**Comment by YihaoPeng** [comment]
regtest是难度比testnet更低（或者说完全没有挖矿难度，用`bitcoin-cli generate 100`都能马上生成100个区块）的比特币测试网络。

**Comment by Haoran** [comment]
> 目前，要支持其他币种的`getblocktemplate`需要做不少工作，因为对比特币的支持是通过直接链接到它的源代码来实现的。

谢谢回复。是主要对JobMaker, GbtMaker，BlockMaker中的用到getblocktemplate协议的地方做扩展，对吧。

**Comment by Haoran** [comment]
@bitmainhjyu 谢谢即时回复！我们这边主要是校验矿池能上线前的运作情况做评估。目前在testnet运作爆块分配收益都是没问题的。以爆块作为指标的话，小算力在主网就比较难实测矿池，所以才想到考虑用山寨币来测试。

**Comment by shupinghan** [comment]
> 是一样的。regtest是难度比testnet更低（或者说完全没有挖矿难度，用`bitcoin-cli generate 100`都能马上生成100个区块）的比特币测试网络。

请问bitcoind设置regtest的时候还需要在jobmaker, sserver这边设置testnet=true吗？我理解用什么网络应该是bitcoind这边决定的，但btcpool这边确实对testnet做了特殊的参数，这个是做什么的？
还要regnet能指定难度吗？

**Comment by YihaoPeng** [comment]
需要设置的原因是，我们在矿池代码内部引用了来自`bitcoin-core`的函数，而调用这些函数需要设置链的类型。某些函数（比如jobmaker中的爆块地址检查等）在mainnet和testnet下结果不同。

**Comment by xhliu** [comment]
To anyone who's interested in the above question, the answer is YES, more than 1 bitcoind have to be launched.
