### ISSUE TITLE
请教如何使用btcpool搭建decred矿池啊，readme中没有使用说明

### ISSUE THREAD

**Issue by zhangliang7190** [btccom/btcpool#169]

**Comment by zhangliang7190** [comment]
矿池编译是按照btcpool编译吗？

**Comment by zhangliang7190** [comment]
> 你可能需要两个sserver来适应不同的矿机，一个
> 
> ```
> protocol = "normal";
> ```
> 另一个
> 
> ```
> protocol = "gominer";
> ```
> 其他组件的配置参考默认配置文件就可以。

谢谢🙏。
我在编译过程中使用cmake -DJOBS=4 -DCHAIN_TYPE=BTC -DCHAIN_SRC_ROOT=/work/bitcoin-0.16.0 ..，出现了googletest cmake不过 的情况：
/root/btcpool/cmake/Modules/GoogleTest.cmake:7:
Parse error.  Expected "(", got newline with text "
".
CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    /root/btcpool/cmake/Modules/GoogleTest.cmake

请问是某些依赖组件没有配置吗？还是有其他的原因的错误。我尝试修改上面的两个文件，都没有效果。

**Comment by YihaoPeng** [comment]
issue因最近没有新反馈而关闭。如果有相关反馈，可以重新打开。

**Comment by Seymour-w** [comment]
I0328 05:55:30.512894 93086 StratumSession.cc:174] recv(69): {"id": 1, "method": "mining.subscribe", "params": ["ccminer/2.2.5"]}
I0328 05:55:30.513020 93086 StratumSession.cc:372] send(130) to  : {"id":1,"result":[[["mining.set_difficulty","0100000b"],["mining.notify","0100000b"]],"00000000000000000b000001",8],"error":null}
E0328 05:55:30.513720 93086 StratumServer.cc:294] no new jobId, ignore to send mining notify
I0328 05:55:30.518700 93086 StratumSession.cc:174] recv(103): {"id": 11, "method": "mining.authorize", "params": ["Tsjuvok7ZRPF8EFgMNt7HAsVVummbgre3Hq.test66", ""]}
W0328 05:55:30.519096 93086 StratumSession.cc:209] authorize failed, workerName:, clientAgent: ccminer/2.2.5, clientIp: 192.168.0.37
I0328 05:55:30.519134 93086 StratumSession.cc:372] send(61) to  : {"id":11,"result":null,"error":[29,"Invalid username",null]}
楼主，麻烦重开下这个问题。我搭建了DCR， 不能用钱包地址挖矿，改成username是可以的。安装bitcoin编译的，是不是这个原因？

**Comment by bmhjyu** [comment]
> I0328 05:55:30.512894 93086 StratumSession.cc:174] recv(69): {"id": 1, "method": "mining.subscribe", "params": ["ccminer/2.2.5"]}
> I0328 05:55:30.513020 93086 StratumSession.cc:372] send(130) to : {"id":1,"result":[[["mining.set_difficulty","0100000b"],["mining.notify","0100000b"]],"00000000000000000b000001",8],"error":null}
> E0328 05:55:30.513720 93086 StratumServer.cc:294] no new jobId, ignore to send mining notify
> I0328 05:55:30.518700 93086 StratumSession.cc:174] recv(103): {"id": 11, "method": "mining.authorize", "params": ["Tsjuvok7ZRPF8EFgMNt7HAsVVummbgre3Hq.test66", ""]}
> W0328 05:55:30.519096 93086 StratumSession.cc:209] authorize failed, workerName:, clientAgent: ccminer/2.2.5, clientIp: 192.168.0.37
> I0328 05:55:30.519134 93086 StratumSession.cc:372] send(61) to : {"id":11,"result":null,"error":[29,"Invalid username",null]}
> 楼主，麻烦重开下这个问题。我搭建了DCR， 不能用钱包地址挖矿，改成username是可以的。安装bitcoin编译的，是不是这个原因？

目前 BTCPool 矿池后端是暂时不支持地址挖矿功能的，我们有计划要支持，但是由于开发人手有限暂时还没有落实。

**Comment by Seymour-w** [comment]
好的，添加这个支持这个工作量大吗？有具体思路没？
