### ISSUE TITLE
怎么从bitpool中获取矿机的算力等信息

### ISSUE THREAD

**Issue by waliguder** [btccom/btcpool#171]
具体在哪个地方实现btcpool 做一些监控统计的工具，供一般用户使用，类似于btccom做的矿池浏览器，我也想自己弄一个矿池，显示连接的矿机的数据，
![image](https://user-images.githubusercontent.com/27879437/48458640-2d286200-e802-11e8-90cd-652aa010827c.png)

**Comment by YihaoPeng** [comment]
参考这篇wiki从statshttpd和slparser写入的数据表中得到算力信息：
https://github.com/btccom/btcpool/wiki/How-to-compute-a-worker's-hashrate-%7C-%E5%A6%82%E4%BD%95%E8%AE%A1%E7%AE%97%E7%9F%BF%E5%B7%A5%E7%9A%84%E5%93%88%E5%B8%8C%E9%80%9F%E7%8E%87

**Comment by waliguder** [comment]
感谢解答。

**Comment by Roddy1219** [comment]
根据数据库中矿机递交的数据来计算算力，上面是计算方法

**Comment by waliguder** [comment]
@Roddy1219 @YihaoPeng 今天我在统计的时候，有个疑问，通过上面方法算出来矿机的算力跟挖矿软件提供的不一致，是因为统计的时间还是很短吗？因为我才启动挖矿。一般那种矿池统计的也是随着时间的递增而趋于真实值吧？

**Comment by waliguder** [comment]
ok，谢谢

**Comment by YihaoPeng** [comment]
issue因最近没有新反馈而关闭。如果有相关反馈，可以重新打开。
