### ISSUE TITLE
对‘fLS::FLAGS_log_dir[abi:cxx11]’未定义的引用

### ISSUE THREAD

**Issue by zhangliang7190** [btccom/btcpool#172]
在编译过程中出现：
Scanning dependencies of target sharelogger
[ 75%] Linking CXX executable gbtmaker
[ 76%] Linking CXX executable nmcauxmaker
[ 76%] Building CXX object CMakeFiles/sharelogger.dir/src/sharelogger/ShareLoggerMain.cc.o
[ 77%] Linking CXX executable gwmaker
CMakeFiles/gbtmaker.dir/src/gbtmaker/GbtMakerMain.cc.o：在函数‘main’中：
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const’未定义的引用
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const’未定义的引用
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const’未定义的引用
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const’未定义的引用
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const’未定义的引用
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:87：对‘fLS::FLAGS_log_dir[abi:cxx11]’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [gbtmaker] 错误 1
make[1]: *** [CMakeFiles/gbtmaker.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....

该怎么解决？

**Comment by SwimmingTiger** [comment]
当前编译器或者编译参数与你的`libgoogle-glog`库不兼容。尝试卸载该库并自行构建：
```
apt remove libgoogle-glog-dev
mkdir -p /root/source && cd /root/source
wget https://github.com/google/glog/archive/v0.3.4.tar.gz
tar zxvf v0.3.4.tar.gz
cd glog-0.3.4
./configure && make && make install
```

**Comment by SwimmingTiger** [comment]
总的来说，这通常是C++11编译器与非C++11函数库的abi兼容性问题。
在最坏的情况下，你可能需要升级系统到下一个发行版，或者自行构建所有不兼容的函数库。

测试表明，Ubuntu16.04及以上系统软件源中的函数库在同样从软件源安装的g++中可以正常链接。

**Comment by SwimmingTiger** [comment]
如果构建困难，也可以考虑在docker中构建
这里是一个构建master分支的例子，可以根据需要进行修改：
https://github.com/btccom/btcpool/tree/master/docker/btcpool/sserver-btc-withswitcher

**Comment by zhangliang7190** [comment]
我这边用的centos7的系统。glog安装成功后，abi的错屋不再报出，不过
`CMakeFiles/gbtmaker.dir/src/gbtmaker/GbtMakerMain.cc.o：在函数‘main’中：
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits, std::allocator >() const’未定义的引用
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits, std::allocator >() const’未定义的引用
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits, std::allocator >() const’未定义的引用
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits, std::allocator >() const’未定义的引用
/work/btcpool/src/gbtmaker/GbtMakerMain.cc:127：对‘libconfig::Setting::operator std::__cxx11::basic_string<char, std::char_traits, std::allocator >() const’未定义的引用`
的错误还存在。我怀疑是某个库或者是某个组件的问题，找不到····

**Comment by YihaoPeng** [comment]
这个库是libconfig++
https://hyperrealm.github.io/libconfig/

**Comment by YihaoPeng** [comment]
因为很久没有新回复，该issue暂时关闭。如果依然没有解决，请回复该issue。
