### ISSUE TITLE
博主您好，我有如下问题想请教，谢谢您的指教

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#173]
1.我觉得现在代码由于支持的币种太多太复杂了怎么能开个分支只支持BTC？另外如果能提交代码到博主这个代码是怎么一个流程，是否需要加入什么组织？
2.关于测试的不知道是不是内存泄露或者是死循环，statshttp模块在我测试100万矿机的时候达到惊人的80g内存占用，线程撕裂者也占用居高不下。我2万块的机器居然不能支持到1000万？（我想发一套手机上运行的币种，支持十亿手机挖矿）
3.如果将代码用于运营，该怎么防护呢？还需要做什么工作呢？例如别人大量连上了不做题，怎么防护sserver模块？
4.如果我需要部署多个节点，美国欧洲中国加拿大等，该如何整合算力，就当多个小矿池然后开发一个中间件统计成一个大的行吗？我自己的小矿池之间会竞争吗？
5.能否指点一下思路我想把sserver模块拆分，连接和算法分离，算法做成库，实现一个不断开连接升级的效果
6.关于pps+和pplns这种分配算法混用的情况请指点一下思路，感觉实现起来混杂着不同的share很难分辨
7.如果运营中supervisor自己蹦了好像没法获得原来运行的服务模块了，这个时候怎么保证高可用呢？
8.关于钱包转账是怎么一个流程比较安全的那种。
9.关于bitcoin博主是否有研究？按照网上的教程改连接也不能连接几千几万的节点？
10.博主是否有运营这一套代码？过程中需要注意什么？比如说监控什么等，是否需要雇佣专业的运维去指导他？
感谢博主

**Comment by YihaoPeng** [comment]
1. 这是一个只支持BTC的版本，目前无人维护，但是应该还能用：https://github.com/btccom/btcpool/tree/legacy 你可以考虑维护自己的分支。
2. https://github.com/btccom/btcpool/issues/90 我在这里的回答涉及了statshttpd对内存的需求。由于目前把所有用户的当前时间窗口内数据都放在内存，它对内存的需求确实与矿机数成正比。
3. 可以编写一个监控程序尝试连接每个sserver、认证并获得任务。如果无法正常获得任务，说明sserver出了问题，再去检查日志或者抓包看恶意用户等。
4. 目前在 tools/bitcoin 目录有一个 kafka_repeater，可以利用它聚合算力（转发ShareLog这个topic）。
5. 使用类似stratumSwitcher的程序，https://github.com/btccom/btcpool-go-modules/tree/master/stratumSwitcher 目前该程序可以实现自身的平滑重启，以及在sserver重启时自动恢复连接。
6. 目前没有适用于PPLNS的slparser。如果编写一个这样的slparser，就可以实现该模式。查询数据库得知爆块时间，然后统计前后share。
7. 目前没有观察到supervisor崩溃的现象。不过如果要保持高可用，可以在不同的服务器开启多个相同的进程（有id参数的只需要设置不同的id就可以共存，没有id参数的则默认可以共存，比如gbtmaker）。
8. 没有相关经验，不过其他人的经验表明专门让一个人负责手工打款比较安全（交易可以自动生成，但检查、签名、广播等工作手动）。
9. bitcoin-core的P2P协议栈无法支持那么多的对等连接。你可以试试搜索“bitcoin spider”之类的专用网络爬虫（我不确定已经存在这样的程序）。
10. pool.btc.com正在使用该代码。需要专业的运维。

**Comment by sslazio2009** [comment]
>     1. 这是一个只支持BTC的版本，目前无人维护，但是应该还能用：https://github.com/btccom/btcpool/tree/legacy 你可以考虑维护自己的分支。
> 
>     2. #90 我在这里的回答涉及了statshttpd对内存的需求。由于目前把所有用户的当前时间窗口内数据都放在内存，它对内存的需求确实与矿机数成正比。
> 
>     3. 可以编写一个监控程序尝试连接每个sserver、认证并获得任务。如果无法正常获得任务，说明sserver出了问题，再去检查日志或者抓包看恶意用户等。
> 
>     4. 目前在 tools/bitcoin 目录有一个 kafka_repeater，可以利用它聚合算力（转发ShareLog这个topic）。
> 
>     5. 使用类似stratumSwitcher的程序，https://github.com/btccom/btcpool-go-modules/tree/master/stratumSwitcher 目前该程序可以实现自身的平滑重启，以及在sserver重启时自动恢复连接。
> 
>     6. 目前没有适用于PPLNS的slparser。如果编写一个这样的slparser，就可以实现该模式。查询数据库得知爆块时间，然后统计前后share。
> 
>     7. 目前没有观察到supervisor崩溃的现象。不过如果要保持高可用，可以在不同的服务器开启多个相同的进程（有id参数的只需要设置不同的id就可以共存，没有id参数的则默认可以共存，比如gbtmaker）。
> 
>     8. 没有相关经验，不过其他人的经验表明专门让一个人负责手工打款比较安全（交易可以自动生成，但检查、签名、广播等工作手动）。
> 
>     9. bitcoin-core的P2P协议栈无法支持那么多的对等连接。你可以试试搜索“bitcoin spider”之类的专用网络爬虫（我不确定是否已经存在这样的程序）。
> 
>     10. pool.btc.com 的所有币种均使用该代码。需要专业的运维。

博主您好，针对您的回答我还是有一些疑问想请教一下。
针对第二条，statshttp这个模块这些数据已经入库了，又提供http接口，外面获取这些数据提供两种方式？是两种获取的数据不一样吗？这么设计是基于什么考虑呢？如果不入库好像还快一些？针对第三条，这能算一种被动式，在别人已经造成损害的情况下，有其他的主动的方式思路吗？针对第八条，按照我的理解是不是根本就不需要开发转账的程序，就把需要转账的用户以及地址额度导出来让运维去用冷钱包一个一个的敲？

**Comment by YihaoPeng** [comment]
2. 目前已经提供参数可以关闭mysql和redis写入。并且，HTTP如果没有人调用也不会产生开销。所以你可以自行选择想要的查询方式。
3. 那你可以编写一个监控任务对同一IP下的TCP连接数进行监控，在发现异常时及时预警。用于攻击的连接通常不会提交合法share，可以结合这一点，对`mining_workers`表中该IP的`share_accept`数进行查询来区分攻击者与合法连接。
8. 我认为开发一个转账程序是可以的，不过转账程序只需要生成交易就可以了，不需要涉及签名。也就是说，转账程序完全不需要接触你的钱包私钥。和其他支付方式不同，在比特币这样的utxo模型的区块链中，你只要知道对方的公钥，就能从比特币节点查询到他的所有utxo，并且可以代替他生成交易。然后，把生成的交易发给打款的人，由对方进行核对，然后导入具有私钥的钱包进行签名，再把交易广播出去，完成打款。

可以导入外部未签名交易的钱包有`Electrum`等。

**Comment by sslazio2009** [comment]
博主您好，最近测这个好像有bug，不知道是不是有特定的模块启动顺序，jobmaker这个模块换机器或者增减kafka数量的情况下经常会收不到gbtmaker的信息

**Comment by Seymour-w** [comment]
楼主，关于你说的第4个问题，是把每一个节点看成一个小矿池吗？  一个节点包含钱包吗？
“4.如果我需要部署多个节点，美国欧洲中国加拿大等，该如何整合算力，就当多个小矿池然后开发一个中间件统计成一个大的行吗？我自己的小矿池之间会竞争吗？”

**Comment by sslazio2009** [comment]
> 楼主，关于你说的第4个问题，是把每一个节点看成一个小矿池吗？ 一个节点包含钱包吗？
> “4.如果我需要部署多个节点，美国欧洲中国加拿大等，该如何整合算力，就当多个小矿池然后开发一个中间件统计成一个大的行吗？我自己的小矿池之间会竞争吗？”

之前不清楚如果把300p的算力平均部署在3个不同的矿池里面会不会就相当于100p的算力在跑，这个问的节点是一个矿池节点就是一套这个btcpool的意思

**Comment by Seymour-w** [comment]
明白，还一个问题是如果把节点和钱包弄在同一个服务器。是不是只要同一个钱包就行了？

**Comment by sslazio2009** [comment]
> 明白，还一个问题是如果把节点和钱包弄在同一个服务器。是不是只要同一个钱包就行了？

是的，实际用最好还是多台服务器组集群，统一服务器要确保sserver的流量和bitcoin的流量不会抢带宽。

**Comment by Seymour-w** [comment]
多谢指教！
