### ISSUE TITLE
在使用statshttpd打开http服务后，未能查询workerId=0的信息

### ISSUE THREAD

**Issue by waliguder** [btccom/btcpool#176]
![image](https://user-images.githubusercontent.com/27879437/48760856-2b6b0c80-ece2-11e8-9dcf-b6b2ed48b5f1.png)
总是返回无效的参数

**Comment by bitmainhjyu** [comment]
矿机是从属于用户的，故必须指定 `user_id` 才可以使用 `worker_id` 参数。

**Comment by waliguder** [comment]
@bitmainhjyu 但是user_id也是一样的错误

**Comment by bitmainhjyu** [comment]
和程序员的普遍思维略有区别，这里 `user_id` 是从 1 开始的。

**Comment by YihaoPeng** [comment]
```
  const char *pUserId   = evhttp_find_header(&params, "user_id");
  const char *pWorkerId = evhttp_find_header(&params, "worker_id");
  const char *pIsMerge  = evhttp_find_header(&params, "is_merge");

  if (pUserId == nullptr || pWorkerId == nullptr) {
    evbuffer_add_printf(evb, "{\"err_no\":1,\"err_msg\":\"invalid args\"}");
    evhttp_send_reply(req, HTTP_OK, "OK", evb);
    goto finish;
  }
```
你需要同时提供`user_id=1&worker_id=0`这样才能查到。

**Comment by YihaoPeng** [comment]
其实我们应该做出修改，允许只提供`user_id`，这样比使用`user_id=1&worker_id=0`更具可读性。

**Comment by waliguder** [comment]
其实我都试了，都是一样的invalid args
但是在外层的数据显示是有一台在挖矿的
`{"err_no":0,"err_msg":"","data":{"uptime":"0006 d 05 h 25 m 35 s","request":167,"repbytes":24188,"pool":{"accept":[0,0,128,576],"reject":[0,0,0,0],"accept_count":375,"workers":1,"users":1}}}`

**Comment by YihaoPeng** [comment]
完整的url应该是
```
http://xxx:xxx/worker_status/?user_id=N&worker_id=0
```

**Comment by YihaoPeng** [comment]
代码中只有两个地方会输出`invalid args`，分别是
```
// query is empty, return
  if (query == nullptr)
```
和
```
if (pUserId == nullptr || pWorkerId == nullptr)
```

**Comment by YihaoPeng** [comment]
此外，因为代码只检查query字符串，所以不支持POST方式提交的参数。

**Comment by waliguder** [comment]
@YihaoPeng 谢谢，终于成功了，的确，不能用post请求，然后注意的地方是worker_status后面还要一个“/”
`http://xxx:xxx/worker_status/?user_id=1&worker_id=0`
成功的获取到正在share的数据

**Comment by SwimmingTiger** [comment]
没有 `/` 应该也是可以的
```
  evhttp_set_cb(httpd, "/",               StatsServerT<SHARE>::httpdServerStatus, this);
  evhttp_set_cb(httpd, "/worker_status",  StatsServerT<SHARE>::httpdGetWorkerStatus, this);
  evhttp_set_cb(httpd, "/worker_status/", StatsServerT<SHARE>::httpdGetWorkerStatus, this);
  evhttp_set_cb(httpd, "/flush_db_time",  StatsServerT<SHARE>::httpdGetFlushDBTime, this);
```

我只是恰好写了 `/`

**Comment by waliguder** [comment]
的确，不需要`/`也可以。
我在Statistics.cc中加入了一些LOG插入的代码，但是为什么在文件中并没有显示，是需要重启吗？还是代码没起作用？
`
// get all workes status
  for (auto itr = workerSet_.begin(); itr != workerSet_.end(); itr++) {
    workerCounter++;

    const int32_t userId   = itr->first.userId_;
    const int64_t workerId = itr->first.workerId_;
    shared_ptr<WorkerShares> workerShare = itr->second;
    const WorkerStatus status = workerShare->getWorkerStatus();

    char ipStr[INET_ADDRSTRLEN] = {0};
    inet_ntop(AF_INET, &(status.lastShareIP_), ipStr, INET_ADDRSTRLEN);
    const string nowStr = date("%F %T", time(nullptr));

    values.push_back(Strings::Format("%" PRId64",%d,%d,%" PRIu64",%" PRIu64","
                                     "%" PRIu64",%" PRIu64","  // accept_15m, reject_15m
                                     "%" PRIu64",%" PRIu64","  // accept_1h,  reject_1h
                                     "%d,\"%s\","
                                     "\"%s\",\"%s\",\"%s\"",
                                     workerId, userId,
                                     -1 * userId,  /* default group id */
                                     status.accept1m_, status.accept5m_,
                                     status.accept15m_, status.reject15m_,
                                     status.accept1h_, status.reject1h_,
                                     status.acceptCount_, ipStr,
                                     date("%F %T", status.lastShareTime_).c_str(),
                                     nowStr.c_str(), nowStr.c_str()));

    LOG(INFO) << "workerInfo----workerId:" << workerId << ",userId:" << userId 
            << ",accept1m:" <<　status.accept1m_　<< ",accept5m:" << status.accept5m_
            << ",accept15m:" << status.accept15m_ << ",reject15m" << status.reject15m_
            << ",accept1h:" << status.accept1h_ << ",reject1h:" << status.reject1h_
            << ",acceptCount:" << status.acceptCount_ << ",IP:" << ipStr
            << ",lastShareTime:" << date("%F %T", status.lastShareTime_).c_str();
  }
`
这样做正确吗？因为我想了解挖矿时具体产生的数据

**Comment by YihaoPeng** [comment]
你加入的位置看上去只会在访问`http://xxx:xxx/worker_status/?user_id=N&worker_id=非0值`时才会运行到。

**Comment by YihaoPeng** [comment]
`worker_id=0`的数据来自`userSet_`，表示该`puid`的所有矿机数据之和。`http://xxx:xxx/worker_status/?user_id=N&worker_id=0`的处理代码在`StatsServerT<SHARE>::getWorkerStatusBatch()`函数中

**Comment by waliguder** [comment]
![image](https://user-images.githubusercontent.com/27879437/48823326-60876580-ed9b-11e8-93a0-de7258895c6b.png)
这个日志到现在都没有更新过，是不是因为我改了源码？我只是加了一下插入日志的操作

**Comment by waliguder** [comment]
![image](https://user-images.githubusercontent.com/27879437/48833951-7a36a600-edb7-11e8-81c8-0cfe36405a0f.png)
rd_kafka_consume一直显示超时，不知道怎么回事，是因为rkmessage为空？kafka的KAFKA_TOPIC_COMMON_EVENTS也为空。想请教下怎么重启kafka

**Comment by waliguder** [comment]
@YihaoPeng accept_count这个字段是用来干吗的？是所有矿机开始挖矿的综合吗？为什么它会比1小时的接受的share要少那么多？
![image](https://user-images.githubusercontent.com/27879437/48890576-2047e600-ee74-11e8-81ec-c681351cd7d4.png)
希望能得到你的答复，谢谢

**Comment by YihaoPeng** [comment]
accept_count记录的是提交的个数，每发现一个accept_share就加一。
一分钟为0是很有可能的，如果难度过高，矿机经常会几分钟都挖不到一个share。此外，即使难度合适，矿机一分钟没有挖到share也是完全有可能的，这取决于运气。

**Comment by waliguder** [comment]
是提交给数据库吗？如果每发现一个accept_share就加一，那它的值应该比accept_1h要多一点吧，但是他一直处于很低的一个状态？原因是它增长的很慢。不清楚这个值的意义。。。

**Comment by YihaoPeng** [comment]
我再来解释一下，accept_count是矿机发送给sserver的`mining.submit`请求的次数。

**Comment by YihaoPeng** [comment]
issue因最近没有新反馈而关闭。如果有相关反馈，可以重新打开。
