### ISSUE TITLE
decred矿池sservr问题请教

### ISSUE THREAD

**Issue by zhangliang7190** [btccom/btcpool#180]
你好：
在矿池连接decred矿机的过程中，
recv(118): {"params": ["test1.001", "0077", "ca73000000000000", "5bf76081", "65aa4e3b"], "id": 19992, "method": "mining.submit"}
此时的：
 blkHash: f5a2dfcd319c987a1b135f0c246126312a1791d3bd35d971ade2059594ae6457,
bnBlockHashf5a2dfcd319c987a1b135f0c246126312a1791d3bd35d971ade2059594ae6457, 
jobTarget: 0000000003fffc00000000000000000000000000000000000000000000000000, networkTarget: 0000000000000000612ed4000000000000000000000000000000000000000000

矿池
send(62) to test1.001 : {"id":19992,"result":null,"error":[23,"Low difficulty",null]}
同时
rejected share: Low difficulty, worker: test1.001, share(jobId: 6626871508768999169, ip: , userId: 1, workerId: -8701873834372045927, time: 1542938778/2018-11-23 02:06:18, height: 294488, blkBits: 18612ed4/11313663180.964638, shareDiff: 64, status: 23/Low difficulty)

请问，这是hash算法的原因吗？该如何解决？

**Comment by bitmainhjyu** [comment]
你可能需要调节一下 sserver 的 protocol 选项，有些矿机需要设置成 gominer 才行。

**Comment by YihaoPeng** [comment]
如果没有后续反馈，这个issue暂时关闭。
