### ISSUE TITLE
请问服务配置中的kafka的顺序是否有什么规则？

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#182]
现在开了三台机器组集群，发现一个很奇怪的问题，基本上发现kafka的log文件基本上集中在第一台机器，体积远远超出其他两台机器的log。然后一个集群里面开多少个gbt，blk，job模块合适呢？因为没挂矿机就开了两三天kafka的log文件就200多g了。

**Comment by YihaoPeng** [comment]
kafka.brokers配置的顺序与topic存储在哪个服务器上完全无关，你需要使用kafka管理命令来调整服务器上的topic分布（称为replication）。
参考 https://blog.csdn.net/lingbo229/article/details/83309208

**Comment by YihaoPeng** [comment]
此外，通过以下命令可以设置topic中消息的保存时间和保存的总大小上限：
```
./bin/kafka-configs.sh --zookeeper 10.0.0.1:2181 --alter --entity-type topics -entity-name topic名称 --add-config retention.ms=消息保存的毫秒数
./bin/kafka-configs.sh --zookeeper 10.0.0.1:2181 --alter --entity-type topics -entity-name topic名称 --add-config retention.bytes=topic的最大字节数
```

有些版本的kafka命令行工具是使用`--config`参数，而不是`--add-config`

**Comment by YihaoPeng** [comment]
如果没有后续问题，这个issue暂时关闭
