### ISSUE TITLE
来自社区用户的反馈：kafka消息不明原因丢失导致没有爆块

### ISSUE THREAD

**Issue by SwimmingTiger** [btccom/btcpool#202]
今天，社区用户通过QQ联系我，称他遇到了一个sserver已爆块，但solved share没有写入kafka的issue。该issue仅发生一次，之前和之后均能正常爆块。

他的kafka版本为kafka-2.1.0 (Scala 2.12)，由三个broker组成集群。但部署时发生了一个小错误，三个broker实际上在同一个服务器，并且意外的共享了日志文件夹（并不是数据日志文件夹，只是普通日志）。这导致我们没有办法查看到每一个broker的日志。此外，他给每个broker的java虚拟机分配了最多1GB内存（`-Xmx1G`）。

然后结果就是某个solved share看起来已经被sserver投递，但是没有被kafka保存下来。sserver没有记录任何生产错误，kafka似乎也没有相关错误（也有可能是日志被无关broker覆盖）。

该问题可能的原因：
1. librdkafka的旧版本与kafka 2.*有兼容性问题。
2. 部署方面的问题。
3. 内存不足导致broker抛出异常。

针对该问题的改进建议：
1. 应该在kafka生产者中添加消息投递失败的检测和重试机制。librdkafka的produce函数看起来是支持结果回调的。
2. 更新程序依赖的librdkafka版本。

**Comment by YihaoPeng** [comment]
没有新进展，该issue暂时关闭
