### ISSUE TITLE
请教博主关于poolwatcher的问题

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#211]
最近是用poolwatcher监测中国大陆地区的主要矿池，发现爆块的矿池不一定会最先发新高度的题目通知poolwatcher，甚至通知poolwatcher的排位还不靠前？理论上不应该是爆块的矿池最先下发新题吗？第二，为什么这个通知的速度总会慢于一个没有配置进去的【POOL】选项？

**Comment by YihaoPeng** [comment]
[POOL] 表示从kafka中读取到的当前矿池的任务。所以如果是你自己的矿池爆块，[POOL] 肯定是最先触发的。
如果是其他矿池爆块，你的 [POOL] 应该晚于其他矿池。当然也有可能早于，这说明你的比特币节点网络连接很好，反应迅速。
爆块矿池的反应速度没有其他非爆块矿池快的话，可能有以下几个原因：
* 你的poolwatcher和爆块矿池之间的网络延迟较大。
* 爆块矿池的内部系统状况不佳，反应速度缓慢。
* 爆块矿池分为多个地区的多个服务器，爆块的服务器和你监听的服务器不同。
