### ISSUE TITLE
部署LTC池时Sserver.cfg中配置

### ISSUE THREAD

**Issue by langubtc** [btccom/btcpool#213]
在Litecoin环境下，sserver.cfg中的avg_block_time or diff_adjust_period 中的900是否需要调整？

**Comment by langubtc** [comment]
是否有参考配置?

**Comment by YihaoPeng** [comment]
`diff_adjust_period`控制的是难度调整算法的敏感程度，如果想让矿机快速达到理想难度，那么可以减少该值。比如，我们在以太坊中将其设为300秒。
不过，设置的太短有一个缺点，就是由于矿机的幸运值，每分钟提交share数量一直在变化，可能造成难度反复上下波动。
不过，只要这个值不是太小（比如小于60），就不会对难度调整算法造成不利影响，也就不会影响收益计算。

`avg_block_time`是之前对该参数的误解。比如，在像以太坊这样的网络中，平均15秒爆一个块，但该参数不应该被设置为15。所以该参数已经改名为`diff_adjust_period`。

**Comment by YihaoPeng** [comment]
我认为，由于莱特币矿机和比特币矿机有很多相似的特性，所以把难度调整周期设置为900应该是合适的。
然后把默认难度设置为等于或稍高于当前最流行的莱特币矿机的稳定工作难度，就可以让大部分矿机都不需要经历难度调整。

**Comment by YihaoPeng** [comment]
> 
> 
> 升级sserver后，出现大量的报错，且在启动后900内没有调整难度。默认难度为65535 `I0101 22:12:14.817775 17072 StratumMinerBitcoin.cc:266] rejected share: Low difficulty, worker:test.35x62, versionMask: 00000000, share(jobId: 6641902000932257281, ip: xxxxx, userId: 5646, workerId: -4861332104447282664, time: 1546438334/2019-01-01 14:12:14, height: 1554352, blkBits: 1a02ce1b/391962871739.876282, shareDiff: 206696, status: 23/Low difficulty)`

请检查构建时的cmake参数，应设为`-DCHAIN_TYPE=LTC`并与Litecoin代码链接。
如果依然存在该问题，请构建一个Debug模式的客户端来打印share检查过程中的细节。我已经调整代码让该日志在`LOW_DIFFICULTY`的情况下也能打印：
```
DLOG(INFO) << "blkHash: " << blkHash.ToString() << ", jobTarget: "
  << jobTarget.ToString() << ", networkTarget: " << sjob->networkTarget_.ToString();
```
