### ISSUE TITLE
sserver多工作线程

### ISSUE THREAD

**Issue by YihaoPeng** [btccom/btcpool#215]
目前，sserver的share验证工作是单线程的，但某些算法（比如ethash）的单核性能有限。
社区用户反馈称，他的以太坊sserver：
> 连1058台机器 cpu 60%~72%

所以如果能改成支持多个工作线程，也许可以把压力分散到CPU的多个核心上，从而减少CPU平均占用。

**Comment by bitmainhjyu** [comment]
可以每个线程一个 event_base。

**Comment by YihaoPeng** [comment]
已经实现
