### ISSUE TITLE
[问题尚不明确] 疑似LTC的share_avg_seconds设置过高导致拒绝率较高

### ISSUE THREAD

**Issue by YihaoPeng** [btccom/btcpool#216]
目前，我们把`share_avg_seconds`设置为`15`秒，结果某些用户的拒绝率在5%到10%之间，并且一直处于高位。

理论计算一下，莱特币2.5分钟出一个块，每个块都可能因为任务过期拒绝1到2个share。
平均每15秒提交一个share，2.5分钟提交10个share。
这样拒绝就能到10%，与我们观察到的数据相符。

也许把`share_avg_seconds`设置为`5`秒是更好的选择，我们正在进行这样的调整，看看有没有效果。

**Comment by langubtc** [comment]
我记得默认配置10秒，也是有出现少量拒绝，但没有10%这么高

**Comment by langubtc** [comment]
调整为5秒，验证是否有效呢？ @YihaoPeng

**Comment by YihaoPeng** [comment]
效果不明确，仍有用户的部分矿机拒绝率较高。受影响矿机的拒绝率明显高于同用户不受影响矿机的拒绝率，我还在找原因。

**Comment by langubtc** [comment]
@YihaoPeng 该拒绝率高是否有可能由于LTC爆块速度比较快,Job清理了导致矿机递交的share拒绝呢？

**Comment by YihaoPeng** [comment]
> 
> 
> @YihaoPeng 该拒绝率高是否有可能由于LTC爆块速度比较快,Job清理了导致矿机递交的share拒绝呢？

这是该问题的根本原因，但这个机制是保证矿池利益不受损的前提。除非LTC接受叔块，否则矿池不能接受过期的share并给它计算收益。

**Comment by YihaoPeng** [comment]
这个现象也许与`share_avg_seconds`无关，而是因为我们的部署使用StratumSwitcher所致。

**Comment by rocqina** [comment]
请问如果是switcher的原因，那么btc和ltc的拒绝率是不是应该一致
