### ISSUE TITLE
Sserver出现socket错误

### ISSUE THREAD

**Issue by langubtc** [btccom/btcpool#217]
单个sserver上到2000台时经常出现: StratumServer.cc:983] got an error on the socket: Connection reset by peer，这个是否需要对服务器进行调优，还是单个sserver本身处理有限呢？

**Comment by bitmainhjyu** [comment]
请问有没有设置 sserver 进程的文件描述符限制？可以使用 `prlimit -n --pid <sserver pid>` 来查看当前的限制。

**Comment by langubtc** [comment]
`RESOURCE DESCRIPTION               SOFT  HARD UNITS
NOFILE   max number of open files 65535 65535`

**Comment by YihaoPeng** [comment]
对了，如果你的服务器在阿里云，并且使用了阿里云的负载均衡服务（SLB），则他们的端口健康检查就会造成该日志频繁输出。因为健康检查是快速建立一个到指定端口的TCP连接，然后马上reset掉。其他云服务商的负载均衡可能也有类似检查。

**Comment by YihaoPeng** [comment]
> 
> 
> 我之前内网模拟测试过单个sserver负载10万没有压力，要把那个if判断调整一下，要不然没校验。你不能建立链接速度太快，每个连接建立都有交互数据，量还挺大的。外网之前博主也说了路由器运营商都可能坑你。

`要把那个if判断调整一下`是指哪里呢？

**Comment by sslazio2009** [comment]
> > 我之前内网模拟测试过单个sserver负载10万没有压力，要把那个if判断调整一下，要不然没校验。你不能建立链接速度太快，每个连接建立都有交互数据，量还挺大的。外网之前博主也说了路由器运营商都可能坑你。
> 
> `要把那个if判断调整一下`是指哪里呢？

我用的版本被人改了，看着这个地方逻辑短路了，没有运行后面的判断，对不住博主了

**Comment by YihaoPeng** [comment]
如果出现大量连接容易崩溃的问题，也可能和SIGPIPE有关
https://github.com/btccom/btcpool/issues/256
