### ISSUE TITLE
建议项目确定一下代码规范

### ISSUE THREAD

**Issue by AndyChenW** [btccom/btcpool#221]
可以考虑用 clang-format 选一个 style

**Comment by AndyChenW** [comment]
https://chromium.googlesource.com/chromium/src/+/master/styleguide/c++/c++.md 
clang-format 的 chromium 不错的，推荐

**Comment by bitmainhjyu** [comment]
我们曾经讨论过这个问题，看起来 chromium 的风格也和目前 btcpool 类似，会考虑在今后加入。

**Comment by bitmainhjyu** [comment]
> 我们曾经讨论过这个问题，看起来 chromium 的风格也和目前 btcpool 类似，会考虑在今后加入。

LLVM 的风格似乎更加符合现有的状况。

**Comment by AndyChenW** [comment]
这个我觉得可以在 .clang-format 里自定义的，规则其实有点像左行还是右行，没有不行，是啥其实都还好。

**Comment by AndyChenW** [comment]
> 我个人不喜欢这种对齐方式，每次重命名都要重新对齐：
> 
> ```
> void myFunction(int a,
>                 int b,
>                 int c,
>                 int d,
>                 int e);
> ```
> 我已经在新的代码中使用这种方式：
> 
> ```
> void myFunction(
>   int a,
>   int b,
>   int c,
>   int d,
>   int e
> );
> ```
这种重对齐不应当是手动做的事，在 save 的时候应当 vim emacs vscode 都能做到 auto format 的

**Comment by bitmainhjyu** [comment]
> > 我个人不喜欢这种对齐方式，每次重命名都要重新对齐：
> > ```
> > void myFunction(int a,
> >                 int b,
> >                 int c,
> >                 int d,
> >                 int e);
> > ```
> > 我已经在新的代码中使用这种方式：
> > ```
> > void myFunction(
> >   int a,
> >   int b,
> >   int c,
> >   int d,
> >   int e
> > );
> > ```
> 
> 这种重对齐不应当是手动做的事，在 save 的时候应当 vim emacs vscode 都能做到 auto format 的

这会产生不必要的 git diff 的。

**Comment by AndyChenW** [comment]
> > > 我个人不喜欢这种对齐方式，每次重命名都要重新对齐：
> > > ```
> > > void myFunction(int a,
> > >                 int b,
> > >                 int c,
> > >                 int d,
> > >                 int e);
> > > ```
> > > 我已经在新的代码中使用这种方式：
> > > ```
> > > void myFunction(
> > >   int a,
> > >   int b,
> > >   int c,
> > >   int d,
> > >   int e
> > > );
> > > ```
> > 
> > 
> > 这种重对齐不应当是手动做的事，在 save 的时候应当 vim emacs vscode 都能做到 auto format 的
> 
> 这会产生不必要的 git diff 的。

这倒是，不过我看 go 自带的 format 也会出现这种情况，出现不必要的 git diff。如果不喜欢前者就用后者也可以的。

**Comment by YihaoPeng** [comment]
谁来写一个`.clang-format`试试吧:smile:

**Comment by AndyChenW** [comment]
直接用 clang-format dump 一个 .clang-format 出来吧，然后再按你们项目成员的喜好再自定义。

不过我**强烈建议**只选 clang-format 里几个 style 里的一种，这种默认的 style 共识如果有一两个小改动对外面的 C++ 开发人员会非常不友好。我们这边选了 Chromium，这基于 Google style 做了些改进，我看了一下改进还是不错的。

**Comment by bmhjyu** [comment]
目前我们已经提供了一个尽可能符合现状的 .clang-format 并且格式化了自有代码，在 CircleCI 持续集成中也增加了对代码规范的检查。

**Comment by AndyChenW** [comment]
大赞。
