### ISSUE TITLE
decred-tls启动需要证书访问rpc问题

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#228]
请问下blkmaker，gw，gbt访问带安全证书的全节点怎么配置证书。

**Comment by bxlkm** [comment]
谢谢，如果dcrd和gw服务都分别部署同一宿主的不同docker里 是不是做证书时得写docker的IP，证书得部署到gw服务docker容器系统信任的证书存储中，假如是不同宿主的docker容器的话，是不是得部署到gw宿主的系统信任的证书存储中。

**Comment by bmhjyu** [comment]
> 对，哪些矿池节点访问dcrd全节点的都要加，我觉得忽略证书访问最好，像curl添加--insecure一样，希望下个版本能够进行修改，谢谢。

目前我们已经将这个功能合并到了 master 分支（注意我们现在 master 分支就是之前的 deveth 分支），只需要在 gwmaker.cfg 内加入如下的内容就可以关闭 SSL 验证。

```
curl = {
  ssl_verify_peer = false;
};
```
