### ISSUE TITLE
请给一套完整的LTC和狗币联合挖矿的配置，ths！

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#229]
请博主明示，不知道LTC和狗币联合挖矿在矿池怎么配置？

**Comment by bxlkm** [comment]
非常感谢，说的很详细，我有个疑问就是矿池和矿机直联就可以，还是必须使用Merged Mining Proxy模块才可以。

**Comment by YihaoPeng** [comment]
矿机直连就可以。

`Merged Mining Proxy`模块和矿机无关，它是一个对`DogeCoin HTTP RPC`（也就是配置在`nmcauxmaker`中的`rpc_addr`和`rpc_userpwd`）的代理。

这个代理的作用是可以让你同时挖掘好几种联合挖矿币种（），如果你只想联合挖`Dogecoin`，不需要使用它。

**Comment by bxlkm** [comment]
谢谢，矿池服务这边需不需要再启动一个Dogecoin的全节点服务啊。矿池这边如果使用的是switcher接入，那么这套配置能否兼容。

**Comment by bxlkm** [comment]
已经解决，需要狗币的全节点。
