### ISSUE TITLE
[分支重命名 / Branch renamed] master -> legacy; deveth -> master

### ISSUE THREAD

**Issue by YihaoPeng** [btccom/btcpool#230]
`deveth`分支已被重命名为`master`，原`deveth`分支暂时保留。
原`master`分支的代码已被合并到`legacy`。
默认分支已被设为`master`，内容与原`deveth`分支相同。

The `deveth` branch has been renamed to `master` and the original deveth branch is temporarily reserved.
The original code in `master` branch has been merged into `legacy`.
The default branch has been set to `master` and the content is the same as the original `deveth` branch.

**Comment by AndyChenW** [comment]
赞
