### ISSUE TITLE
在mining.notify中isClean=true，但是矿机还是继续下发该任务前的计算结果

### ISSUE THREAD

**Issue by zhshy11** [btccom/btcpool#235]
如题：在mining.notify中isClean=true，但是矿机还是继续下发该任务前的计算结果，导致sumbit的返回是rejected share: Job not found (=stale)。请问，该问题大家是否碰到这种问题？

**Comment by bmhjyu** [comment]
这时我们需要检查矿机或者挖矿软件本身的实现。同时也可能存在另外一种情况：矿机在收到该任务的前一刻发现了上一个任务的有效碰撞。

**Comment by SwimmingTiger** [comment]
挖矿软件不支持`isClean`是完全有可能的。比如我们之前就遇到过某些版本的阿瓦隆矿机固件不支持`isClean`，总是会提交`stale share`。对此没有好办法，只能等矿机厂商发布支持该特性的固件。

此外，就像 bmhjyu 说的那样，即使支持该特性的挖矿软件也有可能提交`stale share`，因为你从发送新任务到挖矿软件接收到，需要一段时间。而TCP是全双工的，挖矿软件完全可以在这段时间发送一个对你来说`stale`了的share，但挖矿软件并不知情。
