### ISSUE TITLE
SServer在获取“get-user-list”过程中会出现timeout的问题

### ISSUE THREAD

**Issue by zhangliang7190** [btccom/btcpool#244]
sserver在启动和运行过程中会出现以下错误：
E0212 11:06:32.344776  5453 Utils.cc:250] unable to request data from: https://xxx/getUserInfo?last_id=1178, error: Timeout was reached
E0212 11:06:32.344987  5453 StratumServer.cc:456] http get request user list fail, url: https://xxx/getUserInfo?last_id=1178

请问是SServer中的那些配置会造成以上问题？
将上面的域名中https改为http后不会出现上述错误

**Comment by bmhjyu** [comment]
造成 timeout 的原因可能有多种，很多情况下与网络配置相关，故此最好能在部署该 sserver 的机器上运行一下 `curl -v <https url>` 来获得较详细的诊断信息（获取用户列表实际上是一个通过 libcurl 的 HTTP GET 操作）。

**Comment by SwimmingTiger** [comment]
偶尔的超时其实没有关系。这可能只是web服务器偶然的响应缓慢。
sserver会持续增量拉取用户列表，所以一次失败并没有太大的影响。即使此时有新用户注册，也只是短时间内无法连进来而已。
