### ISSUE TITLE
decred: upgrade production to 1.4.0

### ISSUE THREAD

**Issue by dajohi** [btccom/btcpool#245]
I believe your Decred production pool is still generating version 5 blocks.
Please see https://voting.decred.org.

**Comment by bmhjyu** [comment]
Oops we are upgrading. Really thanks for reminding us.

**Comment by bmhjyu** [comment]
We have upgraded the nodes and now I see newly mined blocks are v6. Thanks again!

**Comment by dajohi** [comment]
Thank you!
