### ISSUE TITLE
请问大家用这个做矿池有bitcoin节点连接数量多少合适，其他方面的一些优化？

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#246]
如果不考虑机器带宽和性能等因素，连接数是8个比较合适还是800个或者更多合适呢？怎么知道其他大矿池的ip去连接呢？是否是连接上了交易所和矿池等活跃的节点会对自己的矿池有优势？

**Comment by SwimmingTiger** [comment]
感觉bitcoin的孤块问题较少发生啊，所以我们从开始创建起就没有太在意节点的peer数这个问题。
目前，我们只是通过addnode把我们自己在各个地区的节点互相加了peer，对其他节点没有做特别的设置。

我们的以太坊节点倒是刻意设置了min_peer=100。以太坊节点的对端peer太少确实会容易孤块。但是bitcoin好像不太会，因为通常区块都有数分钟的时间广播（别人和你同一时间挖出区块的概率较小）。

**Comment by sslazio2009** [comment]
> 感觉bitcoin的孤块问题较少发生啊，所以我们从开始创建起就没有太在意节点的peer数这个问题。
> 目前，我们只是通过addnode把我们自己在各个地区的节点互相加了peer，对其他节点没有做特别的设置。
> 
> 我们的以太坊节点倒是刻意设置了min_peer=100。以太坊节点的对端peer太少确实会容易成为叔块甚至孤块。但是bitcoin好像不太会，因为通常区块都有数分钟的时间广播（别人和你同一时间挖出区块的概率较小）。

[http://8btc.com/thread-20154-1-1.html](url)  主要是参考了这个三年前潘志标的ppt，上面提到增加节点连接有利于进来，即更快的拿到其他爆块的新题，更快的进来这个优化。博主这边是大矿池爆块多所以我觉得各个地区的节点连起来很对，因为自己爆块多，主要是我们现在百来p的算力，爆块少，所以想多通过多连接节点的方式鸟枪法来让题目更早进来，不知道我这个思路是否正确，怎么验证合适呢？

**Comment by YihaoPeng** [comment]
这是这个PPT中所讲的项目：
http://bitcoinfibre.org/
我不知道现在这个项目是否还活跃

**Comment by sslazio2009** [comment]
> 这是这个PPT中所讲的项目：
> http://bitcoinfibre.org/
> 我不知道现在这个项目是否还活跃。但是因为这个项目直接patch比特币源代码，维护困难，我们已经没有采用这个项目的节点了。

那估计我理解错了，我以为他的bitcoinfibre是高速传播节点，仅仅是blkmaker用rpc调用就用于传播，gbtmaker调用的还是正常的节点，我就是改的17.1版本的节点，将里面的select()改为poll()，现在能连3000的连接，改epoll()有点困难。

**Comment by sslazio2009** [comment]
![default](https://user-images.githubusercontent.com/41941824/53727868-47b74180-3eac-11e9-8876-0f8ab58b996e.png)
