### ISSUE TITLE
LTC联挖狗币问题，无法提交auxblock

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#247]
现在nmc配置按照代码里的配置进行的，但是狗币全节点没有zmq选项，把is_check_zmp修改为false，zmq地址随便写了LTC的地址，rpc使用狗币的地址（狗币rpc测试调用成功）。
found_nmc_blocks也有记录，blk日志就是没有auxblock提交信息，也没有打币成功，LTC可以挖到块。
jobmaker日志：
I0225 06:34:46.102205   312 JobMaker.cc:121] received AuxPowBlock message len: 267
W0225 06:34:46.563555   313 JobMakerBitcoin.cc:304] bestKey is the same as last one: 6661822763787904417
I0225 06:34:52.964422   311 JobMaker.cc:121] received RawGbt message len: 26340
I0225 06:34:52.964670   311 JobMakerBitcoin.cc:264] add rawgbt, height: 1585872, gbthash: a5194b7cb2e81882..., gbtTime(UTC): 2019-02-25 06:34:52, isEmpty:0
I0225 06:34:52.964702   311 JobMaker.cc:126] handleMsg returns true, new stratum job
I0225 06:34:52.964718   311 JobMakerBitcoin.cc:360] remove timeout rawgbt: 2019-02-25 06:33:22|1551076402, height:1585872, isEmptyBlock:0
I0225 06:34:56.020380   312 JobMaker.cc:121] received AuxPowBlock message len: 267
I0225 06:35:02.983788   311 JobMaker.cc:121] received RawGbt message len: 27700
I0225 06:35:02.984174   311 JobMakerBitcoin.cc:264] add rawgbt, height: 1585872, gbthash: 236b97f78e1caf48..., gbtTime(UTC): 2019-02-25 06:35:02, isEmpty:0
I0225 06:35:02.984215   311 JobMaker.cc:126] handleMsg returns true, new stratum job
I0225 06:35:02.984231   311 JobMakerBitcoin.cc:360] remove timeout rawgbt: 2019-02-25 06:33:32|1551076412, height:1585872, isEmptyBlock:0
I0225 06:35:02.984700   311 JobMakerBitcoin.cc:527] --------producer stratum job, jobId: 6661822853061779201, height: 1585872--------
I0225 06:35:02.984719   311 JobMakerBitcoin.cc:529] sjob: {"jobId":6661822853061779201,"gbtHash":"236b97f78e1caf482d1c3f59fcdb6ded8fe7f7b34df5205e3b76f23fc9539f0e","prevHash":"84e1a1639b69ab81c54dd5eb7b098ca0b043b85e43596d751d9195a4cce03465","prevHashBeStr":"cce034651d9195a443596d75b043b85e7b098ca0c54dd5eb9b69ab8184e1a163","height":1585872,"coinbase1":"02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff5903d0321804968c735c686f6e676b6f6e672f7777772e6f6b706f6f6c2e746f702ffabe6d6d3bcdfef5ad00194561e8abd0083b13a11361263021b6cacef6444097a99580d80100000000000000","coinbase2":"ffffffff020d5c0c950000000017a91403575933a05c89601d411726e79bf109a1069004870000000000000000266a24aa21a9edd3d40c686630f0ab8f35eb90a0c25bb91e5ed68f685dc1be3a3047d2f9ed6fc500000000","merkleBranch":"71e342a75352754eee80986c60cfe5a0b20d7d19ea47a280c6b2b20ee0980c7d30e8a77f78601e3669012eb7abd4260a7aadccb032801a3a04e258c0bb8c348d0b671e0891221037604e9e5756f18b2026b2e248af4bd186d23d090f695607ba42b591ce2be29a3daea3fbe477225c882f493446eed465a23e6d15b78cd6cc96474e98dc4399e780cdf22cff7e62b42cee1f88adba8947548cb9d73c8b422327","nVersion":536870912,"nBits":436347211,"nTime":1551076502,"minTime":1551075987,"coinbaseValue":2500615181,"witnessCommitment":"6a24aa21a9edd3d40c686630f0ab8f35eb90a0c25bb91e5ed68f685dc1be3a3047d2f9ed6fc5","nmcBlockHash":"3bcdfef5ad00194561e8abd0083b13a11361263021b6cacef6444097a99580d8","nmcBits":436523380,"nmcHeight":2615651,"nmcRpcAddr":"http://xxxx:22555","nmcRpcUserpass":"xxxx:xxxx","rskBlockHashForMergedMining":"","rskNetworkTarget":"0x0000000000000000000000000000000000000000000000000000000000000000","rskFeesForMiner":"","rskdRpcAddress":"","rskdRpcUserPwd":"","isRskCleanJob":true,"mergedMiningClean":true}

NMC日志：
I0225 06:34:46.102205   312 JobMaker.cc:121] received AuxPowBlock message len: 267
W0225 06:34:46.563555   313 JobMakerBitcoin.cc:304] bestKey is the same as last one: 6661822763787904417
I0225 06:34:52.964422   311 JobMaker.cc:121] received RawGbt message len: 26340
I0225 06:34:52.964670   311 JobMakerBitcoin.cc:264] add rawgbt, height: 1585872, gbthash: a5194b7cb2e81882..., gbtTime(UTC): 2019-02-25 06:34:52, isEmpty:0
I0225 06:34:52.964702   311 JobMaker.cc:126] handleMsg returns true, new stratum job
I0225 06:34:52.964718   311 JobMakerBitcoin.cc:360] remove timeout rawgbt: 2019-02-25 06:33:22|1551076402, height:1585872, isEmptyBlock:0
I0225 06:34:56.020380   312 JobMaker.cc:121] received AuxPowBlock message len: 267
I0225 06:35:02.983788   311 JobMaker.cc:121] received RawGbt message len: 27700
I0225 06:35:02.984174   311 JobMakerBitcoin.cc:264] add rawgbt, height: 1585872, gbthash: 236b97f78e1caf48..., gbtTime(UTC): 2019-02-25 06:35:02, isEmpty:0
I0225 06:35:02.984215   311 JobMaker.cc:126] handleMsg returns true, new stratum job
I0225 06:35:02.984231   311 JobMakerBitcoin.cc:360] remove timeout rawgbt: 2019-02-25 06:33:32|1551076412, height:1585872, isEmptyBlock:0
I0225 06:35:02.984700   311 JobMakerBitcoin.cc:527] --------producer stratum job, jobId: 6661822853061779201, height: 1585872--------
I0225 06:35:02.984719   311 JobMakerBitcoin.cc:529] sjob: {"jobId":6661822853061779201,"gbtHash":"236b97f78e1caf482d1c3f59fcdb6ded8fe7f7b34df5205e3b76f23fc9539f0e","prevHash":"84e1a1639b69ab81c54dd5eb7b098ca0b043b85e43596d751d9195a4cce03465","prevHashBeStr":"cce034651d9195a443596d75b043b85e7b098ca0c54dd5eb9b69ab8184e1a163","height":1585872,"coinbase1":"02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff5903d0321804968c735c686f6e676b6f6e672f7777772e6f6b706f6f6c2e746f702ffabe6d6d3bcdfef5ad00194561e8abd0083b13a11361263021b6cacef6444097a99580d80100000000000000","coinbase2":"ffffffff020d5c0c950000000017a91403575933a05c89601d411726e79bf109a1069004870000000000000000266a24aa21a9edd3d40c686630f0ab8f35eb90a0c25bb91e5ed68f685dc1be3a3047d2f9ed6fc500000000","merkleBranch":"71e342a75352754eee80986c60cfe5a0b20d7d19ea47a280c6b2b20ee0980c7d30e8a77f78601e3669012eb7abd4260a7aadccb032801a3a04e258c0bb8c348d0b671e0891221037604e9e5756f18b2026b2e248af4bd186d23d090f695607ba42b591ce2be29a3daea3fbe477225c882f493446eed465a23e6d15b78cd6cc96474e98dc4399e780cdf22cff7e62b42cee1f88adba8947548cb9d73c8b422327","nVersion":536870912,"nBits":436347211,"nTime":1551076502,"minTime":1551075987,"coinbaseValue":2500615181,"witnessCommitment":"6a24aa21a9edd3d40c686630f0ab8f35eb90a0c25bb91e5ed68f685dc1be3a3047d2f9ed6fc5","nmcBlockHash":"3bcdfef5ad00194561e8abd0083b13a11361263021b6cacef6444097a99580d8","nmcBits":436523380,"nmcHeight":2615651,"nmcRpcAddr":"http://xxx:22555","nmcRpcUserpass":"xxx:xxx","rskBlockHashForMergedMining":"","rskNetworkTarget":"0x0000000000000000000000000000000000000000000000000000000000000000","rskFeesForMiner":"","rskdRpcAddress":"","rskdRpcUserPwd":"","isRskCleanJob":true,"mergedMiningClean":true}

sserver日志：
I0225 06:38:11.861588 32705 StratumMinerBitcoin.cc:266] rejected share: Job not found (=stale), worker: 4022257qq.dfx14x82, versionMask: 00000000, share(jobId: 6661823555777732609, ip: 110.190.71.71, userId: 69, workerId: 8997985275271333676, time: 1551076691/2019-02-25 06:38:11, height: 1585875, blkBits: 1a02214b/516182488816.219482, shareDiff: 65536, status: 21/Job not found (=stale))
I0225 06:38:12.673934 32705 StratumMinerBitcoin.cc:266] rejected share: Job not found (=stale), worker: 4022257qq.dfx14x77, versionMask: 00000000, share(jobId: 6661823555777732609, ip: 110.190.71.71, userId: 69, workerId: -3973791329082307301, time: 1551076692/2019-02-25 06:38:12, height: 1585875, blkBits: 1a02214b/516182488816.219482, shareDiff: 65536, status: 21/Job not found (=stale))
I0225 06:38:12.883591 32705 StratumMinerBitcoin.cc:266] rejected share: Job not found (=stale), worker: 4022257qq.dfx14x127, versionMask: 00000000, share(jobId: 6661823555777732609, ip: 110.190.71.71, userId: 69, workerId: -1633629725505481172, time: 1551076692/2019-02-25 06:38:12, height: 1585875, blkBits: 1a02214b/516182488816.219482, shareDiff: 65536, status: 21/Job not found (=stale))
I0225 06:38:13.703927 32705 StratumMinerBitcoin.cc:266] rejected share: Job not found (=stale), worker: 4022257qq.dfx14x60, versionMask: 00000000, share(jobId: 6661823555777732609, ip: 110.190.71.71, userId: 69, workerId: -657891546152369754, time: 1551076693/2019-02-25 06:38:13, height: 1585875, blkBits: 1a02214b/516182488816.219482, shareDiff: 65536, status: 21/Job not found (=stale))
I0225 06:38:13.802397 32705 StratumMinerBitcoin.cc:266] rejected share: Job not found (=stale), worker: 4022257qq.dfx14x110, versionMask: 00000000, share(jobId: 6661823555777732609, ip: 110.190.71.71, userId: 69, workerId: 1271597894062103337, time: 1551076693/2019-02-25 06:38:13, height: 1585875, blkBits: 1a02214b/516182488816.219482, shareDiff: 65536, status: 21/Job not found (=stale))
I0225 06:38:15.561060 32705 StratumMinerBitcoin.cc:266] rejected share: Job not found (=stale), worker: 4022257qq.dfx14x6, versionMask: 00000000, share(jobId: 6661823555777732609, ip: 110.190.71.71, userId: 69, workerId: 8568750529130416430, time: 1551076695/2019-02-25 06:38:15, height: 1585875, blkBits: 1a02214b/516182488816.219482, shareDiff: 65536, status: 21/Job not found (=stale))
I0225 06:38:16.647483 32705 StratumMinerBitcoin.cc:266] rejected share: Job not found (=stale), worker: 4022257qq.dfx14x89, versionMask: 00000000, share(jobId: 6661823555777732609, ip: 110.190.71.71, userId: 69, workerId: 3348352912732162130, time: 1551076696/2019-02-25 06:38:16, height: 1585875, blkBits: 1a02214b/516182488816.219482, shareDiff: 65536, status: 21/Job not found (=stale))
I0225 06:38:16.953253 32705 StratumMinerBitcoin.cc:266] rejected share: Job not found (=stale), worker: 4022257qq.dfx14x138, versionMask: 00000000, share(jobId: 6661823510939216641, ip: 110.190.71.71, userId: 69, workerId: -6284612644423246832, time: 1551076696/2019-02-25 06:38:16, height: 1585875, blkBits: 1a02214b/516182488816.219482, shareDiff: 32768, status: 21/Job not found (=stale))
I0225 06:38:17.933984 32705 StratumMinerBitcoin.cc:266] rejected share: Job not found (=stale), worker: 4022257qq.dfx14x138, versionMask: 00000000, share(jobId: 6661823555777732609, ip: 110.190.71.71, userId: 69, workerId: -6284612644423246832, time: 1551076697/2019-02-25 06:38:17, height: 1585875, blkBits: 1a02214b/516182488816.219482, shareDiff: 32768, status: 21/Job not found (=stale))

**Comment by langubtc** [comment]
blk里面应该是有日志信息的，你可以检查一下。如果found_nmc_blocks有记录，你可以查询一下区块hash，狗狗很容易孤块。

**Comment by bxlkm** [comment]
好的，我先查一下，我使用的是doge1.10版本，跟全节点参数配置和nmc节点没有配置zmq关系大吗？因为狗币全节点没有zmq的开启选项 。

**Comment by langubtc** [comment]
狗狗核心需要开启钱包功能

**Comment by langubtc** [comment]
参考以下配置：
rpcuser=dogecoinrpc
rpcpassword=xxxxxxxxxxxxxxxxxxxxxxxxxxx
rpcthreads=4

rpcallowip=172.16.0.0/12
rpcallowip=192.168.0.0/16
rpcallowip=10.0.0.0/8

zmqpubrawblock=tcp://0.0.0.0:8337
zmqpubrawtx=tcp://0.0.0.0:8337
zmqpubhashtx=tcp://0.0.0.0:8337
zmqpubhashblock=tcp://0.0.0.0:8337

# use 1G memory for utxo, depends on your machine's memory
dbcache=2000

daemon=1

addnode=99.162.146.53
addnode=85.25.118.19
addnode=195.85.215.174
addnode=47.89.13.175
addnode=35.183.27.127
addnode=92.35.194.188
addnode=13.125.252.52
addnode=104.153.44.246
addnode=2a01:4f8:200:442d::2

**Comment by bxlkm** [comment]
多谢，我先按照您的这个配置，重新配置下全节点再观察下。

**Comment by bxlkm** [comment]
zmqpubrawblock=tcp://0.0.0.0:8337
zmqpubrawtx=tcp://0.0.0.0:8337
zmqpubhashtx=tcp://0.0.0.0:8337
zmqpubhashblock=tcp://0.0.0.0:8337

这4项参数里面没有啊 我1.10版本默认端口22556是p2p 22555是rpc 能问下您的版本是哪个吗？

**Comment by bxlkm** [comment]
@langubtc 大神 请再次指点一下，数据库里面孤块标志为0 应该不是孤块。但是就是不能接受挖出的块，着急！！！

**Comment by langubtc** [comment]
dogecoin-1.10.0,孤块你是指ltc 还是狗狗？如果是狗狗你应该看nmc那张表，同时nmcauxmaker里面有配置RPC地址，请确实是否是正确。

**Comment by bxlkm** [comment]
@langubtc 多谢指点，是nmc表里的数据，LTC正常暴块了，nmc里面也写数据了，LTC爆的块区块上能查到，狗币如果是孤块的话应该怎么查看，区块游览器里没有找到，rpc地址测试也正确，唯独nmcauxmaker里面的配置is_check_zmq和zmq_address地址不知道应该怎么配置，因为狗币的1.10全节点里面根本找不到zmq的4项配置，这个是否is_check_zmq=false，zmq_address随便写一个就行呢？

**Comment by bxlkm** [comment]
@langubtc 我查了blk失败的日志，里面没有aux提交的信息，是不是API调用的不对，我先把代码升级到最新版试一下，现在用的是2018年12月份的deveth分支的

**Comment by langubtc** [comment]
保持is_check_zmq = false;就可以。可以使用现在的master分支

**Comment by bxlkm** [comment]
@langubtc 多谢，已经部署完在测试了。

**Comment by bxlkm** [comment]
@langubtc 大神你好，master分支部署已经能够挖出狗币了，但是nmc支付里面设置的打币地址，不能接收到狗币，但是节点钱包会自动生成地址接收，这是什么原因？怎么配置才能接收到？

**Comment by SwimmingTiger** [comment]
要想`nmcauxmaker`里面设置的地址生效，Dogecoin的节点必须支持`createauxblock`这个RPC。但是它很可能不支持，于是只能使用传统的`getauxblock`，这个RPC不支持指定收款地址，收益只会打到节点内部的钱包里面。
如果想要支持`createauxblock`，必须给节点打补丁。
https://github.com/namecoin/namecoin-core/commit/aba8a5b947cb13f7ac0e087830e24f9bf2201b98
这是当时给Namecoin做的补丁。Dogecoin应该可以参考。

**Comment by bxlkm** [comment]
@SwimmingTiger 非常感谢，应该就是这个问题了。

**Comment by bxlkm** [comment]
@SwimmingTiger  有没有变相的方法，把收币地址设置成节点默认打币地址，不知道dogecoin的节点API有没有类似方法，请大神指点。
