### ISSUE TITLE
请问博主gbtmaker jobmaker  poolwatcher blkmaker这四个服务是否合成一个服务效率更高？

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#251]
主要是gbt这个topic太大了，十多兆的量，有没可能直接把jobmaker合并到gebmaker或者更加极端就这四个服务合成一个服务负责拿题发爆块等，就通过kafka组job给sserver？这种思路是否合理能探讨一下吗？
另外如果其他爆块时间短的币种，通过kafka来是否会带来一定的延迟，这个博主有测试过吗？

**Comment by bmhjyu** [comment]
这当然是有实现可能的，btcpool 本身的架构就有替换任何一个组件的弹性。然而这都可能会带来灵活性上的损失，比如未来若增加多种联合挖矿的支持而对应币种的 RPC 又需要不同转换，那如果使用大一统型的 jobmaker 很可能就要对 jobmaker 进行频繁改动及部署。

**Comment by sslazio2009** [comment]
> 这当然是有实现可能的，btcpool 本身的架构就有替换任何一个组件的弹性。然而这都可能会带来灵活性上的损失，比如未来若增加多种联合挖矿的支持而对应币种的 RPC 又需要不同转换，那如果使用大一统型的 jobmaker 很可能就要对 jobmaker 进行频繁改动及部署。

原来如此，按照您的经验增加联合挖矿的币种是否有很多币种需要去增加？然后请问目前这个里面有个namecoin是域名币，这个gwmaker是什么币种的呢，配置和这个域名币的不一样？

**Comment by SwimmingTiger** [comment]
我们在BCH实现了`getblocktemplate_light`这个RPC，用计算好的`merkle branch`代替`transactions`，这样gbt就小了很多。
可以考虑把`getblocktemplate_light`移植到BTC。
这是BCH上的实现：
https://github.com/btccom/bitcoin-abc-1/commits/lightgbt
https://github.com/btccom/bitcoin-abc-1/commits/lightgbt-v0.18.3

**Comment by bmhjyu** [comment]
> > 这当然是有实现可能的，btcpool 本身的架构就有替换任何一个组件的弹性。然而这都可能会带来灵活性上的损失，比如未来若增加多种联合挖矿的支持而对应币种的 RPC 又需要不同转换，那如果使用大一统型的 jobmaker 很可能就要对 jobmaker 进行频繁改动及部署。
> 
> 原来如此，按照您的经验增加联合挖矿的币种是否有很多币种需要去增加？然后请问目前这个里面有个namecoin是域名币，这个gwmaker是什么币种的呢，配置和这个域名币的不一样？

我们将币种大致分为了两种：

- `getblocktemplate` 类型，该类型以 BTC 及其山寨币为代表，其 RPC 可以获取原始的交易内容然后由矿池打包生成挖矿任务，对应的就是 gbtmaker 组件。
- `getwork` 类型，该类型以 ETH 为代表，其 RPC 获取到的只是交易打包好之后的区块头，矿池不做打包交易的动作，对应的就是 gwmaker 组件。

**Comment by sslazio2009** [comment]
> > > 这当然是有实现可能的，btcpool 本身的架构就有替换任何一个组件的弹性。然而这都可能会带来灵活性上的损失，比如未来若增加多种联合挖矿的支持而对应币种的 RPC 又需要不同转换，那如果使用大一统型的 jobmaker 很可能就要对 jobmaker 进行频繁改动及部署。
> > 
> > 
> > 原来如此，按照您的经验增加联合挖矿的币种是否有很多币种需要去增加？然后请问目前这个里面有个namecoin是域名币，这个gwmaker是什么币种的呢，配置和这个域名币的不一样？
> 
> 我们将币种大致分为了两种：
> 
>     * `getblocktemplate` 类型，该类型以 BTC 及其山寨币为代表，其 RPC 可以获取原始的交易内容然后由矿池打包生成挖矿任务，对应的就是 gbtmaker 组件。
> 
>     * `getwork` 类型，该类型以 ETH 为代表，其 RPC 获取到的只是交易打包好之后的区块头，矿池不做打包交易的动作，对应的就是 gwmaker 组件。

学习了，感谢楼主

**Comment by sslazio2009** [comment]
> 我们在BCH实现了`getblocktemplate_light`这个RPC，用计算好的`merkle branch`代替`transactions`，这样gbt就小了很多。
> 可以考虑把`getblocktemplate_light`移植到BTC。
> 这是BCH上的实现：
> https://github.com/btccom/bitcoin-abc-1/commits/lightgbt
> https://github.com/btccom/bitcoin-abc-1/commits/lightgbt-v0.18.3

这个不错，之前那个topic一波都要快100ms，现在这个10ms就传完了
