### ISSUE TITLE
请教一下博主kafka_repeater算力聚合的思路

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#252]
当前在伊拉克/伊朗 中国大陆地区 加拿大部署了三个矿池节点，采用kafka_repeater汇合之后是一个总的信息，没有每个矿池节点的信息。如果对每个矿池节点的数据也希望和原来一样详细，是不同节点使用不同的topic名去汇合到一个数据库（各节点原来的详细数据）然后写一个相加的程序来汇总到另一张表（汇总数据）好一些，还是每个矿池节点维护自己节点的数据，kafka_repeater后写一个汇总的数据？
或者这两种方案都不行有更加合适的思路呢？

**Comment by bmhjyu** [comment]
有几点可以帮助选择：

- 使用 Kafka repeater 的代价是每一个 share 都要重复传输。
- 汇总数据库表的数据量，在 share 比较多的时候显然就小多了。
- sharelogger/slparser/statshttpd 可以视为参考实现，其实这些都是可以替换成使用者自行开发的组件的。

**Comment by sslazio2009** [comment]
> 有几点可以帮助选择：
> 
>     * 使用 Kafka repeater 的代价是每一个 share 都要重复传输。
> 
>     * 汇总数据库表的数据量，在 share 比较多的时候显然就小多了。
> 
>     * sharelogger/slparser/statshttpd 可以视为参考实现，其实这些都是可以替换成使用者自行开发的组件的。

针对您回复的第一点，我模拟三万台矿机，cpu以及内存带宽都增加不大，是其他方面有什么影响吗？
针对您回复的第二点现在这样跨洲际的情况不使用Kafka repeater来聚合算力，开发一个程序读每个数据库的表然后相加到一张新表里面更加合适吗？想请教一下您这边Kafka repeater是使用来干什么的呢，怎么一个场景？开发的初衷是聚合算力后来发现不合适吗？
针对您回复的第三点现在改动不大，主要把statshttpd也挂在sharelogger后面用，8个服务改得只剩下4个了。

**Comment by bmhjyu** [comment]
> > 有几点可以帮助选择：
> > ```
> > * 使用 Kafka repeater 的代价是每一个 share 都要重复传输。
> > 
> > * 汇总数据库表的数据量，在 share 比较多的时候显然就小多了。
> > 
> > * sharelogger/slparser/statshttpd 可以视为参考实现，其实这些都是可以替换成使用者自行开发的组件的。
> > ```
> 
> 针对您回复的第一点，我模拟三万台矿机，cpu以及内存带宽都增加不大，是其他方面有什么影响吗？
> 针对您回复的第二点现在这样跨洲际的情况不使用Kafka repeater来聚合算力，开发一个程序读每个数据库的表然后相加到一张新表里面更加合适吗？想请教一下您这边Kafka repeater是使用来干什么的呢，怎么一个场景？开发的初衷是聚合算力后来发现不合适吗？
> 针对您回复的第三点现在改动不大，主要把statshttpd也挂在sharelogger后面用，8个服务改得只剩下4个了。

Kafka repeater 确实是可以实现聚合算力，如果还想在聚合后知道来源的话那么你需要一些处理来标识 share 的来源，这可以是不同 topic，实现上应该也不难做。之前的回答初衷主要还是因为这样需要的带宽比本地数据库聚合之后要大一些，两者并没有一定的优劣之分。如果查看 repeater 源码的话，可以发现其实它除了转发还有一些 share 格式转换的功能。这是因为在以往开发过程中有新需求升级了 share 的格式，为了使矿池可以平滑升级而加入的。
