### ISSUE TITLE
博主，你好！为什么有些矿池打包交易中只有coinbase？这算不算空包？

### ISSUE THREAD

**Issue by Seymour-w** [btccom/btcpool#254]

**Comment by YihaoPeng** [comment]
通常把这样只有coinbase交易的区块称为空块。出现空块的原因是多方面的，比如矿池采用了“在接收到完整的区块前先挖空块”的策略，或者是矿池的区块链网络节点本身就没有收到可打包的交易。

**Comment by Seymour-w** [comment]
非常感谢您的回答！ 我还请教两个问题：
1. 打空包是不是可以降低孤块的概率？
2. 什么情况下一个块里包含2条相同的交易信息？而这个块变成了孤块；
谢谢！

**Comment by YihaoPeng** [comment]
1. 是。
2. `getblocktemplate`不应返回包含两条相同交易信息的结果。如果遇到该问题，请向区块链节点客户端开发者反馈。

**Comment by Seymour-w** [comment]
好的！ 再次感谢！
