### ISSUE TITLE
请教一下博主 “accept stale message” 这个是为什么呢？对过期答案也要接受？

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#255]

**Comment by bmhjyu** [comment]
这个只是 ETH/ETC 特有的一个选项。ETH/ETC 因为出块时间很短，所以存在叔块机制以防止过多的孤块。实际上矿池挖到的块只要块结构合法，即使过期提交到 geth/parity 也会被接受，这样的块将来可能成为叔块而获得一定奖励。所以对于矿机提交的 share 在矿池实现里面也提供了配置选项来使得过期的提交可以被矿池接受，其奖励参照叔块奖励和 share 的难度来计算。这个配置选项名称是 `accept_stale`，在如下几个组件里都存在。
* `sserver` 默认为 false，share 会直接被拒绝，矿工会收到一个错误消息。如果设置为 true 则 share 会被接受，但是返回矿工的消息内会附加字段表示该 share 其实已经过期，这种情况下 share 的状态和通常的被接受有区别，可以在 slparser/statshttpd 内再次进行改变。
* `slparser` 默认为 false，对于接受的过期 share 统计收益时将其剔除。如果设置为 true 则会参照叔块奖励比例来统计其收益。
* `statshttpd` 默认为 false，对于接受的过期 share 统计算力时将其归类为拒绝，如果设置为 true 则归类为接受。

**Comment by sslazio2009** [comment]
> 这个只是 ETH/ETC 特有的一个选项。ETH/ETC 因为出块时间很短，所以存在叔块机制以防止过多的孤块。实际上矿池挖到的块只要块结构合法，即使过期提交到 geth/parity 也会被接受，这样的块将来可能成为叔块而获得一定奖励。所以对于矿机提交的 share 在矿池实现里面也提供了配置选项来使得过期的提交可以被矿池接受，其奖励参照叔块奖励和 share 的难度来计算。这个配置选项名称是 `accept_stale`，在如下几个组件里都存在。
> 
>     * `sserver` 默认为 false，share 会直接被拒绝，矿工会收到一个错误消息。如果设置为 true 则 share 会被接受，但是返回矿工的消息内会附加字段表示该 share 其实已经过期，这种情况下 share 的状态和通常的被接受有区别，可以在 slparser/statshttpd 内再次进行改变。
> 
>     * `slparser` 默认为 false，对于接受的过期 share 统计收益时将其剔除。如果设置为 true 则会参照叔块奖励比例来统计其收益。
> 
>     * `statshttpd` 默认为 false，对于接受的过期 share 统计算力时将其归类为拒绝，如果设置为 true 则归类为接受。

感谢，有btc使用了一个名为okkong的固件，stale特别高再加上这个更新让我误以为需要接受这个
