### ISSUE TITLE
sserver 异常退出

### ISSUE THREAD

**Issue by onigirisan** [btccom/btcpool#256]
遇到一个sserver频繁重启的问题，排查下来没有发现crash日志，但是退出码是141
看源码sserver也没有处理sigpipe信号，会是个问题导致的吗？

**Comment by YihaoPeng** [comment]
已经在这个提交中修复该问题。
https://github.com/btccom/btcpool/commit/ee1ddc1457d7fc4f7fa46f396dcfdf88a920723b
