### ISSUE TITLE
TargetToDiff/DiffToTarget居然不能对等?

### ISSUE THREAD

**Issue by oyangjian** [btccom/btcpool#258]
uint256 target;
void DiffToTarget(1024, target);
...

但是 TargetToDiff(target) != 1024???
这里这2个非要做个Diff1的处理吗？名字是对等的,但是值不对等.

**Comment by bmhjyu** [comment]
我在测试代码中尝试了如下的用例
```
TEST(Common, DiffConversion) {
  uint256 target;
  DiffToTarget(1024, target);
  auto d = TargetToDiff(target);
  ASSERT_EQ(1024u, d);
}
```
结果表明是对等的，你可以构造并共享一个出问题的代码用例吗？

**Comment by oyangjian** [comment]
我是用ZEC编译的.

**Comment by bmhjyu** [comment]
> 我是用ZEC编译的.

嗯我们发现转换中的一个 bug，该问题已经在 8a0773279902a49b6941e21019f20f480faeefc1 这个 commit 中修正。
