### ISSUE TITLE
installation script not available

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#259]
The "install_btcpool.sh" is not available per the instruction here:
https://github.com/btccom/btcpool/blob/master/docs/INSTALL-BTCPool.md

Please advice.

**Comment by YihaoPeng** [comment]
It is recommended to deploy or test with Docker now:
https://github.com/btccom/btcpool/tree/master/docker/btcpool/deploy

"install_btcpool.sh" is obsolete and has been removed. We will update the documentation.

**Comment by xwen01** [comment]
Thanks. Do you plan to add base images for other coins?

**Comment by bmhjyu** [comment]
> Thanks. Do you plan to add base images for other coins?

By far the dockerfiles already cover all the coins supported.
