### ISSUE TITLE
unknown message type from namecoind 

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#260]
大神好：
      BTC联挖NMC最近版本出现了点问题，btc全节点版本0.16.3 nmc版本0.17.0 其他消息都正常，全节点都已开启zmq配置选项，但是nmcauxmaker日志出现以下信息
E0412 08:07:03.661418   184 GbtMaker.cc:621] unknown message type from namecoind: ^T^A^@^@
E0412 08:07:03.661746   184 GbtMaker.cc:621] unknown message type from namecoind: 2U~_}$????fR?#^E.?s?cX?~]?i~R^H?O^^X!
E0412 08:09:05.805706   184 GbtMaker.cc:621] unknown message type from namecoind: ^V^A^@^@
E0412 08:09:05.805768   184 GbtMaker.cc:621] unknown message type from namecoind: $J?]?*?sPL?(^T8?^Z/?D?^E?W9?Y?~FG^A?)
E0412 08:11:50.357964   184 GbtMaker.cc:621] unknown message type from namecoind: ^X^A^@^@
E0412 08:11:50.358103   184 GbtMaker.cc:621] unknown message type from namecoind: ~Fb?>p=~N[4~\?X?^D@^T~A?X@(^\?+R]x??^]Ol
E0412 08:17:59.534041   184 GbtMaker.cc:621] unknown message type from namecoind: ^Z^A^@^@
E0412 08:17:59.534140   184 GbtMaker.cc:621] unknown message type from namecoind: ?~O?]F?j^]Df??eq????D?~B?~T?K^D~\j?~@??
E0412 08:35:41.887724   184 GbtMaker.cc:621] unknown message type from namecoind: ^\^A^@^@
E0412 08:35:41.887805   184 GbtMaker.cc:621] unknown message type from namecoind: ??a+??+?0????ּ??^MQ^\??f?~Wn^L~EP~D'?

**Comment by YihaoPeng** [comment]
可能需要像比特币一样增加对以下字段的读取：
```
const string sequence =
std::string(static_cast<char *>(zSequence.data()), zSequence.size());
```

**Comment by YihaoPeng** [comment]
已经提交一个修复，你可以试试：
https://github.com/btccom/btcpool/commit/0522458942979ed6b9ea5af969c0b89096d7de62

**Comment by bxlkm** [comment]
多谢，我一会测试下。

**Comment by bxlkm** [comment]
bitcoin/GbtMaker.cc: In member function 'void GbtMaker::threadListenBitcoind()':
/work/okpool-service/src/bitcoin/GbtMaker.cc:346:37: error: unable to find numeric literal operator 'operator""ms'
         std::this_thread::sleep_for(20ms); // so we sleep and try again
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/btcpool.dir/src/bitcoin/GbtMaker.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/btcpool.dir/all] Error 2

**Comment by bxlkm** [comment]
@YihaoPeng dash什么时候支持一下，我们自己根据bitcoin的方式DIY的dash暂时可用，但没考虑那么多因素，能否支持一下。

**Comment by YihaoPeng** [comment]
你们可以把你们对dash的支持提交给我们吗，然后我们看看有没有后续需要进行的工作。

**Comment by bxlkm** [comment]
我们在老版本上做的代码有点乱，怎么提交啊

**Comment by bxlkm** [comment]
我可以压缩直接发给你也行

**Comment by YihaoPeng** [comment]
压缩之后上传到这里吧。我来合并。

**Comment by bxlkm** [comment]
好的，我一会就发 在最早版本的deveth上面做的，代码有点乱，请见谅。

**Comment by bxlkm** [comment]
@YihaoPeng 忘记件事情忘记说了，为了使用一个数据库多表的操作，里面增加了表后缀的选项，看下是否有这样的需求，如果不需要的话，数据库操作部分就不需要做修改。

**Comment by YihaoPeng** [comment]
好的。

**Comment by bxlkm** [comment]
@YihaoPeng 老大你好，提出个需求建议，还是把一个数据库操作多币种表的后缀支持加一下吧，要不每次更新都需要megre一下，现有版本是使用多库后缀，但是需要一个数据库实例操作多张表的话，还得自己修改，建议支持下。

**Comment by bxlkm** [comment]
@YihaoPeng 已经fix了，测试没有问题了。
