### ISSUE TITLE
jobmaker RawGbt Map is empty

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#261]
Kafka.cc:81] consumer librdkafka version: 0.9.1
I0413 13:56:24.427659    93 Kafka.cc:163] add brokers: 172.31.58.133:9092
I0413 13:56:24.427728    93 Kafka.cc:170] create topic handle: BtcRskRawGw
I0413 13:56:29.458571    93 JobMakerBitcoin.cc:162] consume latest rawgbt messages from kafka...
I0413 13:56:34.458698    93 JobMakerBitcoin.cc:173] consume latest rawgbt messages done
I0413 13:56:34.458889    93 JobMaker.cc:213] wait for worker 139956248889088exiting
W0413 13:56:54.458935   126 JobMakerBitcoin.cc:295] RawGbt Map is empty
W0413 13:57:14.459288   126 JobMakerBitcoin.cc:295] RawGbt Map is empty
W0413 13:57:34.459606   126 JobMakerBitcoin.cc:295] RawGbt Map is empty
W0413 13:57:54.459904   126 JobMakerBitcoin.cc:295] RawGbt Map is empty
W0413 13:58:14.460213   126 JobMakerBitcoin.cc:295] RawGbt Map is empty
没有矿机接入的情况下，全节点正常，gbt也正常，blk正常，kafka，zookeeper正常，jobmaker出现这样的情况属于正常吗？

**Comment by YihaoPeng** [comment]
不正常。请检查`jobmaker.cfg`的`rawgbt_topic`是否与`gbtmaker.cfg`中的匹配。

如果匹配，请尝试用`/work/kafka/bin/kafka-console-consumer.sh`来打印`rawgbt_topic`，看看是否正常输出。

该问题最常见的原因是`rawgbt`的消息大小超过限制。请确保你在所有broker的`server.properties`中添加了如下设置：
```
# increate message size limit
message.max.bytes=60000000
replica.fetch.max.bytes=80000000
```

如果消息接收依然有问题，请检查`/work/kafka/logs/server.log`

**Comment by bxlkm** [comment]
@YihaoPeng 之前代码对于dash的https://github.com/dashpay/dash/releases/download/v0.13.1.0/dashcore-0.13.1.0-x86_64-linux-gnu.tar.gz这个全节点版本通讯时时需要依赖https://github.com/codablock/bls-signatures/archive/v20181101.zip这个库编译。

**Comment by YihaoPeng** [comment]
好的。感谢提供源代码。我之后会进行合并。

**Comment by bxlkm** [comment]
我也很感谢有这么好的一个开源项目，向你们致敬，提供源代码是我应该做的。
