### ISSUE TITLE
 JSON-RPC call failed: [    2147483647,    "Unknown",    null ]

### ISSUE THREAD

**Issue by joenhon** [btccom/btcpool#262]
JSON-RPC call failed: [
   2147483647,
   "Unknown",
   null
]
各位大神 这是个什么情况

**Comment by SwimmingTiger** [comment]
出现在哪里？

**Comment by joenhon** [comment]
挖矿程序上

**Comment by joenhon** [comment]
> 出现在哪里？

挖矿程序上

**Comment by joenhon** [comment]
![image](https://user-images.githubusercontent.com/39330202/56096919-9c74c000-5f20-11e9-92fa-58d1ed38cd20.png)

**Comment by joenhon** [comment]
![image](https://user-images.githubusercontent.com/39330202/56096928-b2828080-5f20-11e9-97d3-4cb80c7f0079.png)

**Comment by joenhon** [comment]
我都不知道 我是不是安装成功了 运行挖矿测试程序 直接报root@joen-virtual-machine:/work/btcpool/build/run_simulator# ./simulator -c simulator.cfg -l /tmp/log
F0415 01:18:50.985239 44000 SimulatorMain.cc:158] exception: basic_string::_M_create
*** Check failure stack trace: ***
    @     0x7fa0c82d60cd  google::LogMessage::Fail()
    @     0x7fa0c82d7f33  google::LogMessage::SendToLog()
    @     0x7fa0c82d5c28  google::LogMessage::Flush()
    @     0x7fa0c82d8999  google::LogMessageFatal::~LogMessageFatal()
    @     0x5645d97134b9  (unknown)
    @     0x7fa0c658cb97  __libc_start_main
    @     0x5645d971268a  (unknown)
已放弃 (核心已转储)

**Comment by joenhon** [comment]
root@joen-virtual-machine:/tmp/log# tail -f simulator.INFO 
Log file created at: 2019/04/15 01:18:50
Running on machine: joen-virtual-machine
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0415 01:18:50.983707 44000 SimulatorMain.cc:94] BTC simulator version 2.3.2-262-g0522458
I0415 01:18:50.984303 44000 StratumClient.cc:250] send(68): {"id":1,"method":"mining.subscribe","params":["__simulator__/0.1"]}
I0415 01:18:50.984838 44000 StratumClient.cc:145] recv(39): {"id":1,"jsonrpc":"2.0","result":true}
E0415 01:18:50.984874 44000 StratumClient.cc:191] json result is null, err: 
I0415 01:18:50.985203 44000 StratumClient.cc:302] StratumClientWrapper::stop...
F0415 01:18:50.985239 44000 SimulatorMain.cc:158] exception: basic_string::_M_create

**Comment by joenhon** [comment]
明明自己都说接收到result为true 到了191行就说为空

**Comment by SwimmingTiger** [comment]
这很有问题。看起来你的模拟器发送了一个JSON-RPC1.0请求，但是收到了一个JSON-RPC2.0响应（缺少result字段）。你的sserver.cfg的type是什么？

**Comment by joenhon** [comment]
> 这很有问题。看起来你的模拟器发送了一个JSON-RPC1.0请求，但是收到了一个JSON-RPC2.0响应（缺少result字段）。你的sserver.cfg的type是什么？

![image](https://user-images.githubusercontent.com/39330202/56097116-e8c0ff80-5f22-11e9-8d86-62614b4168ab.png)

**Comment by SwimmingTiger** [comment]
你想要挖掘Siacoin吗？
挖掘Siacoin的代码是不完整并且未经测试的，应该没有办法正常工作。‘
如果你想要挖掘Bitcoin，请设置type为BTC，并且把缺少的配置项补充完整。
建议使用这里的配置文件：
https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg

**Comment by joenhon** [comment]
原来如此 谢谢大佬

**Comment by joenhon** [comment]
> 你想要挖掘Siacoin吗？
> 挖掘Siacoin的代码是不完整并且未经测试的，应该没有办法正常工作。‘
> 如果你想要挖掘Bitcoin，请设置type为BTC，并且把缺少的配置项补充完整。
> 建议使用这里的配置文件：
> https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg
> 当然，`type = "BCH";` 需要改为`type = "BTC";`

{"id":5,"result":null,"error":[400,"Client is not a stratum switcher",null]}
大佬， 这个又是因为什么原因？

**Comment by bmhjyu** [comment]
> > 你想要挖掘Siacoin吗？
> > 挖掘Siacoin的代码是不完整并且未经测试的，应该没有办法正常工作。‘
> > 如果你想要挖掘Bitcoin，请设置type为BTC，并且把缺少的配置项补充完整。
> > 建议使用这里的配置文件：
> > https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg
> > 当然，`type = "BCH";` 需要改为`type = "BTC";`
> 
> {"id":5,"result":null,"error":[400,"Client is not a stratum switcher",null]}
> 大佬， 这个又是因为什么原因？

请在编译时使用 `-DPOOL__WORK_WITH_STRATUM_SWITCHER=OFF` CMake 选项，该选项控制 stratum switcher 的支持，详细的 CMake 选项说明可以在 https://github.com/btccom/btcpool/blob/master/docs/INSTALL-BTCPool.md#cmake-options 找到。

**Comment by joenhon** [comment]
> OFF

非常的感谢

**Comment by joenhon** [comment]
> > > 你想要挖掘Siacoin吗？
> > > 挖掘Siacoin的代码是不完整并且未经测试的，应该没有办法正常工作。” 
> > > 如果你想要挖掘比特币，请设置类型为BTC，并且把缺少的配置项补充完整。
> > > 建议使用这里的配置文件：
> > > [https](https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg)：[//github.com/btccom/btcpool/tree/master/src/bitcoin/cfg](https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg) 
> > > 当然，`type = "BCH";`需要改为`type = "BTC";`
> > 
> > 
> > {“id”：5，“result”：null，“error”：[400，“Client is not a stratum switcher”，null]} 
> > 大佬，这个又是因为什么原因？
> 
> 请在编译时使用`-DPOOL__WORK_WITH_STRATUM_SWITCHER=OFF`CMake选项，该选项控制stratum switcher的支持，详细的CMake选项说明可以在https://github.com/btccom/btcpool/blob/master/docs/INSTALL-BTCPool.md#cmake-options找到。

非常的感谢

**Comment by joenhon** [comment]
> > > 你想要挖掘Siacoin吗？
> > > 挖掘Siacoin的代码是不完整并且未经测试的，应该没有办法正常工作。” 
> > > 如果你想要挖掘比特币，请设置类型为BTC，并且把缺少的配置项补充完整。
> > > 建议使用这里的配置文件：
> > > [https](https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg)：[//github.com/btccom/btcpool/tree/master/src/bitcoin/cfg](https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg) 
> > > 当然，`type = "BCH";`需要改为`type = "BTC";`
> > 
> > 
> > {“id”：5，“result”：null，“error”：[400，“Client is not a stratum switcher”，null]} 
> > 大佬，这个又是因为什么原因？
> 
> 请在编译时使用`-DPOOL__WORK_WITH_STRATUM_SWITCHER=OFF`CMake选项，该选项控制stratum switcher的支持，详细的CMake选项说明可以在https://github.com/btccom/btcpool/blob/master/docs/INSTALL-BTCPool.md#cmake-options找到。

重新CMake了一下  环境全崩😭

**Comment by YihaoPeng** [comment]
make clean，然后把build目录里面和cmake有关的（CMake* CPack* cmake*）删掉再重新运行cmake ......就可以了吧。

**Comment by YihaoPeng** [comment]
因为没有进一步反馈，该issue暂时关闭
