### ISSUE TITLE
如何支持阿里云kafka

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#263]
@YihaoPeng  请教一下老大，使用阿里云kafka需要修改代码吗，还是把基础库需要升级到0.9.1以上版本再进行矿池编译，还是这个版本的库已经兼容。

**Comment by sslazio2009** [comment]
阿里云不行，有参数不符合而且还不让改

**Comment by bxlkm** [comment]
意思是只要kafka参数符合消息尺寸大小 矿池就支持是这个意思吗？

**Comment by sslazio2009** [comment]
> 意思是只要kafka参数符合消息尺寸大小 矿池就支持是这个意思吗？
> 除了# increate message size limit
> message.max.bytes=60000000
> replica.fetch.max.bytes=80000000
> 配置需要添加以外 还需要其他的吗？

嗯，其他的topic都没问题，你可以买着试试，不行可以无条件退款

**Comment by YihaoPeng** [comment]
BCH的话有lightgbt支持，打开就能用。需要用我们patch过的BCH节点。
BTC的话，目前没有lightgbt节点，是直接把交易存储在kafka里面的，消息大小很容易超过限制。

**Comment by YihaoPeng** [comment]
因为没有进一步反馈，该issue暂时关闭
