### ISSUE TITLE
BTC联挖NMC支付地址问题

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#266]
使用最新master版本代码测试（测试网），btc全节点0.16.3 NMC使用0.17.0 接入矿机运行正常，btc测试网可以挖出块，nmc数据库里也有块记录，但是查不到币打到哪里了，nmc里配置的nmc全节点生成的测试打币地址。
与namecoin的全节点有关系吗？

**Comment by YihaoPeng** [comment]
检查blkmaker的日志，找到提交时nmc节点的返回值，里面可能包含错误信息或者请求失败的信息。

**Comment by bxlkm** [comment]
auxcoind  support rpc commands: createauxblock and submitauxblock
I0418 05:35:19.712626   192 BlockMakerBitcoin.cc:859] received StratumJob message, len: 1894
I0418 05:35:19.712682   192 BlockMakerBitcoin.cc:881] StratumJob, jobId: 6680409846162699777, gbtHash: bddf56e9e9f982f8d7a3853148e1d7e1491150c345089140532f866f5a8cb6db

BlockMakerBitcoin.cc:331] received Namecoin SolvedShare message, len: 830
I0418 05:51:10.409438   402 BlockMakerBitcoin.cc:488] rpc call success, submit auxblock response: {"result":true,"error":null,"id":1}
查不到测试网的币在哪里，namecoin的测试网打币地址mn9cm4qCJ34RxvWsCRzU7BrvaMVTTqFTYV，这个地址是在全节点测试网通过全节点getnewaddress生成的。
在全节点使用namecoin-cli查询余额是零，也没有打进全节点钱包地址。

**Comment by bxlkm** [comment]
老大你们好，请教个问题，bch和bsv能不能联合挖nmc啊，这个我没测试过，btc联挖也没出过块。

**Comment by langubtc** [comment]
BCH和BSV都可以联合挖NMC

**Comment by bxlkm** [comment]
非常感谢，我先测试一下。

**Comment by YihaoPeng** [comment]
> 在全节点使用namecoin-cli查询余额是零，也没有打进全节点钱包地址。

你可以查询一下数据库，看看hash是多少（比如是`379badd9c186237e889e27eb80f955d5cbfcec02d43e41451900e6ac793c14af`），然后用
```
namecoin-cli getblock 379badd9c186237e889e27eb80f955d5cbfcec02d43e41451900e6ac793c14af
```

如果没有返回，说明很可能这个块孤掉了。

此外，`namecoin-cli getbalance`不会返回未成熟的余额。所以需要100个区块之后才能看到余额变化。
但是你可以使用`listtransactions`查看未成熟的coinbase交易。

此外，也可以用`namecoin-cli getblockchaininfo`查看当前块高。如果你的NMC节点区块高度长时间没有增长，或者当前`bestblockhash`与区块浏览器的不同，说明你在分叉链上。如果这条链没有人挖，你的coinbase交易就一直不会成熟。

**Comment by bxlkm** [comment]
@YihaoPeng 我在namecoin官网查不到 namecoin多长时间出一次块啊，帮忙查一下出块时间间隔多长，谢了。

**Comment by YihaoPeng** [comment]
namecoin的出块时间应该和bitcoin一样是10分钟。

**Comment by bxlkm** [comment]
@YihaoPeng 搞定了，zmq问题。
