### ISSUE TITLE
启动gbtmaker报错

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#269]
启动gbtmaker（./gbtmaker -c ./gbtmaker.cfg -l ./log_gbtmaker）的时候得到下面的错误：

```
F0421 20:56:03.674497 10922 Kafka.cc:469] Failed to acquire metadata: Local: Timed out
*** Check failure stack trace: ***
    @     0x7fa49823b03d  google::LogMessage::Fail()
    @     0x7fa49823cea3  google::LogMessage::SendToLog()
    @     0x7fa49823abcb  google::LogMessage::Flush()
    @     0x7fa49823d88e  google::LogMessageFatal::~LogMessageFatal()
    @           0x41c2cb  KafkaProducer::checkAlive()
    @           0x40aae0  GbtMaker::init()
    @           0x40835d  main
    @     0x7fa496005830  __libc_start_main
    @           0x4089d9  _start
Aborted (core dumped)
```

请问这个是什么问题呢?

**Comment by langubtc** [comment]
kafka没有连上吧

**Comment by xwen01** [comment]
谢谢你的回复。现在遇到新的报错：

F0423 14:21:22.817415 25414 GbtMakerMain.cc:139] gbtmaker init failure
*** Check failure stack trace: ***
    @     0x7f1f68dbf03d  google::LogMessage::Fail()
    @     0x7f1f68dc0ea3  google::LogMessage::SendToLog()
    @     0x7f1f68dbebcb  google::LogMessage::Flush()
    @     0x7f1f68dc188e  google::LogMessageFatal::~LogMessageFatal()
    @           0x408501  main
    @     0x7f1f66b89830  __libc_start_main
    @           0x4089d9  _start
Aborted (core dumped)

我的gbtmaker.cfg:
#
# gbt maker cfg
#
# @since 2016-06
# @copyright btc.com
#

gbtmaker = {
  # rpc call interval seconds
  rpcinterval = 5;

  # check zmq when startup
  is_check_zmq = true;

  rawgbt_topic = "BtcRawGbt";

  # use RPC `getblocktemplatelight`, only for bch
  lightgbt = false; # if unspecified, default false
};

bitcoind = {
  # bitcoind MUST with zmq options: -zmqpubhashblock, -zmqpubhashtx
  # '-zmqpubhashtx' will use to check zmq is working when startup gbtmaker
  zmq_addr = "tcp://127.0.0.1:3415";

  # rpc settings
  rpc_addr    = "http://127.0.0.1:18332";
  rpc_userpwd = "bitcoinrpc:abc";  # username:password
};

kafka = {
  brokers = "127.0.0.1:9092";
};

请问这个有什么建议吗？
