### ISSUE TITLE
博主您好，我有如下问题想请教，谢谢您的指教

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#270]
最近用最新的master试了一下，有如下问题想请教。
1.现在的编译的时候指定币种是按照什么标准划分的？是新的币种都使用BTC，如果适配新币种例如门罗就把算法文件都拷贝到3part的文件夹内然后改cmake吗，就是参照几个新的用BTC编译的币种grin这种来弄吗？
2.grin的这个看着和btc的挖矿有很大区别，感觉像是只需要poolwatcher取题sserver接矿工就ok，gbtmaker、jobmaker、blkmaker这三个都不需要了吗？
3.ZEC的 poolwatcher模块一直报错说参数少，是目前这个模块还未适配这个币种还是我编译的时候选择错了？一直是运行到了poolwatcherbitcoin里面，两个币种参数不一样
4.主页介绍EquiHash算法的ZCash，Beam一样的算法参数不同所以要区分，不清楚其他币种这个情况多吗？看ccminer挖矿软件和yiimp矿池能做到一套算法一堆币种，所以这个有点奇怪。ETHash / Daggerhashimoto算法的Ethereum和Ethereum Classic就直接挂两个不同钱包能直接用zookeeper的切换就行吗？想用这个适配一个其他算法或者币种，例如用eth的这个算法的其他币种都直接加进来，做出一个机枪池的效果，想请教一下适配是不是工作量很大，需要每个山寨币种都仔细看。然后假如是做成机枪池，pps来结算，用户挖a币种按照a币种来结算，我们觉得挖b币种更加有收益切换挖b，这个时候a和b的全网难度不一样，也在变化中，怎么做精度合适不会算错账呢？

**Comment by bmhjyu** [comment]
> 1.现在的编译的时候指定币种是按照什么标准划分的？是新的币种都使用BTC，如果适配新币种例如门罗就把算法文件都拷贝到3part的文件夹内然后改cmake吗，就是参照几个新的用BTC编译的币种grin这种来弄吗？

BTCPool 的 BTC 是通过链接 bitcoin 节点来实现的，这样我们可以直接使用很多现成的代码来构建区块。对于从它 fork 出来的山寨币，我们都可以通过这种方式实现，否则的话就不行。

> 2.grin的这个看着和btc的挖矿有很大区别，感觉像是只需要poolwatcher取题sserver接矿工就ok，gbtmaker、jobmaker、blkmaker这三个都不需要了吗？

Grin 的节点自带一个 stratum server，我们目前的实现就是利用 poolwatcher 来监听它的任务。

> 3.ZEC的 poolwatcher模块一直报错说参数少，是目前这个模块还未适配这个币种还是我编译的时候选择错了？一直是运行到了poolwatcherbitcoin里面，两个币种参数不一样

我确实没有动过 ZEC 的 poolwatcher。如果有能力，可以自行 gdb 调试一下，这实际上应该是非常简单的。

> 4.主页介绍EquiHash算法的ZCash，Beam一样的算法参数不同所以要区分，不清楚其他币种这个情况多吗？看ccminer挖矿软件和yiimp矿池能做到一套算法一堆币种，所以这个有点奇怪。

其实 ccminer/yiimp 的一套算法一堆币种并不包括 ZCash 和 Beam，这两个币种的 stratum 协议就不一样。

> ETHash / Daggerhashimoto算法的Ethereum和Ethereum Classic就直接挂两个不同钱包能直接用zookeeper的切换就行吗？想用这个适配一个其他算法或者币种，例如用eth的这个算法的其他币种都直接加进来，做出一个机枪池的效果，想请教一下适配是不是工作量很大，需要每个山寨币种都仔细看。然后假如是做成机枪池，pps来结算，用户挖a币种按照a币种来结算，我们觉得挖b币种更加有收益切换挖b，这个时候a和b的全网难度不一样，也在变化中，怎么做精度合适不会算错账呢？

如果两个币种算法和 stratum 协议都一样就可以。

**Comment by sslazio2009** [comment]
> > 4.主页介绍EquiHash算法的ZCash，Beam一样的算法参数不同所以要区分，不清楚其他币种这个情况多吗？看ccminer挖矿软件和yiimp矿池能做到一套算法一堆币种，所以这个有点奇怪。
> 
> 其实 ccminer/yiimp 的一套算法一堆币种并不包括 ZCash 和 Beam，这两个币种的 stratum 协议就不一样。
> 
请教一下 ZCash 和 Beam这两个币种的 stratum 协议的说明资料来源哪有呢？用矿机去抓包确实不一样，网上搜的都是bitcoin的。

**Comment by bmhjyu** [comment]
> > > 4.主页介绍EquiHash算法的ZCash，Beam一样的算法参数不同所以要区分，不清楚其他币种这个情况多吗？看ccminer挖矿软件和yiimp矿池能做到一套算法一堆币种，所以这个有点奇怪。
> > 
> > 
> > 其实 ccminer/yiimp 的一套算法一堆币种并不包括 ZCash 和 Beam，这两个币种的 stratum 协议就不一样。
> 
> 请教一下 ZCash 和 Beam这两个币种的 stratum 协议的说明资料来源哪有呢？用矿机去抓包确实不一样，网上搜的都是bitcoin的。

ZCash 的 stratum 协议可以认为就是 Bitcoin 的，Beam 的 stratum 协议可以参考 https://github.com/BeamMW/beam/wiki/Beam-mining-protocol-API-(Stratum)。

**Comment by YihaoPeng** [comment]
ZCash:
https://github.com/slushpool/poclbm-zcash/wiki/Stratum-protocol-changes-for-ZCash
注意其中的RESERVED字段现在已经具有含义，目前为`final_sapling_root_hash`

BEAM:
https://github.com/BeamMW/beam/wiki/Beam-mining-protocol-API-(Stratum)

**Comment by xwen01** [comment]
> > 1.现在的编译的时候指定币种是按照什么标准划分的？是新的币种都使用BTC，如果适配新币种例如门罗就把算法文件都拷贝到3part的文件夹内然后改cmake吗，就是参照几个新的用BTC编译的币种grin这种来弄吗？
> 
> BTCPool 的 BTC 是通过链接 bitcoin 节点来实现的，这样我们可以直接使用很多现成的代码来构建区块。对于从它 fork 出来的山寨币，我们都可以通过这种方式实现，否则的话就不行。
> 
> > 2.grin的这个看着和btc的挖矿有很大区别，感觉像是只需要poolwatcher取题sserver接矿工就ok，gbtmaker、jobmaker、blkmaker这三个都不需要了吗？
> 
> Grin 的节点自带一个 stratum server，我们目前的实现就是利用 poolwatcher 来监听它的任务。
> 
> > 3.ZEC的 poolwatcher模块一直报错说参数少，是目前这个模块还未适配这个币种还是我编译的时候选择错了？一直是运行到了poolwatcherbitcoin里面，两个币种参数不一样
> 
> 我确实没有动过 ZEC 的 poolwatcher。如果有能力，可以自行 gdb 调试一下，这实际上应该是非常简单的。
> 
> > 4.主页介绍EquiHash算法的ZCash，Beam一样的算法参数不同所以要区分，不清楚其他币种这个情况多吗？看ccminer挖矿软件和yiimp矿池能做到一套算法一堆币种，所以这个有点奇怪。
> 
> 其实 ccminer/yiimp 的一套算法一堆币种并不包括 ZCash 和 Beam，这两个币种的 stratum 协议就不一样。
> 
> > ETHash / Daggerhashimoto算法的Ethereum和Ethereum Classic就直接挂两个不同钱包能直接用zookeeper的切换就行吗？想用这个适配一个其他算法或者币种，例如用eth的这个算法的其他币种都直接加进来，做出一个机枪池的效果，想请教一下适配是不是工作量很大，需要每个山寨币种都仔细看。然后假如是做成机枪池，pps来结算，用户挖a币种按照a币种来结算，我们觉得挖b币种更加有收益切换挖b，这个时候a和b的全网难度不一样，也在变化中，怎么做精度合适不会算错账呢？
> 
> 如果币种算法和 stratum 协议都一样就可以，目前的 BTCPool 支持是通过部署一套 sserver 和多套其它组件实现的，https://github.com/btccom/btcpool/blob/master/docs/INSTALL-BTCPool.md#mining-coin-switcher 有简略的说明。

借贴问一下，如果是Grin，用它自带的stratum server，还需要运行sserver吗？请问有部署grin+btcpool的简单步骤或者教程吗？谢谢！

**Comment by bmhjyu** [comment]
> > > 1.现在的编译的时候指定币种是按照什么标准划分的？是新的币种都使用BTC，如果适配新币种例如门罗就把算法文件都拷贝到3part的文件夹内然后改cmake吗，就是参照几个新的用BTC编译的币种grin这种来弄吗？
> > 
> > 
> > BTCPool 的 BTC 是通过链接 bitcoin 节点来实现的，这样我们可以直接使用很多现成的代码来构建区块。对于从它 fork 出来的山寨币，我们都可以通过这种方式实现，否则的话就不行。
> > > 2.grin的这个看着和btc的挖矿有很大区别，感觉像是只需要poolwatcher取题sserver接矿工就ok，gbtmaker、jobmaker、blkmaker这三个都不需要了吗？
> > 
> > 
> > Grin 的节点自带一个 stratum server，我们目前的实现就是利用 poolwatcher 来监听它的任务。
> > > 3.ZEC的 poolwatcher模块一直报错说参数少，是目前这个模块还未适配这个币种还是我编译的时候选择错了？一直是运行到了poolwatcherbitcoin里面，两个币种参数不一样
> > 
> > 
> > 我确实没有动过 ZEC 的 poolwatcher。如果有能力，可以自行 gdb 调试一下，这实际上应该是非常简单的。
> > > 4.主页介绍EquiHash算法的ZCash，Beam一样的算法参数不同所以要区分，不清楚其他币种这个情况多吗？看ccminer挖矿软件和yiimp矿池能做到一套算法一堆币种，所以这个有点奇怪。
> > 
> > 
> > 其实 ccminer/yiimp 的一套算法一堆币种并不包括 ZCash 和 Beam，这两个币种的 stratum 协议就不一样。
> > > ETHash / Daggerhashimoto算法的Ethereum和Ethereum Classic就直接挂两个不同钱包能直接用zookeeper的切换就行吗？想用这个适配一个其他算法或者币种，例如用eth的这个算法的其他币种都直接加进来，做出一个机枪池的效果，想请教一下适配是不是工作量很大，需要每个山寨币种都仔细看。然后假如是做成机枪池，pps来结算，用户挖a币种按照a币种来结算，我们觉得挖b币种更加有收益切换挖b，这个时候a和b的全网难度不一样，也在变化中，怎么做精度合适不会算错账呢？
> > 
> > 
> > 如果币种算法和 stratum 协议都一样就可以，目前的 BTCPool 支持是通过部署一套 sserver 和多套其它组件实现的，https://github.com/btccom/btcpool/blob/master/docs/INSTALL-BTCPool.md#mining-coin-switcher 有简略的说明。
> 
> 借贴问一下，如果是Grin，用它自带的stratum server，还需要运行sserver吗？请问有部署grin+btcpool的简单步骤或者教程吗？谢谢！

现在暂时还没有，我们将于近期内增加 Grin 相关的文档。

**Comment by xwen01** [comment]
> > > > 1.现在的编译的时候指定币种是按照什么标准划分的？是新的币种都使用BTC，如果适配新币种例如门罗就把算法文件都拷贝到3part的文件夹内然后改cmake吗，就是参照几个新的用BTC编译的币种grin这种来弄吗？
> > > 
> > > 
> > > BTCPool 的 BTC 是通过链接 bitcoin 节点来实现的，这样我们可以直接使用很多现成的代码来构建区块。对于从它 fork 出来的山寨币，我们都可以通过这种方式实现，否则的话就不行。
> > > > 2.grin的这个看着和btc的挖矿有很大区别，感觉像是只需要poolwatcher取题sserver接矿工就ok，gbtmaker、jobmaker、blkmaker这三个都不需要了吗？
> > > 
> > > 
> > > Grin 的节点自带一个 stratum server，我们目前的实现就是利用 poolwatcher 来监听它的任务。
> > > > 3.ZEC的 poolwatcher模块一直报错说参数少，是目前这个模块还未适配这个币种还是我编译的时候选择错了？一直是运行到了poolwatcherbitcoin里面，两个币种参数不一样
> > > 
> > > 
> > > 我确实没有动过 ZEC 的 poolwatcher。如果有能力，可以自行 gdb 调试一下，这实际上应该是非常简单的。
> > > > 4.主页介绍EquiHash算法的ZCash，Beam一样的算法参数不同所以要区分，不清楚其他币种这个情况多吗？看ccminer挖矿软件和yiimp矿池能做到一套算法一堆币种，所以这个有点奇怪。
> > > 
> > > 
> > > 其实 ccminer/yiimp 的一套算法一堆币种并不包括 ZCash 和 Beam，这两个币种的 stratum 协议就不一样。
> > > > ETHash / Daggerhashimoto算法的Ethereum和Ethereum Classic就直接挂两个不同钱包能直接用zookeeper的切换就行吗？想用这个适配一个其他算法或者币种，例如用eth的这个算法的其他币种都直接加进来，做出一个机枪池的效果，想请教一下适配是不是工作量很大，需要每个山寨币种都仔细看。然后假如是做成机枪池，pps来结算，用户挖a币种按照a币种来结算，我们觉得挖b币种更加有收益切换挖b，这个时候a和b的全网难度不一样，也在变化中，怎么做精度合适不会算错账呢？
> > > 
> > > 
> > > 如果币种算法和 stratum 协议都一样就可以，目前的 BTCPool 支持是通过部署一套 sserver 和多套其它组件实现的，https://github.com/btccom/btcpool/blob/master/docs/INSTALL-BTCPool.md#mining-coin-switcher 有简略的说明。
> > 
> > 
> > 借贴问一下，如果是Grin，用它自带的stratum server，还需要运行sserver吗？请问有部署grin+btcpool的简单步骤或者教程吗？谢谢！
> 
> 现在暂时还没有，我们将于近期内增加 Grin 相关的文档。

请问是不是blkmaker，gbtmaker，jobmaker，poolwatcher，sharelogger，slparser，sserver，statshttpd这些都正常运行，配置文件中bitcoind对应的rpc信息用grin node对应的addr，userpwd就行了？
btcpool中提供了针对grin的poolwatcher，sharelogger，slparser，sserver，statshttpd对应的配置文件，但是没有blkmaker，gbtmaker，jobmaker的，是不是这几个不用修改？

谢谢！

**Comment by bmhjyu** [comment]
> 请问是不是blkmaker，gbtmaker，jobmaker，poolwatcher，sharelogger，slparser，sserver，statshttpd这些都正常运行，配置文件中bitcoind对应的rpc信息用grin node对应的addr，userpwd就行了？
> btcpool中提供了针对grin的poolwatcher，sharelogger，slparser，sserver，statshttpd对应的配置文件，但是没有blkmaker，gbtmaker，jobmaker的，是不是这几个不用修改？

Grin 不需要 gbtmaker/jobmaker/blkmaker 这几个组件，它是通过 poolwatcher 来连接到 grin 节点自带的 stratum server 来获取任务并提交爆块的。有一点需要注意的是需要采用我们 fork 过的节点 https://github.com/btccom/grin/tree/v1.0.2-btcpool 才行，因为原始的节点代码中获取的任务没有包含网络难度信息（它的区块头里包含的是累积的网络难度，无法直接使用）。

**Comment by sslazio2009** [comment]
> ZCash:
> https://github.com/slushpool/poclbm-zcash/wiki/Stratum-protocol-changes-for-ZCash
> 注意其中的RESERVED字段现在已经具有含义，目前为`final_sapling_root_hash`
> 
> BEAM:
> https://github.com/BeamMW/beam/wiki/Beam-mining-protocol-API-(Stratum)

您好，我看了下这个，请问还有其他详细的资料吗？类似于代码里面提到的https://github.com/bitcoin/bips/blob/master/bip-0034.mediawiki   getBlockHeightFromCoinbase这个函数对ZEC的没用，想弄个ZEC的poolwatcher

**Comment by xwen01** [comment]
Grin 不需要 gbtmaker/jobmaker/blkmaker 这几个组件，它是通过 poolwatcher 来连接到 grin 节点自带的 stratum server 来获取任务并提交爆块的。有一点需要注意的是需要采用我们 fork 过的节点 https://github.com/btccom/grin/tree/v1.0.2-btcpool 才行，因为原始的节点代码中获取的任务没有包含网络难度信息（它的区块头里包含的是累积的网络难度，无法直接使用）。

好的，那就是只需要用到你们提供配置文件的几个组件，配置文件还需要做额外的修改吗？dbtesting有对应的sql文件吗？

**Comment by xwen01** [comment]
> Grin 不需要 gbtmaker/jobmaker/blkmaker 这几个组件，它是通过 poolwatcher 来连接到 grin 节点自带的 stratum server 来获取任务并提交爆块的。有一点需要注意的是需要采用我们 fork 过的节点 https://github.com/btccom/grin/tree/v1.0.2-btcpool 才行，因为原始的节点代码中获取的任务没有包含网络难度信息（它的区块头里包含的是累积的网络难度，无法直接使用）。

你好，在编译你们fork的grin的时候，发现报错：
error: failed to run custom build command for `ncurses v5.97.0`

--- stderr
grin-btcpool-fork/target/release/build/ncurses-957cac7165fac4c6/out/chtype_size.c:6:21: fatal error: ncurses.h: No such file or directory

请问这个应该怎么解决呢？谢谢！

**Comment by sslazio2009** [comment]
> ZCash:
> https://github.com/slushpool/poclbm-zcash/wiki/Stratum-protocol-changes-for-ZCash
> 注意其中的RESERVED字段现在已经具有含义，目前为`final_sapling_root_hash`
> 
> BEAM:
> https://github.com/BeamMW/beam/wiki/Beam-mining-protocol-API-(Stratum)

还有个问题也想请教博主一下很奇怪，为什么bitcoin和zcash的stratum给矿机一个是大端一个是小端？这个是哪有写吗？

**Comment by YihaoPeng** [comment]
Stratum协议是由实现定义的，第一个做出挖矿软件或者矿池的人从事实上决定了具体字段采用的字节序，其他后来者只能选择兼容。
所以，没有地方写明字段应该采用什么字节序，这取决于第一个实现者的个人喜好。
