### ISSUE TITLE
请教个DCR Switcher的问题

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#271]

**Comment by rocqina** [comment]
现在DCR支持nicehash和tpruvot两种协议的矿机，nicehash可以通过模拟一个mining.notify发送给矿机，根据矿机的submit检查是否满足blake256算法。tpruvot模拟的mining.notify，相比nicehash只是在coinbase1少了结尾少了8个0.并不影响对block头的hash方法，同时tpruvot矿机发送的submit，相较nicehash的submit，只是extraNonce2长度差了4个字节。但是blakehash不出来，请教大神给点方向。
DCR的头是180字节，基本上只是在extraNonce1前或后补四个字节0或者extraNonce2前或后补四个字节0，凑180字节。大神能给tpruvot矿机如何拼头的思路也可以，感谢！

**Comment by rocqina** [comment]
简单的说，就是想根据模拟一个notify下发给矿机，然后根据矿机发过来的submit，反推出矿机用的是那种算法。对于DCR的矿机，因为走nicehash和tpruvot两种可能的协议。所以反推出矿工是用的什么协议的矿机

**Comment by bmhjyu** [comment]
DCR 的两种协议，目前是通过配置选项来决定的。我们在开发过程中误将 NiceHash 的协议认作 gominer，所以选项和代码里都写的是 gominer 但是实际上是 NiceHash 的协议（我们将在未来改正这个问题）。

- NiceHash

  - 矿池回复矿机的 `mining.subscribe` 消息时，`extra nonce 1` 是实际上的 extra nonce 1，`extra nonce 2 size` 字段确实表示的就是 extra nonce 2 的长度。
  - 矿池处理矿机的 `mining.subscribe` 消息时，按照先 `extra nonce 1` 再 `extra nonce 2` 的顺序拼接。

- TPruvot

  - 矿池回复矿机的 `mining.subscribe` 消息时，`extra nonce 1` 的最后四个字节是实际的 extra nonce 1，其长度决定了整个 extra nonce 部分的长度，`extra nonce 2 size` 这个字段实际上没有使用。
  - 矿池处理矿机的 `mining.subscribe` 消息时，按照先 `extra nonce 2` 再 `extra nonce 1` 的顺序拼接。

所以这两种情况下，矿池发送到矿池这个方向上的消息实际上就已经是不一样的了。

**Comment by rocqina** [comment]
感谢大神在矿池这里的解释，我对Switcher这部分也有疑问
Switcher在newStratumSession的时候做了处理    
      case ChainTypeDecredNormal:
		// reversed 12 bytes
		session.sessionIDString = "0000000000000000" + Uint32ToHexLE(session.sessionID)
	case ChainTypeDecredGoMiner:
		// reversed 4 bytes
		session.sessionIDString = Uint32ToHexLE(session.sessionID)
在处理矿机发送subscribe到swticher的时候，直接用到了这个字段
        case ChainTypeDecredNormal:
		fallthrough
	case ChainTypeDecredGoMiner:
		if len(request.Params) >= 1 {
			userAgent, ok := session.stratumSubscribeRequest.Params[0].(string)
			// 判断是否为BTCAgent
			if ok && strings.HasPrefix(strings.ToLower(userAgent), btcAgentClientTypePrefix) {
				session.isBTCAgent = true
			}
		}

		result = JSONRPCArray{JSONRPCArray{JSONRPCArray{"mining.set_difficulty", session.sessionIDString}, JSONRPCArray{"mining.notify", session.sessionIDString}}, session.sessionIDString, 8}
		请教这里的处理逻辑是有什么意义，我如果直接用Uint32ToHex(session.sessionID)代替session.sessionIDString，对于nicehash的情况，我收到的extranonce2是8个字节的，而处理TPruvot，始终是四个字节，而且每次的值都不变

**Comment by rocqina** [comment]
需要指点一下
当矿池下发任务notify，矿机发送submit的时候，nicehash和tpruvot构建header的公式是一样的吗
这是nicehash矿机构建的header，然后对头进行blake256hash验证
header := dcr_nversion + revertPeerByteIn4Bytes(dcr_preHash) + dcr_coinbase1[:208] + revertPeerByte(nonce) + extraNonce1 + extraNonce2 + "0000000000000000000000000000000000000000" + dcr_coinbase2

现在TPruvot用同样的方式验证blake256hash就不通过。

之前session.sessionIDString = "0000000000000000" + Uint32ToHexLE(session.sessionID)
result = JSONRPCArray{JSONRPCArray{JSONRPCArray{"mining.set_difficulty", session.sessionIDString}, JSONRPCArray{"mining.notify", session.sessionIDString}}, session.sessionIDString, 8}
模拟notify发给TPruvot矿机以后接收到的extraNonce2是一个12个字节长度，不确定这种矿机应该怎么构建dcr的头

**Comment by bmhjyu** [comment]
> 需要指点一下
> 当矿池下发任务notify，矿机发送submit的时候，nicehash和tpruvot构建header的公式是一样的吗
> 这是nicehash矿机构建的header，然后对头进行blake256hash验证
> header := dcr_nversion + revertPeerByteIn4Bytes(dcr_preHash) + dcr_coinbase1[:208] + revertPeerByte(nonce) + extraNonce1 + extraNonce2 + "0000000000000000000000000000000000000000" + dcr_coinbase2
> 
> 现在TPruvot用同样的方式验证blake256hash就不通过。
> 
> 之前session.sessionIDString = "0000000000000000" + Uint32ToHexLE(session.sessionID)
> result = JSONRPCArray{JSONRPCArray{JSONRPCArray{"mining.set_difficulty", session.sessionIDString}, JSONRPCArray{"mining.notify", session.sessionIDString}}, session.sessionIDString, 8}
> 模拟notify发给TPruvot矿机以后接收到的extraNonce2是一个12个字节长度，不确定这种矿机应该怎么构建dcr的头

这部分实际上在昨天的回复里面已经提到了，我们举个例子，假设在 tpruvot 方式下 extra nonce 1 字段是 `000000000000000012345678`，那么矿机和挖矿软件是把最后四个 12345678 当作 extra nonce 1，前面的字节长度是 extra nonce 2 size 也就是8个字节，**拼接时需要先 extra nonce 2 再 extra nonce 1**。

**Comment by rocqina** [comment]
@bmhjyu 大神，你说的拼接dcr包头我能理解，但是我困惑的是，矿机提交过来的是12个字节的extraNonce2，按理说应该是8个字节，怎么截取这个字段作为extraNonce2，比如我收到矿机submit的extraNonce2格式：“0000000045f6000080000001”
extraNonce1就是Uint32ToHex(session.sessionID)

**Comment by bmhjyu** [comment]
哦矿机提交确实是忘记了解释，这时提交的其实已经是 extra nonce 2 + extra nonce 1 了，前面的八个字节是 extra nonce 2，相关代码可以参见 https://github.com/btccom/btcpool/blob/feabc434b18514d66b520cb9c1526affcbb35c39/src/decred/StratumServerDecred.cc#L139 这里。

**Comment by bmhjyu** [comment]
另外，现在的 master 分支其实已经无需使用 switcher 了，它的功能已经集成进 sserver 里面，我们将来也不会再维护它了。

**Comment by rocqina** [comment]
好的，我也会尽快了解新的sserver替换switcher的处理，感谢
