### ISSUE TITLE
请教一个Zcash的问题,如何根据单位时间的share计算出算力情况.

### ISSUE THREAD

**Issue by azure-sea** [btccom/btcpool#272]
你好,请教一个Zcash的问题.zcash如何根据单位时间的share计算算力情况.这个与btc的算法不一致.我使用btc的计算方式无法得出结果.

**Comment by sslazio2009** [comment]
单位时间的share数乘以2的32次方除以10的12次方再除以单位时间就是的

**Comment by YihaoPeng** [comment]
对于zcash来说，应该是 hashrate (hash/s) = 2^8192 (hash) / t (s)

8192是zcash的bdiff1中前导0所具有的比特数可表示的数值数量。

**Comment by azure-sea** [comment]
> 单位时间的份额数乘以2的32次方除以10的12次方再除以单位时间就是的

我上面都说使用btc的方式无法得到结果.兄弟你这是搞事情.

**Comment by azure-sea** [comment]
> 对于zcash来说，应该是哈希值（sol / s）= share_diff_sum * 2 ^ 8192（解决方案）/ t（s）
> 
> 8192是zcash的bdiff1中前导0所具有的比特数可表示的数值数量。它表示，如果散列函数是均匀映射，则运算8192次得到一个满足难度1的份额的概率为1。

谢谢,我先通过这个试试.

**Comment by YihaoPeng** [comment]
请注意我的公式中有输入错误，我已经进行更正（应该是2^13，也就是8192，而不是2^8192）

**Comment by azure-sea** [comment]
嗯,已经看到了.非常感谢大佬.还有没有其他币种的计算方式的资料. 网上对于这些小币资料好少.

**Comment by YihaoPeng** [comment]
`算力 = 算力因子 * share / 时间`

| 币种 | 算法 | Diff 1 (bits) | 算力因子 |
| ---- | ---- | ---------- | -------- |
| BTC/BCH/UBTC/SBTC | SHA256d | 0x1d00ffff | 2 ^ 32 |
| ETH | Ethash | 0x2100ffff | 1 |
| DCR | Blake256 | 0x1d00ffff | 2 ^ 32 |
| LTC | Scrypt | 0x1f00ffff | 2 ^ 16 |
| Grin | Cuckaroo29 | | 42 |
|          | Cuckatoo31+ | | 42 |
| ZCash | EquiHash (n=144, k=5) | 0x1f07ffff | 2 ^ 13 |
| Beam | EquiHash (n=150, k=5) | | 1 |

一个Python版的BitsToTarget函数：
```py
bits=0x187fffff
exp=bits >> 24
base = bits & 0x00ffff
target = base * 2**(8*(exp-3))
print '%064x' % target
```

**Comment by azure-sea** [comment]
谢谢,大佬的开源精神点赞!!!.

**Comment by rocqina** [comment]
@YihaoPeng  Zec的2的13次方用Python版的BitsToTarget函数，算不出来前面有13个0，请教一下这个算力因子怎么算出来的？

**Comment by huwentao1** [comment]
@YihaoPeng 这个算力因子是怎么算出来的，计算公式可以详细解释一下吗
