### ISSUE TITLE
提个小建议,项目构建不是很合理

### ISSUE THREAD

**Issue by yqsy** [btccom/btcpool#273]
个人在搭建环境时的一些观点:

1. 不应该直接使用root账户
2. 不应该强制工作目录为"/work", 并且与运行时目录耦合
  2.1. 二进制bin -> 直接 sudo make install 至 /usr/local/bin
  2.2. 配置文件 -> 有默认选项, 读取/etc/btcpool/xx.cfg 等等,  源代码目录提供全量的配置文件templete,用户自己选择使用哪些配置.
  2.3. 日志文件 -> 有默认选项,写入/var/btcpool/xxx.log 等等
  2.4. 实时提示 -> 命令行可以默认打印出glog的日志,方便查找问题
  2.5. 部署文档 -> 建议分分段落,加一个table of content. 并且600行的部署文档可以精简到200行内. 减少他人的学习时间

ps: 部署了两天还没搞好,心累.

**Comment by yqsy** [comment]
而且默认的配置文件都是有问题的. 既然开源,能否整理的干净,整洁,利落一些?

**Comment by YihaoPeng** [comment]
1. 你可以自己切换到其他用户运行该程序，这些进程并不需要特殊的权限。
2. 你可以使用 `POOL__INSTALL_PREFIX` cmake选项修改安装位置，比如安装到/usr/local/btcpool。很多开源项目在自行构建时都使用自定义的目录结构（而不是把文件分散在 `/usr/local/bin` `/usr/local/etc` 等处）。
ps: 我们推荐使用docker运行BTCPool的各个进程。最近我还添加了一个一键启动BTC测试环境的`docker-compose`：
https://github.com/btccom/btcpool/tree/autotest/docker/btcpool/test/btc
在该目录运行如下命令就可以启动所有组件（配置文件用于回归测试。可以自行修改配置文件用于bitcoin testnet或者mainnet）：
```
# 前台运行
docker-compose up

# 后台运行
docker-compose up -d
```

**Comment by YihaoPeng** [comment]
默认的配置文件确实是有问题的，因为针对不同的币种需要不同的配置项。
把所有币种的配置项都写上去确实是一个解决方案，但似乎并不是最佳方案。
比较好的方法似乎是每次构建一个币种（就像针对BTC的构建不支持BCH一样，针对BTC的构建也不支持BEAM；针对Grin的构建不支持ETH，等），然后就可以复制针对这个币种的配置文件到安装目录。

不过这需要对构建系统做很多调整，可能近期不会完成。我们还是先把所有配置项都复制到默认配置文件里面去。

**Comment by yqsy** [comment]
好吧.  我把这个issue 关闭了. 主要是想发泄一下情绪.  这只是一个矿池程序, 竟然有上十个组件, 配置文件源码中有两份, 生成目录中有一份(拷贝过去的), 其中一份配置还缺斤少两,跑不起来:
1. /work/btcpool/src/bitcoin/cfg/gbtmaker.cfg  ,  没有rawgbt_topic
2. /work/btcpool/src/bitcoin/cfg/jobmaker.cfg,   rawgbt_topic = "RawGbt";   ,   那为什么 blkmaker.cfg   rawgbt_topic = "BtcRawGbt"; 同一个变量名称描述不同的主题吗, 还是什么含义. 
3. 明明是btc,为什么配置中要写BCH.... 

并且跑不起来起码console打印一下哪一个配置读取的有问题, 没有的. 要去tail看日志.

哎... 工作给任务要研究这一块, 不然真的不想研究.   难受... - -. 真的不想在部署这个事情上花费精力.

**Comment by oyangjian** [comment]
配置按照默认配置都不是问题。我觉得最大的问题是编译btcpool依赖于bitcoin litecoin等源代码。应该把里面的script 构建coinbase交易重写。这样编译一套代码即可。类似于yiimp。

**Comment by bmhjyu** [comment]
> 配置按照默认配置都不是问题。我觉得最大的问题是编译btcpool依赖于bitcoin litecoin等源代码。应该把里面的script 构建coinbase交易重写。这样编译一套代码即可。类似于yiimp。

这是一个历史遗留问题，改进的呼声和意愿一直都有，只是现实比较骨感，开发人力资源比较缺乏无法在短期内实现。

**Comment by YihaoPeng** [comment]
我认为我们是刻意选择这个方案的。因为区块链硬分叉和分叉币的大量存在，维护一个正确实现各个币种共识规则的代码库是非常困难的。直接重用各个币种官方实现的源代码是最佳解决方案。

**Comment by bmhjyu** [comment]
嗯，我所指的改进，其实是可以不依赖 btc/ltc 代码编译其它币种。

**Comment by YihaoPeng** [comment]
你可以使用`-l stderr`或者省略`-l`参数，此时日志会重定向到标准错误。
> 并且跑不起来起码console打印一下哪一个配置读取的有问题, 没有的. 要去tail看日志.

**Comment by YihaoPeng** [comment]
此外，做为对该发泄的硬核回应：

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

**Comment by yqsy** [comment]
> 你可以使用`-l stderr`或者省略`-l`参数，此时日志会重定向到标准错误。
> 
> > 并且跑不起来起码console打印一下哪一个配置读取的有问题, 没有的. 要去tail看日志.

ok

**Comment by YihaoPeng** [comment]
> 明明是btc,为什么配置中要写BCH....

因为相关代码被BTC/BCH/UBTC/LTC/ZCash共享，所以它们目前具有相同的参考配置文件。

https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg 该目录中的部分配置文件是从一个BCH部署中复制的。

**Comment by yqsy** [comment]
> > 明明是btc,为什么配置中要写BCH....
> 
> 因为相关代码被BTC/BCH/UBTC/LTC/ZCash共享，所以它们目前具有相同的参考配置文件。
> 
> https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg 该目录中的部分配置文件是从一个BCH部署中复制的。

所以我觉得最好就是让一个没有接触过这个矿池框架的,但是有比特币和c++基础的,可以按照配置在一个小时内部署整套程序,并且摸清楚脉搏.   对于你们内部员工的话也可以节省时间,对于其他人也可以方便搭建环境,一起分享研究..  把时间花在刀刃上.  

当然肯定我自身也有问题,因为其他人说可以按照文档做下来可以做到,我花了两天还没有做到. 我继续尝试一下, 感谢你的回复!
