### ISSUE TITLE
LTC rejected share issue！！！

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#275]
I0424 06:39:09.404570    10 StratumMinerBitcoin.cc:285] rejected share: Low difficulty, worker: aaa.bbb, versionMask: 1c1da000, share(jobId: 6683346814661991169, ip: 183.221.180.14, userId: 69, workerId: 3833542270014404010, time: 1556087949/2019-04-24 06:39:09, height: 1619982, blkBits: 1a016b5e/774617773497.668945, shareDiff: 16384, status: 23/Low difficulty)

什么情况才会出现？

**Comment by YihaoPeng** [comment]
1. 确认使用了 `CHAIN_TYPE=LTC` 的构建，并且sserver配置文件中`type=LTC`
2. 确认你的挖矿软件正在运行LTC的算法。
3. 确认`enable_dev_mode`没有被打开。如果该选项打开，则矿机一定会提交低难度share（因为`dev_fixed_difficulty`的默认值小于最低难度）。
4. 如果以上都没问题，请Debug构建项目，然后将包含Low Difficulty的完整sserver日志贴到这里，我们会检查hash值计算部分的实现是否正确。

**Comment by YihaoPeng** [comment]
该问题有进展吗？

**Comment by YihaoPeng** [comment]
问题没有进展，暂时关闭
