### ISSUE TITLE
sserver kafka报错，请问正常吗？

### ISSUE THREAD

**Issue by zhoushouchang** [btccom/btcpool#276]
I0425 17:41:25.666807 28285 Kafka.cc:32] RDKAFKA-3-FAIL: rdkafka#producer-2developer:9092/0: Receive failed: Disconnected
I0425 17:41:25.666923 28285 Kafka.cc:32] RDKAFKA-3-ERROR: rdkafka#producer-2developer:9092/0: Receive failed: Disconnected
I0425 17:41:25.695876 28289 Kafka.cc:32] RDKAFKA-3-FAIL: rdkafka#producer-3developer:9092/0: Receive failed: Disconnected
I0425 17:41:25.695917 28289 Kafka.cc:32] RDKAFKA-3-ERROR: rdkafka#producer-3developer:9092/0: Receive failed: Disconnected
I0425 17:41:25.726641 28293 Kafka.cc:32] RDKAFKA-3-FAIL: rdkafka#producer-4developer:9092/0: Receive failed: Disconnected
I0425 17:41:25.726681 28293 Kafka.cc:32] RDKAFKA-3-ERROR: rdkafka#producer-4developer:9092/0: Receive failed: Disconnected

**Comment by zhoushouchang** [comment]
启动后10分钟样子报这个错误

**Comment by YihaoPeng** [comment]
如果可以自行恢复，就应该没问题。
