### ISSUE TITLE
GbtMaker，BtcRawGbt消息大小超过4M

### ISSUE THREAD

**Issue by zhoushouchang** [btccom/btcpool#277]
GbtMaker，BtcRawGbt消息大小超过4M，而比特币区块大小限制1M。请问若此时挖到块，块的大小会超过1M而导致错误吗？

**Comment by bmhjyu** [comment]
BtcRawGbt 消息是 base64 编码过的 getblocktemplate 返回的 JSON 加上其它一些信息，这个文本的形式比序列化之后的二进制区块是大很多的。实际上 bitcoind 在生产 block template 的时候是会检查区块链共识的区块大小限制，从而限制放进 block template 的交易数量的。一般情况下，只要 jobmaker 生成的 coinbase 交易序列化为二进制后小于100字节就不会超过限制。
