### ISSUE TITLE
gbtmarker启动报错bitcoind rpc failure

### ISSUE THREAD

**Issue by chenzhi201901** [btccom/btcpool#278]
报错如下：
E0425 20:07:04.411371  5864 Utils.cc:272] server responded with code: 500
E0425 20:07:04.411665  5864 GbtMaker.cc:161] bitcoind rpc failure
E0425 20:07:04.411764  5864 GbtMaker.cc:235] get rawgbt failure
bitcoind已经启动，telnet rpc 8332是通的，
![image](https://user-images.githubusercontent.com/50005235/56780876-8c5bbb00-6813-11e9-9311-66d6ddeb4f4e.png)
请问如何解决？

**Comment by zhoushouchang** [comment]
bitcoind还没同步完

**Comment by chenzhi201901** [comment]
同步完才能连接服务器吗，是否要同步完所有的区块？

> bitcoind还没同步完

**Comment by zhoushouchang** [comment]
同步完rpc才会返回数据，而不是错误码500。debug.log可以查看同步状态

**Comment by chenzhi201901** [comment]
> 同步完rpc才会返回数据，而不是错误码500。debug.log可以查看同步状态

现在同步比特币区块现在要多大的磁盘空间？ 或者运行testnet能跑起来btcpool吗

**Comment by zhoushouchang** [comment]
testnet可以跑btcpool

**Comment by yurisyb** [comment]
Hi

this is my error,


root@testpool:/work/btcpool/build# telnet 127.0.0.1 8332
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

HTTP/1.1 400 Bad Request
Content-Type: text/html
Connection: close
Date: Mon, 10 Jun 2019 05:02:25 GMT
Content-Length: 94

<HTML><HEAD>
<TITLE>400 Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
</BODY></HTML>
Connection closed by foreign host.

How to fix this?

**Comment by YihaoPeng** [comment]
@yurisyb 8332 is a HTTP (JSON-RPC) port of bitcoind, so you need a HTTP client instead of telnet.
I use curl:
```
curl --user bitcoinrpc:passwd --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblocktemplate", "params": [] }' -H 'content-type: text/plain' http://localhost:8332
```

**Comment by YihaoPeng** [comment]
问题没有进展，暂时关闭。
No new progress, temporarily closed.
