### ISSUE TITLE
关于miner注册用户

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#279]
请问miner在连接stratum server挖矿时，可以不用注册直接挖吗？目前不注册会报错“authorize failed”，miner端会出现“failed to login mining pool"，如果打开enableAutoReg，miner端会得到”login failed: timeout“。

**Comment by YihaoPeng** [comment]
自动注册需要一个监听zookeeper节点的注册服务：[initUserCoin](https://github.com/btccom/btcpool-go-modules/tree/master/initUserCoin)。需要配置它的：
```
    "ZKAutoRegWatchDir": "/stratumSwitcher/bitcoin_autoreg/",
    "UserAutoRegAPI": {
        "IntervalSeconds": 10,
        "URL": "http://127.0.0.1:8000/autoreg.php",            
        "User": "admin",
        "Password": "admin",
        "DefaultCoin": "btc",
        "PostData": {
            "sub_name": "{sub_name}",
            "region_name": "cn",
            "currency": "BTC"
        }
},
```

它可以把矿机的认证转换为基于web的子账户名注册请求（发送`Content-Type`为`application/json`的POST请求）。你们可以自己实现web api（请求内容可以自定义，只用`{sub_name}`替换子账户名的位置就好）。`PostData`里面也可以包含你们需要的key等。

这里有一组如何实现自动注册API的例子：
https://github.com/btccom/btcpool/blob/master/install/api-sample/autoreg.php
https://github.com/btccom/btcpool/blob/master/install/api-sample/userlist-autoreg.php

前者用于被`initUserCoin`调用实现子账户名注册，后者是sserver的user-list-api，可以列出注册后的新子账户。

**Comment by YihaoPeng** [comment]
如果没有该服务，sserver发到zookeeper中的注册请求就不会得到响应，子账户也就不会创建，于是矿机也不会得到响应。

**Comment by xwen01** [comment]
> 自动注册需要一个监听zookeeper节点的注册服务：[initUserCoin](https://github.com/btccom/btcpool-go-modules/tree/master/initUserCoin)。需要配置它的：
> 
> ```
>     "ZKAutoRegWatchDir": "/stratumSwitcher/bitcoin_autoreg/",
>     "UserAutoRegAPI": {
>         "IntervalSeconds": 10,
>         "URL": "http://127.0.0.1:8000/autoreg.php",            
>         "User": "admin",
>         "Password": "admin",
>         "DefaultCoin": "btc",
>         "PostData": {
>             "sub_name": "{sub_name}",
>             "region_name": "cn",
>             "currency": "BTC"
>         }
> },
> ```
> 
> 它可以把矿机的认证转换为基于web的子账户名注册请求（发送`Content-Type`为`application/json`的POST请求）。你们可以自己实现web api（请求内容可以自定义，只用`{sub_name}`替换子账户名的位置就好）。`PostData`里面也可以包含你们需要的key等。
> 
> 这里有一组如何实现自动注册API的例子：
> https://github.com/btccom/btcpool/blob/master/install/api-sample/autoreg.php
> https://github.com/btccom/btcpool/blob/master/install/api-sample/userlist-autoreg.php
> 
> 前者用于被`initUserCoin`调用实现子账户名注册，后者是sserver的user-list-api，可以列出注册后的新子账户。

谢谢。所以要单独安装initUserCoin模块对吧？然后把autoreg.php对应的url配置到UserAutoRegAPI的“URL”?

**Comment by xwen01** [comment]
> 自动注册需要一个监听zookeeper节点的注册服务：[initUserCoin](https://github.com/btccom/btcpool-go-modules/tree/master/initUserCoin)。需要配置它的：
> 
> ```
>     "ZKAutoRegWatchDir": "/stratumSwitcher/bitcoin_autoreg/",
>     "UserAutoRegAPI": {
>         "IntervalSeconds": 10,
>         "URL": "http://127.0.0.1:8000/autoreg.php",            
>         "User": "admin",
>         "Password": "admin",
>         "DefaultCoin": "btc",
>         "PostData": {
>             "sub_name": "{sub_name}",
>             "region_name": "cn",
>             "currency": "BTC"
>         }
> },
> ```
> 
> 它可以把矿机的认证转换为基于web的子账户名注册请求（发送`Content-Type`为`application/json`的POST请求）。你们可以自己实现web api（请求内容可以自定义，只用`{sub_name}`替换子账户名的位置就好）。`PostData`里面也可以包含你们需要的key等。
> 
> 这里有一组如何实现自动注册API的例子：
> https://github.com/btccom/btcpool/blob/master/install/api-sample/autoreg.php
> https://github.com/btccom/btcpool/blob/master/install/api-sample/userlist-autoreg.php
> 
> 前者用于被`initUserCoin`调用实现子账户名注册，后者是sserver的user-list-api，可以列出注册后的新子账户。

谢谢回复！我已经安装了initUserCoin模块，配置文件改成如下:

{
    "UserListAPI": {
        "grin": "http://127.0.0.1/userlist-autoreg.php"
    },
    "IntervalSeconds": 10,
    "ZKBroker": [ "127.0.0.1:2181" ],
    "ZKSwitcherWatchDir": "/stratumSwitcher/btcbcc/",
    "EnableUserAutoReg": true,
    "ZKAutoRegWatchDir": "/stratumSwitcher/bitcoin_autoreg/",
    "UserAutoRegAPI": {
        "IntervalSeconds": 10,
        "URL": "http://127.0.0.1/autoreg.php",
        "User": "admin",
        "Password": "admin",
        "DefaultCoin": "grin",
        "PostData": {
            "sub_name": "{sub_name}",
            "region_name": "cn",
            "currency": "GRIN"
        }
    },
    "StratumServerCaseInsensitive": false,
    "ZKUserCaseInsensitiveIndex": "/stratumSwitcher/bitcoin_case/"
}

目前测试并没有自动注册，也没有生成userlist.json，请问这是什么原因呢？谢谢！

**Comment by YihaoPeng** [comment]
`sserver`本身已经内置了`stratumSwitcher`能实现的所有功能，所以只需要像bitcoin一样在`sserver.cfg`添加以下配置即可：
https://github.com/btccom/btcpool/blob/ed6dc8f42c729ebeb5b4748b80ff310ac63a2129/src/bitcoin/cfg/sserver(multi-chains).cfg#L139

`zookeeper_auto_reg_watch_dir`与`ZKAutoRegWatchDir`对应。

**Comment by xwen01** [comment]
谢谢！
