### ISSUE TITLE
DCR的拒绝率太高

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#280]
I0428 10:46:54.547458   287 StratumMinerDecred.cc:170] rejected share: Low difficulty, worker: zhangliang.001, share(jobId: 6684894987617371649, ip: 114.247.223.60, userId: 1287, workerId: -8701873834372045927, time: 1556448414/2019-04-28 10:46:54, height: 339591, blkBits: 181e41b5/36338926918.842728, shareDiff: 65536, voters: 5, status: 23/Low difficulty)
I0428 10:46:54.721005   287 StratumMinerDecred.cc:170] rejected share: Low difficulty, worker: zhangliang.001, share(jobId: 6684894987617371649, ip: 114.247.223.60, userId: 1287, workerId: -8701873834372045927, time: 1556448414/2019-04-28 10:46:54, height: 339591, blkBits: 181e41b5/36338926918.842728, shareDiff: 65536, voters: 5, status: 23/Low difficulty)
I0428 10:46:54.976198   287 StratumMinerDecred.cc:170] rejected share: Low difficulty, worker: zhangliang.001, share(jobId: 6684894987617371649, ip: 114.247.223.60, userId: 1287, workerId: -8701873834372045927, time: 1556448414/2019-04-28 10:46:54, height: 339591, blkBits: 181e41b5/36338926918.842728, shareDiff: 65536, voters: 5, status: 23/Low difficulty)
大概有50%的拒绝率，这个跟配置有关系吗

**Comment by rocqina** [comment]
矿机刚连进来几分钟拒绝率高，看log都是low_diffculty,之后稳定就正常了

**Comment by bmhjyu** [comment]
请贴一下所有组件的配置和日志，以及矿机的型号。如果有可能的话最好要抓一下包，这样才能比较有效地进行分析。
