### ISSUE TITLE
请教一下博主关于btcagent的问题，兼容其他币种

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#283]
现在想照葫芦画瓢弄一个ZEC币种版本的代理，sserver代码里面矿机登录回复给矿机{"id": 1, "result": ["SESSION_ID", "NONCE_1"], "error": null}（NONCE_1 is first part of the block header nonce (in hex).）把连接的session_id下发下去了，请问如果代理连接多台机器，能否把挂代理的机器都设置成代理的session_id，或者有什么思路能让代理连接的矿工都能有合适的session_id？例如直接增加一个cmd让server分配下发给矿机？

另外之前的zec的poolwatcher我试了下还是有如下问题不明白请博主指教，发题是{"id": null, "method": "mining.notify", "params": ["JOB_ID", "VERSION", "PREVHASH", "MERKLEROOT", "RESERVED", "TIME", "BITS", CLEAN_JOBS]}  如果从其他矿池取题发空块的题给我们矿机，怎么合成这个MERKLEROOT选项呢？

**Comment by bmhjyu** [comment]
> 现在想照葫芦画瓢弄一个ZEC币种版本的代理，sserver代码里面矿机登录回复给矿机{"id": 1, "result": ["SESSION_ID", "NONCE_1"], "error": null}（NONCE_1 is first part of the block header nonce (in hex).）把连接的session_id下发下去了，请问如果代理连接多台机器，能否把挂代理的机器都设置成代理的session_id，或者有什么思路能让代理连接的矿工都能有合适的session_id？例如直接增加一个cmd让server分配下发给矿机？

BTCAgent 的原理是这样的，它从 stratum server 拿到四个字节的 extra nonce 1 和八字节的 extra nonce 2 size，然后它自己再为下游的矿机连接分配一个额外的 session id 附加在 stratum server 的 extra nonce 1 之后，同时缩减发送给矿机的 extra nonce 2 size，所以矿机仍然是具有不同的 extra nonce 1 的。这同样可以应用到 ZCash，而且 ZCash 的 nonce 空间有32字节之多，完全是够用的。添加新的命令也是可行的方案，但这样改动显然更大些。

> 另外之前的zec的poolwatcher我试了下还是有如下问题不明白请博主指教，发题是{"id": null, "method": "mining.notify", "params": ["JOB_ID", "VERSION", "PREVHASH", "MERKLEROOT", "RESERVED", "TIME", "BITS", CLEAN_JOBS]} 如果从其他矿池取题发空块的题给我们矿机，怎么合成这个MERKLEROOT选项呢？

实际上这时 poolwatcher 的 raw GBT 消息里面里面是没有 Merkle branch 的（因为是空块），jobmaker 收到这个消息时会直接用配置的 payout address 来生成 coinbase 交易添加进去生产 Merkle root。

**Comment by sslazio2009** [comment]
> > 另外之前的zec的poolwatcher我试了下还是有如下问题不明白请博主指教，发题是{"id": null, "method": "mining.notify", "params": ["JOB_ID", "VERSION", "PREVHASH", "MERKLEROOT", "RESERVED", "TIME", "BITS", CLEAN_JOBS]} 如果从其他矿池取题发空块的题给我们矿机，怎么合成这个MERKLEROOT选项呢？
> 
> 实际上这时 poolwatcher 的 raw GBT 消息里面里面是没有 Merkle branch 的（因为是空块），jobmaker 收到这个消息时会直接用配置的 payout address 来生成 coinbase 交易添加进去生产 Merkle root。

感谢博主解答，代码里面string coinbaseStr = jgbt["coinbasetxn"]["data"].str();按照您说的这个逻辑主要是ZEC的梅尔根树需要coinbasetxn的data字段，我看了我节点十几个高度的这个参数，都或多或少有部分数字不一样，所以请问如果从别的矿池拿到题目要生成我自己的MERKLEROOT的时候这个data的参数该如何确定呢？

**Comment by bmhjyu** [comment]
> 感谢博主解答，代码里面string coinbaseStr = jgbt["coinbasetxn"]["data"].str();按照您说的这个逻辑主要是ZEC的梅尔根树需要coinbasetxn的data字段，我看了我节点十几个高度的这个参数，都或多或少有部分数字不一样，所以请问如果从别的矿池拿到题目要生成我自己的MERKLEROOT的时候这个data的参数该如何确定呢？

抱歉这一部分我没有仔细看就作了不正确的回答，ZCash 的 coinbase 交易因为要分一部分奖励给开发者，所以其中必须用这些开发者的公钥来生产对应的输出。我们发现对应的规则比较复杂，在 jobmaker 中并没有完全自行生产 coinbase 交易（BTC 之类 GBT 类型的币种是自行生成的），而是使用 getblocktemplate 返回的 coinbase 交易模板进行修改，因此现在的 poolwatcher 就无法做这样的操作了。如果想自行开发，那么就需要搞清楚如何应用开发者公钥的规则。

**Comment by sslazio2009** [comment]
> > 感谢博主解答，代码里面string coinbaseStr = jgbt["coinbasetxn"]["data"].str();按照您说的这个逻辑主要是ZEC的梅尔根树需要coinbasetxn的data字段，我看了我节点十几个高度的这个参数，都或多或少有部分数字不一样，所以请问如果从别的矿池拿到题目要生成我自己的MERKLEROOT的时候这个data的参数该如何确定呢？
> 
> 抱歉这一部分我没有仔细看就作了不正确的回答，ZCash 的 coinbase 交易因为要分一部分奖励给开发者，所以其中必须用这些开发者的公钥来生产对应的输出。我们发现对应的规则比较复杂，在 jobmaker 中并没有完全自行生产 coinbase 交易（BTC 之类 GBT 类型的币种是自行生成的），而是使用 getblocktemplate 返回的 coinbase 交易模板进行修改，因此现在的 poolwatcher 就无法做这样的操作了。如果想自行开发，那么就需要搞清楚如何应用开发者公钥的规则。我们之后也会增加这个功能。

好的，感谢博主指导，我再看一下

**Comment by YihaoPeng** [comment]
看起来可以调用 chainparams.cpp 里面的 `GetFoundersRewardAddressAtHeight()` 和 `GetFoundersRewardScriptAtHeight()` 来得到交易的开发者奖励部分。
