### ISSUE TITLE
Switcher的例子去掉了，代码里的逻辑还在

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#287]
想问下大佬，看你们最新的更新，去掉了swicher的编译选项例子，但是我看代码逻辑仍然还保留这部分的逻辑。想了解一下switcher这部分你们只是弃用，但是代码逻辑是不是还会保留。如果我想在以后仍然用switcher，应该还是可以用的，只是你们不更新了？假设你们以后switcehr逻辑有很多新的feature，但是如果不用，仍然用go的switcher，就编译运行来说，后续不会有问题吧。

**Comment by bmhjyu** [comment]
去掉例子的原因是我们发现很多使用矿池代码的人看到了之后就直接使用了这个编译选项，导致编译出的 sserver 无法直接使用（这其实是大部分人的用例）。这部分功能虽然我们不打算维护，但也暂时不会从代码中移除，所以还是可用的。
