### ISSUE TITLE
merged-mining-proxy怎么使用，rpc怎么配置？

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#291]
使用多联挖代理，例如btc联挖nmc和ela默认的blkmaker里面的found_aux_block_table还需要配置吗？nmcmaker怎么配置？merged-mining-proxy里面的rpcserver需要配置到哪里？请大佬给个教程。

**Comment by YihaoPeng** [comment]
默认的blkmaker里面的found_aux_block_table不需要配置，写入数据库的结果是所有币种爆块的混合，没有意义。


merged-mining-proxy里面的RPCServer是配置给它自己的，它自己就是这个RPCServer，这里配置它的监听地址和端口。
nmcmaker需要连接到merged-mining-proxy启动的这个RPCServer，也就是，nmcauxmaker的rpcaddr应该是merged-mining-proxy的监听地址，端口是merged-mining-proxy的监听端口。

**Comment by bxlkm** [comment]
@YihaoPeng 搞定了，多谢。
