### ISSUE TITLE
关于duplicate share

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#292]
对于btc，并没有看到重复提交的处理。假如矿机往矿池的两个端口提交完全一样的share，sserver本身是独立进程，两个端口2个sserver进程，互相并不知道对方提交了什么，所以就有两个完全一样的share进入kafka，在计算用户算力的时候没看到有去重，那就是两条，而对于矿池收益，只是一个任务。我知道对于一个矿机在两个sserver 处的sessionid完全一样的可能的情况很小，但是假设有。

**Comment by rocqina** [comment]
为什么eth会有duplicate share的检查，btc不需要

**Comment by bmhjyu** [comment]
Session ID 的高八位是可配置的 sserver ID，只要在配置中对不同的 sserver 指定不同的值，或者都指定零和相同的 `zookeeper_lock_path` （此时它们必须连接相同的 Zookeeper）就可以保证 session ID 的全局唯一性。

```
  # should be global unique, range: [1, 255]
  # If the id is 0, try to automatically assign one from zookeeper.
  id = 1;
  # The lock path used when automatically assigning an id
  zookeeper_lock_path = "/locks/sserver_sia";
```

至于全局的重复提交检查，ETH 从 geth/parity 获取任务时如果使用标准的 RPC 调用，无法改变区块中除去 nonce 之外的部分。而大部分矿机使用的协议又不支持指定特别的 nonce 前缀，所以所有的矿机连接获取的任务都是相同的，存在不同连接提交相同 share 的可能，所以必须再做全局的重复提交检查。对于 BTC 来讲，每个连接的 extra nonce 1 都不相同，这就使得不同连接的任务不相同，所以我们只需要做每个连接的局部重复提交检查就可以了。

**Comment by bmhjyu** [comment]
另外针对 ETH，我们也自行 fork 了 geth/parity 的 RPC API 从而允许修改区块头中的 extra data 字段。如果使用我们 fork 过的节点（https://github.com/btccom/go-ethereum/tree/v1.8.23-btcpool 还有 https://github.com/btccom/parity-ethereum/tree/v2.4.5-btcpool），那么每一个矿机连接的任务就都是不相同的了。这部分功能我们也是最近才开发的，随后我们将会增加使用说明。

**Comment by rocqina** [comment]
好，研究一下eth这部分，感谢
