### ISSUE TITLE
blkmaker kafka 消息阻塞

### ISSUE THREAD

**Issue by zhangliang7190** [btccom/btcpool#293]
您好；
在部署矿池的过程中，blkmaker因为Kafka消息的问题而挂起，blk消费最近的n条后，出现未知的活动异常，就挂起了。重启blkmaker之后，依然会消费同样的n条消息然后挂起。请问有什么方法解决吗？产生该问题的原因是啥？

**Comment by YihaoPeng** [comment]
你可以把blkmaker的日志贴一下吗？有敏感信息的部分删掉。

**Comment by zhangliang7190** [comment]
> 你可以把blkmaker的日志贴一下吗？有敏感信息的部分删掉。


# block maker cfg
#
# @since 2016-07
# @copyright btc.com
#
kafka = {
  brokers = "***"; # "10.0.0.1:9092,10.0.0.2:9092,..."
};

curl = {
  ssl_verify_peer = true; // set false to skip ssl verification on node RPC
};

blockmaker = {
  type = "ETH";
};
#
# pool mysql db: table.found_blocks
#
pooldb = {
 ****
};
blk_makers = (
  {
    chain_type = "ETH"; //blockchain short name
    enabled = true; //enable worker
    nodes = (
      {
        rpc_addr    = "***";
        rpc_userpwd = "*****";  # username:password
      }
    );
    # kafka topics
    rawgbt_topic = "EthRawGbt";
    solved_share_topic = "EthSolvedShare";
    high_diff_topic = "EthHighDiff";
    auxpow_solved_share_topic = "EthAuxPowSolvedShare";
    rsk_solved_share_topic = "EthRskSolvedShare";
    job_topic = "EthJob";
   
    constantinople_height = 7280000; #7280000
  }
);

~                                                                                                                                                                                              
~

**Comment by YihaoPeng** [comment]
不是配置文件，是日志，也就是 log_blkmaker/*INFO

**Comment by YihaoPeng** [comment]
该问题有进展吗？

**Comment by zhangliang7190** [comment]
> 该问题有进展吗？
麻烦关闭该问题吧，这是代码中的配置造成的，blk读kafka数据会读取最近的n条数据。实际上Kafka并没有堵塞，是因为blk没有其他的log，看起来好像有问题一样。
