### ISSUE TITLE
关于Jobmaker中设置支付的问题

### ISSUE THREAD

**Issue by npk** [btccom/btcpool#295]
您好，在jobmaker.cfg 中关于payout有如下的设置

# payout address
    # the private key of my2dxGb5jz43ktwGxg2doUaEb9WhZ9PQ7K is cQAiutBRMq4wwC9JHeANQLttogZ2EXw9AgnGXMq5S3SAMmbX2oLd
    payout_address = "my2dxGb5jz43ktwGxg2doUaEb9WhZ9PQ7K";
    # coinbase info with location ID (https://github.com/btccom/btcpool/issues/36)
    coinbase_info = "region1/Project BTCPool/";

这个支付地址是多长时间支付呢，是有了收益就自动支付还是需要手工完成？ 谢谢

**Comment by bmhjyu** [comment]
这个地址是打包区块时的 coinbase 交易中 output 的地址，也就是接收爆块奖励的地址，只要矿池爆块那么就会马上获取爆块的所有奖励。它和矿池用户的收益支付没有关系，用户的收益发放功能是需要单独开发的。

**Comment by npk** [comment]
好的，清楚了。也就是说矿池只要爆块就会把奖励支付到这个指定的钱包地址上了。谢谢🙏
