### ISSUE TITLE
关于bpool_local_stats_db中earn字段

### ISSUE THREAD

**Issue by npk** [btccom/btcpool#296]
您好，

请问在bpool_local_stats_db表中earn这个字段应该是统计worker或者user的收益吧，这个是如何计算出来的呢？单位是什么呢？  挖矿收益中包含直接挖矿爆块另外还有网络转账打包费，这个是合并计算了还是分开计算？

谢谢

**Comment by bmhjyu** [comment]
Duplicate of #297

**Comment by bmhjyu** [comment]
这部分的内容已经在 #297 中解答，故先将其关闭。
