### ISSUE TITLE
earn记录的数值问题

### ISSUE THREAD

**Issue by npk** [btccom/btcpool#297]
目前数据库中用户earn已经有了上万的数值，但是在jobmaker.cfg中指定的payout的钱包地址的余额还是为零，也没有任何转账记录，请问数据库中satas_pool_hour的earn应该就是矿池收益吧？

这个收益是不是等于payout中会接收到的数值呢？

谢谢

**Comment by langubtc** [comment]
payout是你矿池的爆块接收地址，earn是用户挖矿收益奖励（PPS）

**Comment by lionincd** [comment]
请问earn是否只是收益的奖励？和比特币之间换算关系是什么？这个奖励会发放到哪里（如果payout钱包只收到爆块的话）？

多谢！

**Comment by lionincd** [comment]
> payout是你矿池的爆块接收地址，earn是用户挖矿收益奖励（PPS）

请问earn是否只是收益的奖励？和比特币之间换算关系是什么？这个奖励会发放到哪里（如果payout钱包只收到爆块的话）？

多谢！

**Comment by bmhjyu** [comment]
这里的 earn 字段是指按照 PPS 矿工应该获得的收益，它的单位就是聪。目前开源的后端并不包含如何发放这部分收益的代码，这部分通常矿池开发者都需要进行各种自定义。并且开发者应该将矿池的 slparser/statshttpd 组件视作参考实现，如何处理 sharelog 是完全可以自主开发的，比如实现不同于 PPS 的矿工收益方案。

**Comment by lionincd** [comment]
> 这里的 earn 字段是指按照 PPS 矿工**应该**获得的收益，它的单位就是聪。目前开源的后端并不包含如何发放这部分收益的代码，这部分通常矿池开发者都需要进行各种自定义。并且开发者应该将矿池的 slparser/statshttpd 组件视作参考实现，如何处理 sharelog 是完全可以自主开发的，比如实现不同于 PPS 的矿工收益方案。
我理解矿池会有两部分收益： block reward and transaction fees，如果理解正确，earn不是记录transaction fees，请问 transaction fees会体现在哪里？

**Comment by YihaoPeng** [comment]
> 目前数据库中用户earn已经有了上万的数值，但是在jobmaker.cfg中指定的payout的钱包地址的余额还是为零。

这是很正常的，说明你的矿池还没有爆块。BTCPool是一个PPS（pay per share）矿池，其原理如下：
1. 区块链存在一个爆块难度`A`，矿池下发给矿机的任务难度为`B`，`B`远小于`A`。
2. 当矿机挖到的share达到难度`B`，它就会提交给矿池。此时，矿池就给用户记录一笔值为 `B / A * R` 的收益，`R`为爆块奖励。
3. 如果矿机提交的share的难度在达到`B`的同时也达到了`A`，则矿池产生一个爆块，`jobmaker.cfg`中指定的`payout`的钱包地址的余额增加`R+F`，其中`F`为该区块中打包的交易的手续费之和。

所以，我们有如下结论：
1. 即使数据库中记录了大量的用户收益，矿池自己也不一定会获得收益。因为矿池获得收益的必要条件是爆块，比用户获得收益困难`A/B`倍。
2. 理论上来说，当用户提交`A/B`个share之后，矿池爆块的概率为`1`。但即便如此矿池也不一定会真的爆块，因为频率不会与概率严格相符。
3. 如果矿池和用户都没有作弊，并且所有软件（包括挖矿软件、矿池软件）都没有问题，则从长期来看数据库中记录的用户收益和矿池钱包收到的金额`R`（即爆块奖励，不包括手续费`F`）应该相差不大。如果相差很大，则考虑以下原因：
   a. 矿池爆块太少了，频率与概率不接近。还需要增加统计时间才能使频率接近于概率。
   b. 用户作弊（藏块攻击）或挖矿软件有问题导致爆块share未能提交。
   c. 矿池软件存在问题导致爆块未成功。
   d. 区块链节点存在问题导致爆块未被区块链接受（区块成为孤块）。

**Comment by YihaoPeng** [comment]
没有新进展，暂时关闭
