### ISSUE TITLE
stats_workers_hour时间统计错误

### ISSUE THREAD

**Issue by lionincd** [btccom/btcpool#298]
在测试过程中，发现矿工按时间统计的时间数据不对，如创建时间是“'2019-05-24 09:00:27'”，而矿工挖矿的时间统计反而在“'2019052401'”，请参见附图，相差有8小时左右，系统时间设置CST+8，MySQL和系统设置一致。

<img width="480" alt="stats_workers_hour" src="https://user-images.githubusercontent.com/14542204/58299322-755bb900-7e11-11e9-8d45-4200c5f2458d.png">

多谢！

**Comment by rocqina** [comment]
标准时间和北京时间差距8小时

**Comment by lionincd** [comment]
> 间和北京时间差距

请问需要如何调整？
