### ISSUE TITLE
initUserCoin模块配置问题

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#299]
我在使用 initUserCoin 模块自动注册用户的时候，遇到如下问题：
```
I0525 03:23:15.416793   28128 UserAutoReg.go:46] reg user: test11163, info: {"SessionID":16777228,"Worker":"test11163.com.xx"}
I0525 03:23:15.418107   28128 UserAutoReg.go:85] reg user success. user: test11163, puid: 1, coin: grin, status: success, message: success


I0525 03:23:18.572489   28128 InitUserCoin.go:42] HTTP GET http://127.0.0.1/userlist-autoreg.php?last_id=0
I0525 03:23:18.573345   28128 InitUserCoin.go:79] HTTP GET Success. User Num: 0
I0525 03:23:18.573353   28128 InitUserCoin.go:105] Finish: grin; User Num: 0; http://127.0.0.1/userlist-autoreg.php
W0525 03:23:25.419093   28128 UserAutoReg.go:95] set coin for new user failed: record exists, skip
```
我目前用的sserver，没有用stratumSwitcher，但是需要使用initUserCoin模块，请问对应的配置：
```
"ZKSwitcherWatchDir": "/stratumSwitcher/btcbcc/",
```
应该使用什么路径呢？目前
```
"ZKAutoRegWatchDir": "/sserver/autoreg/“
```
是OK的。
谢谢~

**Comment by YihaoPeng** [comment]
ZKSwitcherWatchDir 对应 sserver.cfg 中的 zookeeper_userchain_map
ZKAutoRegWatchDir 对应 sserver.cfg 中的 zookeeper_auto_reg_watch_dir

两边配置成一样就可以。
此外，`set coin for new user failed: record exists, skip`并不是错误，只是说明这个记录已经存在，不需要再次写入了。

**Comment by xwen01** [comment]
> ZKSwitcherWatchDir 对应 sserver.cfg 中的 zookeeper_userchain_map
> ZKAutoRegWatchDir 对应 sserver.cfg 中的 zookeeper_auto_reg_watch_dir
> 
> 两边配置成一样就可以。
> 此外，`set coin for new user failed: record exists, skip`并不是错误，只是说明这个记录已经存在，不需要再次写入了。

谢谢回复！顺便问一下，你们fork的grin（https://github.com/btccom/grin.git）现在好像不能同步了，是不是因为版本的问题呢？我看到我目前的版本是1.0.1

**Comment by YihaoPeng** [comment]
试试1.0.2？
https://github.com/btccom/grin/commits/v1.0.2-btcpool

**Comment by xwen01** [comment]
> 试试1.0.2？
> https://github.com/btccom/grin/commits/v1.0.2-btcpool

1.0.2可以同步了。谢谢！
