### ISSUE TITLE
nmcmaker能否像gbt，blk启动多个吗？能否指定不同的全节点地址服务？

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#300]
大神好。
架构上图上gbt，blk，ss可以启动多个，nmc服务可以这样干吗？如果可以jobmaker能启动多个吗？

**Comment by bmhjyu** [comment]
这个当然是可以的，nmcmaker/jobmaker 也是可以启动多个以达到冗余的目的。

**Comment by bxlkm** [comment]
多谢。
