### ISSUE TITLE
gbtmaker里面没有抢空块的逻辑

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#301]
jobmaker里面有处理空块的逻辑，从浏览器看btc矿池的表现是会抢空块。这部分是没有开放吗？

**Comment by bmhjyu** [comment]
这部分是通过 poolwatcher 来实现的，poolwatcher 自身是一个 stratum 客户端，用它连接其它 stratum server 的话块高发生改变是它就会发送一个空块任务到 Kafka 中。

**Comment by rocqina** [comment]
明白了，感谢

**Comment by rocqina** [comment]
没有发现eth里面有watchpool的逻辑，是不是当前的代码并不支持eth挖空块。工作原理感觉和btc是一样的

**Comment by rocqina** [comment]
只看到btc有watchpool的逻辑，像eth都没有watchpool的逻辑，这部分的逻辑是另有处理还是代码目前就没有处理抢空块的逻辑

**Comment by bmhjyu** [comment]
目前 ETH 这些并没有实现这个功能，这是由币种本身节点 RPC 的限制造成的。BTC 节点的 `submitblock` 调用时不要求节点内部存在一个对应任务的数据结构和状态，完全可以从外部构建一个空块任务并且在此基础上爆块。可是 ETH 节点爆块提交的前提是这个任务必须是由 `eth_getWork` 调用获取的，这个调用在节点内部产生了对应的数据结构和状态。想要实现和 BTC 类似的空块任务，则必须修改 ETH 节点的代码。

**Comment by rocqina** [comment]
好的，我还以为是因为eth出块太快考虑的
