### ISSUE TITLE
sserver的rejected share非常高

### ISSUE THREAD

**Issue by npk** [btccom/btcpool#303]
您好，
Btcpool只使用BTC币种，在测试时发现sserver的日志中以及矿机的统计信息中发现非常高的rejected share，检查其他服务进程和网络连接都没有异常，请问如何能降低rejected share或者排查这个问题呢？

谢谢

I0604 00:22:42.042822  4857 StratumMinerBitcoin.cc:344] rejected share: Low difficulty, worker: user.worker, versionMask: 00000000, share(jobId: 6698340561365756930, ip: x.x.x.x, userId: 1, workerId: -2996843103218010965, time: 1559578962/2019-06-03 16:22:42, height: 579079, blkBits: 1725bb76/7459680720542.295898, shareDiff: 8192, nonce: a5bb3e38, sessionId: 01000002, versionMask: 00000000, status: 23/Low difficulty)
I0604 00:22:42.269958  4857 StratumMinerBitcoin.cc:344] rejected share: Low difficulty, worker: user.worker, versionMask: 00000000, share(jobId: 6698340561365756930, ip: x.x.x.x, userId: 1, workerId: -2996843103218010965, time: 1559578962/2019-06-03 16:22:42, height: 579079, blkBits: 1725bb76/7459680720542.295898, shareDiff: 8192, nonce: a1d01e0f, sessionId: 01000002, versionMask: 00000000, status: 23/Low difficulty)
I0604 00:22:46.843602  4857 StratumMinerBitcoin.cc:344] rejected share: Low difficulty, worker: user.worker, versionMask: 00000000, share(jobId: 6698340561365756930, ip: x.x.x.x, userId: 1, workerId: -2996843103218010965, time: 1559578966/2019-06-03 16:22:46, height: 579079, blkBits: 1725bb76/7459680720542.295898, shareDiff: 8192, nonce: a17a6f2b, sessionId: 01000002, versionMask: 00000000, status: 23/Low difficulty)
I0604 00:22:48.941660  4857 StratumMinerBitcoin.cc:344] rejected share: Low difficulty, worker: user.worker, versionMask: 00000000, share(jobId: 6698340561365756930, ip: x.x.x.x, userId: 1, workerId: -2996843103218010965, time: 1559578968/2019-06-03 16:22:48, height: 579079, blkBits: 1725bb76/7459680720542.295898, shareDiff: 8192, nonce: a92c7730, sessionId: 01000002, versionMask: 00000000, status: 23/Low difficulty)
I0604 00:22:50.449733  4857 StratumMinerBitcoin.cc:344] rejected share: Low difficulty, worker: user.worker, versionMask: 00000000, share(jobId: 6698340561365756930, ip: x.x.x.x, userId: 1, workerId: -2996843103218010965, time: 1559578970/2019-06-03 16:22:50, height: 579079, blkBits: 1725bb76/7459680720542.295898, shareDiff: 8192, nonce: a224181a, sessionId: 01000002, versionMask: 00000000, status: 23/Low difficulty)

**Comment by npk** [comment]
数据库中的记录：

`mysql> select * from stats_workers_hour;
+------+----------------------+------------+--------------+--------------+-------------+-----------------------------+------+---------------------+---------------------+
| puid | worker_id            | hour       | share_accept | share_reject | reject_rate | score                       | earn | created_at          | updated_at          |
+------+----------------------+------------+--------------+--------------+-------------+-----------------------------+------+---------------------+---------------------+
|    1 | -2996843103218010965 | 2019060315 |      1589248 |      5013504 |    0.759305 | 0.0000002130450430168630000 |  266 | 2019-06-03 23:12:40 | 2019-06-03 23:59:47 |
|    1 | -2996843103218010965 | 2019060316 |      1286144 |      3661824 |    0.740066 | 0.0000001724127409981840000 |  216 | 2019-06-04 00:00:19 | 2019-06-04 00:32:24 |
|    7 |  8113131267054106046 | 2019060307 |         4992 |            0 |           0 | 0.0000000006691975416927880 |    1 | 2019-06-03 15:01:54 | 2019-06-03 16:30:29 |
+------+----------------------+------------+--------------+--------------+-------------+-----------------------------+------+---------------------+---------------------+
3 rows in set (0.00 sec)

mysql> select * from stats_users_hour;
+------+------------+--------------+--------------+-------------+-----------------------------+------+---------------------+---------------------+
| puid | hour       | share_accept | share_reject | reject_rate | score                       | earn | created_at          | updated_at          |
+------+------------+--------------+--------------+-------------+-----------------------------+------+---------------------+---------------------+
|    1 | 2019060315 |      1589248 |      5013504 |    0.759305 | 0.0000002130450430168630000 |  266 | 2019-06-03 23:12:40 | 2019-06-03 23:59:47 |
|    1 | 2019060316 |      1294336 |      3792896 |    0.745572 | 0.0000001735109113230130000 |  217 | 2019-06-04 00:00:19 | 2019-06-04 00:33:13 |
|    7 | 2019060307 |         4992 |            0 |           0 | 0.0000000006691975416927880 |    1 | 2019-06-03 15:01:54 | 2019-06-03 16:30:29 |
+------+------------+--------------+--------------+-------------+-----------------------------+------+---------------------+---------------------+
3 rows in set (0.00 sec)`

**Comment by npk** [comment]
用tcpdump抓包如下：

![image](https://user-images.githubusercontent.com/1757999/58820808-2bbb6b80-8666-11e9-8271-5230cab78ef0.png)

**Comment by YihaoPeng** [comment]
sserver的设置应该保持
```
enable_dev_mode = false;
```

如果这个选项是true，就会下发`dev_fixed_difficulty`难度的任务给矿机。这个任务难度如果比默认挖矿难度低，又没有打开`enable_simulator`，就会报告`Low Difficulty`。

**Comment by npk** [comment]
谢谢，您的回复。
我检查了sservr.cfg里面关于dev的配置：
########################## dev options #########################

  # if enable simulator, all share will be accepted. for testing
  enable_simulator = false;

  # if enable it, all share will make block and submit. for testing
  enable_submit_invalid_block = false;

  # if enable, difficulty sent to miners is always dev_fixed_difficulty. for development
  enable_dev_mode = false;

  # difficulty to send to miners. for development
  dev_fixed_difficulty = 0.005;

  ###################### end of dev options ######################

确定在配置里面都是关闭的

**Comment by SwimmingTiger** [comment]
我建议你构建一个Debug版sserver
cmake -DCMAKE_BUILD_TYPE=Debug ..
然后看打印的矿机提交hash与任务要求target的区别。
如果矿机提交的hash没有任何前导0，说明矿机与sserver存在兼容性问题（比如不支持8字节ExtraNonce2）。

此外，请运行unitest并保证以下测试用例通过：
https://github.com/btccom/btcpool/blob/ca156c0f20c7502dd8efea94edfa73794d65c996/test/TestStratumServer.cc#L189

如果未通过，说明构建的有问题。需要说明的是，本程序从未在32位系统中验证过，目前只支持64位Linux。

**Comment by npk** [comment]
好的，谢谢
