### ISSUE TITLE
返回share结果result字段是null

### ISSUE THREAD

**Issue by fuhaijin** [btccom/btcpool#305]
StratumSession::rpc1ResponseError
当share不被接受，返回结果中result字段使用了null，为何不直接用false?

**Comment by YihaoPeng** [comment]
这是 SlushPool 的原始 Bitcoin Stratum 协议中的约定：
https://slushpool.com/help/manual/stratum-protocol
```
Exception Handling
Stratum defines simple exception handling. Example of rejected share looks like:
{"id": 10, "result": null, "error": (21, "Job not found", null)}
```
