### ISSUE TITLE
是否能够支持下vcash联合挖矿？

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#306]

**Comment by sslazio2009** [comment]
应该能够支持，原来的nmc和其他的联合币公用一个标准的可以多个辅助链hash一个一起44字节，vcash的magicnum不一样，用法也不一样，也是44字节，能放得下去。https://github.com/vcashorg/vcash/blob/vcash/doc/pool_merge_mining.md#post-mining-block 这个上面的步骤发回去的比nmc要简单。
目前币信和币印都支持了vcash联合挖矿

**Comment by YihaoPeng** [comment]
我们已经有一个vcash实现了，我们最近准备提交到master。

**Comment by bxlkm** [comment]
@YihaoPeng RSK的联挖mergedMiningProxy配置应该怎么配，根据官网的https://github.com/rsksmart/rskj/wiki/JSON-RPC-API 配置了API出现json对象错误，是不是也得支持下里面的字段啊。

**Comment by YihaoPeng** [comment]
@bxlkm RSK联合挖矿不使用mergedMiningProxy，使用的是`gwmaker`(`chain_type=RSK`)。jobmaker需要配置`rsk_rawgw_topic`。nmcauxmaker和gwmaker可以同时运行。

目前已向master分支添加VCASH联合挖矿，它也使用`gwmaker`(`chain_type=VCASH`)。jobmaker需要配置`VcashRawGw`。

**Comment by YihaoPeng** [comment]
已经添加了配置VCash联合挖矿的文档。
https://github.com/btccom/btcpool/blob/master/docs/MergedMining.md

**Comment by bxlkm** [comment]
@YihaoPeng 多谢，已知晓。
