### ISSUE TITLE
upgrade failed

### ISSUE THREAD

**Issue by yurisyb** [btccom/btcpool#308]
make -j$(nproc)

root@testpool:/work/btcpool/build# make -j$(nproc)
[  3%] Built target sph
[  6%] Built target blake2
[  7%] Built target equihash
[  9%] Built target cuckoo
[ 12%] Built target ethash
[ 15%] Built target beam
Scanning dependencies of target btcpool
[ 16%] Building CXX object CMakeFiles/btcpool.dir/src/GwMaker.cc.o
[ 17%] Building CXX object CMakeFiles/btcpool.dir/src/DiffController.cc.o
[ 18%] Building CXX object CMakeFiles/btcpool.dir/src/BlockMaker.cc.o
[ 18%] Building CXX object CMakeFiles/btcpool.dir/src/JobMaker.cc.o
[ 19%] Building CXX object CMakeFiles/btcpool.dir/src/Kafka.cc.o
[ 19%] Building CXX object CMakeFiles/btcpool.dir/src/MySQLConnection.cc.o
[ 19%] Building CXX object CMakeFiles/btcpool.dir/src/Stratum.cc.o
[ 20%] Building CXX object CMakeFiles/btcpool.dir/src/StratumClient.cc.o
In file included from /work/btcpool/src/Stratum.cc:32:0:
/work/zcash-2.0.4/src/hash.h:16:10: fatal error: sodium.h: No such file or directory
 #include "sodium.h"
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/btcpool.dir/build.make:327: recipe for target 'CMakeFiles/btcpool.dir/src/Stratum.cc.o' failed
make[2]: *** [CMakeFiles/btcpool.dir/src/Stratum.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1506: recipe for target 'CMakeFiles/btcpool.dir/all' failed
make[1]: *** [CMakeFiles/btcpool.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

I have tried make -j1 also got error

root@testpool:/work/btcpool/build# make -j1
[  1%] Built target sph
[  2%] Built target equihash
[  4%] Built target cuckoo
[  7%] Built target beam
[  7%] Building CXX object CMakeFiles/btcpool.dir/src/Stratum.cc.o
In file included from /work/btcpool/src/Stratum.cc:32:0:
/work/zcash-2.0.4/src/hash.h:16:10: fatal error: sodium.h: No such file or directory
 #include "sodium.h"
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/btcpool.dir/build.make:327: recipe for target 'CMakeFiles/btcpool.dir/src/Stratum.cc.o' failed
make[2]: *** [CMakeFiles/btcpool.dir/src/Stratum.cc.o] Error 1
CMakeFiles/Makefile2:1506: recipe for target 'CMakeFiles/btcpool.dir/all' failed
make[1]: *** [CMakeFiles/btcpool.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by YihaoPeng** [comment]
Try install libsodium-dev
```
apt install libsodium-dev
```

**Comment by YihaoPeng** [comment]
Document updated
https://github.com/btccom/btcpool/commit/89d7eb4106f6f7fab28b2e3e514eae9198db8202

**Comment by yurisyb** [comment]
Thanks fixed the issue
