### ISSUE TITLE
请教关于ela联合挖矿的问题

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#310]
看介绍上面支持ElastOS，但是代码里面只看到nmc和rsk的代码，是否是我看漏了？或者是需要参照这两个币种加一下代码？抑或是就改改配置topic之类的就行了？请大牛指点一二。

**Comment by YihaoPeng** [comment]
如果单独联合挖矿ELA，使用nmcauxmaker对接ELA的RPC就可以。
如果要同时联合挖矿ELA和NMC，使用nmcauxmaker对接这个联合挖矿代理：
https://github.com/btccom/btcpool-go-modules/tree/master/mergedMiningProxy

**Comment by sslazio2009** [comment]
> 如果单独联合挖矿ELA，使用nmcauxmaker对接ELA的RPC就可以。
> 如果要同时联合挖矿ELA和NMC，使用nmcauxmaker对接这个联合挖矿代理：
> https://github.com/btccom/btcpool-go-modules/tree/master/mergedMiningProxy

你好，
我按照这个下面的联合挖编译报错，是不是这个资源移动了位置？

package golang.org/x/crypto/scrypt: unrecognized import path "golang.org/x/crypto/scrypt" (https fetch: Get https://golang.org/x/crypto/scrypt?go-get=1: dial tcp 216.239.37.1:443: connect: connection timed out)

**Comment by sslazio2009** [comment]
应该是我网的问题，在云服务器上面可以，只能自己下载然后建一个同名文件夹放。

**Comment by YihaoPeng** [comment]
golang.org被墙了，所以`go get`不能自动下载这个包。
我已经把这个包放在了我的vendor目录，以后`go get`的时候就不会再遇到这个问题了。

**Comment by sslazio2009** [comment]
> 如果单独联合挖矿ELA，使用nmcauxmaker对接ELA的RPC就可以。
> 如果要同时联合挖矿ELA和NMC，使用nmcauxmaker对接这个联合挖矿代理：
> https://github.com/btccom/btcpool-go-modules/tree/master/mergedMiningProxy

博主您好，我把nmc ela uno rsk vch五个能支持的联合币种都加进去试了一下，还是有些不清楚的想请教一下。
主要是一个原始交易地址的问题，aux的代理接入了nmc ela uno这三个接到mergedminingproxy代理，然后代理接nmcauxmaker，就看到mergedminingproxy中ela有一个createauxblock提交参数里面填写了payout地址，然后nmcauxmaker里面可以填写一个，请问剩下那个uno的地址填写在哪呢？然后使用gwmaker，配置里面填写了rsk和vch两个币种，也均未看到有payout的地址配置填写。
另外，sserver中有rsk的sovledshare和nmc的sovledshare，这两个的爆块是blkmaker向连接节点发？vch的直接就sserver向vch节点发？或者是rsk和nmc的也带了rpc的user名和password和vch一样都是sserver负责向rsk节点/mergedmining代理发爆块信息，blkmaker只负责主链btc的呢？ 那么nmc的爆块能在代理那入库，rsk和vch爆块了就没入库了？
还请博主不吝指点。

**Comment by YihaoPeng** [comment]
1. 如果你使用的uno节点不支持`createauxblock("address")`，则需要设置使用`getauxblock`，此时的挖矿收益会进入节点自带的钱包。
2. RSK的挖矿收益会进入节点配置文件中指定的钱包地址，VCash的情况应该类似。
3. 如果没有任何地方可以配置地址，则只能进入节点自带的钱包内。

**Comment by sslazio2009** [comment]
@YihaoPeng   Peng老师你好，请问gwvcashmaker里面parity_notify_host和port这个http服务是起什么作用呢？看文档介绍是eth的服务？

**Comment by YihaoPeng** [comment]
vcash节点可能也有“收到新区块时调用HTTP接口主动通知”的功能。只是由于该功能最先为以太坊设计，名称具有`parity_`前缀。该功能会打开一个HTTP服务器，访问`监听IP:监听端口/notify`会使gwmaker立即调用对应的RPC重新获取任务。
所以只要配置vcash节点在发现新区块时访问该HTTP服务器的`/notify`路径即可。
比如这是ETH Parity的新区块通知配置：
```
# URLs to which work package notifications are pushed.
notify_work = ["http://127.0.0.1:8000/notify"]
```
对应以下gwmaker配置：
```
parity_notify_host = "0.0.0.0";
parity_notify_port = 8000;
```

我不知道VCash节点如何配置通知，因为VCash挖矿是同事开发的。
