### ISSUE TITLE
RSK现在是混挖还是独立矿池配置？

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#312]
老大好，RSK我看了下从gwmaker获取任务，怎么和btc联合挖矿，如果支持的话请给出配置？
多谢！

**Comment by YihaoPeng** [comment]
与SHA256币种（比如BTC、BCH、UBTC）联合挖矿。
部署方法：
1. 运行gwmaker，写入某个`rawgw_topic`。
2. 在jobmaker.cfg中的`rsk_rawgw_topic `选项中指定相同的topic，即可生成带有RSK联合挖矿标记的任务。
3. 其他组件不需要配置。blkmaker会根据任务中的RSK RPC信息进行爆块提交。需要保证blkmaker可以访问RSK RPC。

**Comment by bxlkm** [comment]
@YihaoPeng 多谢 我试一下。
