### ISSUE TITLE
CGMiner can't connect to the pool

### ISSUE THREAD

**Issue by yurisyb** [btccom/btcpool#313]
Btcagent setup:

{
    "agent_listen_ip": "0.0.0.0",
    "agent_listen_port": 3333,
    "pools": [
        ["pool.hashpanel.com", 3333, "testpool"]
    ]
}

#btcagent.ERROR:
Log file created at: 2019/06/14 10:31:53
Running on machine: testpool
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0614 10:31:53.872603  7201 AgentMain.cc:121] setup failure

#btcagent.testpool.invalid-user.log.INFO.20190614-103154.19612
Log file created at: 2019/06/14 10:31:54
Running on machine: testpool
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0614 10:31:54.116921 19612 Server.cc:1205] add pool: pool.hashpanel.com:3333, subaccount name: testpool
I0614 10:31:54.131011 19612 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0614 10:31:54.131160 19612 Server.cc:1223] success connect[0]: pool.hashpanel.com:3333, subaccount name: testpool
I0614 10:31:54.131234 19612 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0614 10:31:54.131305 19612 Server.cc:1223] success connect[1]: pool.hashpanel.com:3333, subaccount name: testpool
I0614 10:31:54.131376 19612 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0614 10:31:54.131430 19612 Server.cc:1223] success connect[2]: pool.hashpanel.com:3333, subaccount name: testpool
I0614 10:31:54.131494 19612 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0614 10:31:54.131546 19612 Server.cc:1223] success connect[3]: pool.hashpanel.com:3333, subaccount name: testpool
I0614 10:31:54.131606 19612 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0614 10:31:54.131659 19612 Server.cc:1223] success connect[4]: pool.hashpanel.com:3333, subaccount name: testpool

#supervisorctl log
agent                            RUNNING   pid 19612, uptime 0:00:15

everything look okay but still the miner can't connect to the poool
i can connect with telnet pool.hashpanel.com 3333
miner setup:
pool.hashpanel.com 3333
workername: testpool
password:

**Comment by sslazio2009** [comment]
楼主你好，得看看后面的日志，前面的日志没问题，日志倒着往前面截看看

**Comment by YihaoPeng** [comment]
```
  # telnet pool.hashpanel.com 3333                                                                                                        !10074
Trying 192.228.161.55...
Connected to 5740053fe6f9.sn.mynetname.net.
Escape character is '^]'.
{"id":1,"method":"mining.subscribe","params":["bmminer/2.0.0"]}
{"id":1,"result":[[["mining.set_difficulty","01000046"],["mining.notify","01000046"]],"01000046",8],"error":null}
{"id":2,"method":"mining.authorize","params":["testpool",""]}
{"id":2,"result":null,"error":[29,"Invalid username",null]}
```

You need to change the `testpool` in your agent_conf.json to a valid username.

**Comment by yurisyb** [comment]
Hi,
From can I get the valid username?
if api i have set already to testpool 
{"err_no":0,"err_msg":null,"data":{"yuri":1,"testpool":2}}

**Comment by sslazio2009** [comment]
> ```
> telnet pool.hashpanel.com 3333
> Trying 192.228.161.55...
> Connected to 5740053fe6f9.sn.mynetname.net.
> Escape character is '^]'.
> {"id":1,"method":"mining.subscribe","params":["bmminer/2.0.0"]}
> {"id":1,"result":[[["mining.set_difficulty","01000046"],["mining.notify","01000046"]],"01000046",8],"error":null}
> {"id":2,"method":"mining.authorize","params":["testpool",""]}
> {"id":2,"result":null,"error":[29,"Invalid username",null]}
> ```
> 
> You need to change the `testpool` in your `agent_conf.json` to a valid username.
resolve host: pool.hashpanel.com, ip: 10.1.2.33  他这个解析出来是个内网

**Comment by yurisyb** [comment]
I don’t understand this. Can you please specify where to add the username
or from where check the valid username and use it in cgminer worker

**Comment by YihaoPeng** [comment]
Are you the admin of `pool.hashpanel.com`?
If you are, check the `list_id_api_url` option in your `sserver.cfg` to make sure the URL is accessible and contains the `testpool` username.

If the above check does not find a problem, there is still a problem: if `sserver` is running, you cannot add or modify the user name whose `puid` is less than or equal to the current maximum `puid`. If you want to make this change, you need to restart all `sserver`.

```
{"err_no":0,"err_msg":null,"data":{"aaa":1,"ccc":3}}
```
In this json, the `puid` of `ccc` is 3. So this edit will not works without restarting your `sserver`:
```
{"err_no":0,"err_msg":null,"data":{"aaa":1,"ddd":3,"bbb":2}}
```

**Comment by YihaoPeng** [comment]
> from where can I check the valid username and then use it in btcagent with cgminer worker

BTCAgent does not manage users. The users available in BTCAgent depend on the pool server to which it is connected, which is `pool.hashpanel.com` in your configuration. Only administrators of `pool.hashpanel.com` can add users.

**Comment by yurisyb** [comment]
To make very clear,
this is my sserver address 
  list_id_api_url = "https://pool.hashpanel.com/userlist.php";

this is the configuration inside the userlist file
<?php
header('Content-Type: application/json');
$last_id = (int) $_GET['last_id'];
$users = [
	'bitcoinrpc' => 1,
	'testpool' => 2,
];
$requestedUsers = [];
foreach ($users as $name=>$id) {
    if ($id > $last_id) {
        $requestedUsers [$name] = $id;
    }
}
echo json_encode(
    [
        'err_no' => 0,
        'err_msg' => null,
        'data' => (object) $requestedUsers,
    ]
);
?>

the sserver error:

Log file created at: 2019/06/20 12:01:42
Running on machine: pool
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0620 12:01:42.496778 23254 StratumServerMain.cc:132] LTC sserver version 2.3.2-291-g2cb2649
I0620 12:01:42.498603 23254 StratumServerMain.cc:70] createServer type: LTC
I0620 12:01:42.498834 23254 StratumServer.cc:449] [Option] stale shares will be accepted.
I0620 12:01:42.499028 23254 Kafka.cc:368] producer librdkafka version: 0.9.1
I0620 12:01:42.499145 23254 Kafka.cc:368] producer librdkafka version: 0.9.1
I0620 12:01:42.499210 23254 Kafka.cc:368] producer librdkafka version: 0.9.1
I0620 12:01:42.499275 23254 Kafka.cc:81] consumer librdkafka version: 0.9.1
I0620 12:01:42.499431 23254 UserInfo.cc:45] UserInfo: user name will be case insensitive
E0620 12:01:42.503393 23262 Utils.cc:260] unable to request data from: https://pool.hashpanel.com/userlist.php?last_id=0, error: Out of memory
E0620 12:01:42.503640 23262 UserInfo.cc:401] http get request user list fail, url: https://pool.hashpanel.com/userlist.php?last_id=0
I0620 12:01:42.506451 23254 StratumServer.cc:135] set max job lifetime to 300s
I0620 12:01:42.506530 23254 StratumServer.cc:140] set mining notify interval to 30s
I0620 12:01:42.506968 23254 Kafka.cc:163] add brokers: 10.1.2.33:9092
I0620 12:01:42.507191 23254 Kafka.cc:170] create topic handle: LtcJob
I0620 12:01:42.538774 23254 Kafka.cc:442] add brokers: 10.1.2.33:9092
I0620 12:01:42.538832 23268 StratumServer.cc:193] start job repository consume thread
I0620 12:01:42.538834 23254 Kafka.cc:449] create topic handle: ShareLog
I0620 12:01:42.570375 23254 Kafka.cc:442] add brokers: 10.1.2.33:9092
I0620 12:01:42.570521 23254 Kafka.cc:449] create topic handle: SolvedShare
I0620 12:01:42.601372 23254 Kafka.cc:442] add brokers: 10.1.2.33:9092
I0620 12:01:42.601444 23254 Kafka.cc:449] create topic handle: CommonEvents
I0620 12:01:42.633116 23254 Kafka.cc:368] producer librdkafka version: 0.9.1
I0620 12:01:42.633162 23254 Kafka.cc:368] producer librdkafka version: 0.9.1
I0620 12:01:42.633318 23254 Kafka.cc:442] add brokers: 10.1.2.33:9092
I0620 12:01:42.633378 23254 Kafka.cc:449] create topic handle: AuxPowSolvedShare
I0620 12:01:42.665027 23254 Kafka.cc:442] add brokers: 10.1.2.33:9092
I0620 12:01:42.665300 23254 Kafka.cc:449] create topic handle: RskSolvedShare
I0620 12:01:42.695801 23254 StratumServer.cc:789] stratum server running
E0620 12:01:43.004186 23262 Utils.cc:260] unable to request data from: https://pool.hashpanel.com/userlist.php?last_id=0, error: Out of memory
E0620 12:01:43.004233 23262 UserInfo.cc:401] http get request user list fail, url: https://pool.hashpanel.com/userlist.php?last_id=0
E0620 12:01:43.505417 23262 Utils.cc:260] unable to request data from: https://pool.hashpanel.com/userlist.php?last_id=0, error: Out of memory
E0620 12:01:43.505658 23262 UserInfo.cc:401] http get request user list fail, url: https://pool.hashpanel.com/userlist.php?last_id=0
E0620 12:01:44.006188 23262 Utils.cc:260] unable to request data from: https://pool.hashpanel.com/userlist.php?last_id=0, error: Out of memory
E0620 12:01:44.006232 23262 UserInfo.cc:401] http get request user list fail, url: https://pool.hashpanel.com/userlist.php?last_id=0
I0620 12:01:44.248642 23254 StratumSession.cc:76] client connect, ip: 10.1.2.33
I0620 12:01:44.248695 23254 StratumSession.cc:76] client connect, ip: 10.1.2.33
I0620 12:01:44.248839 23254 StratumSession.cc:76] client connect, ip: 10.1.2.33
I0620 12:01:44.248945 23254 StratumSession.cc:76] client connect, ip: 10.1.2.33
I0620 12:01:44.249069 23254 StratumSession.cc:76] client connect, ip: 10.1.2.33
I0620 12:01:44.249135 23254 StratumSession.cc:178] recv(72): {"id":1,"method":"mining.subscribe","params":["btccom-agent/1.0.0-su"]}
I0620 12:01:44.249197 23254 StratumSession.cc:502] send(114) to  : {"id":1,"result":[[["mining.set_difficulty","01000000"],["mining.notify","01000000"]],"01000000",8],"error":null}
I0620 12:01:44.249256 23254 StratumSession.cc:178] recv(72): {"id":1,"method":"mining.subscribe","params":["btccom-agent/1.0.0-su"]}
I0620 12:01:44.249290 23254 StratumSession.cc:502] send(114) to  : {"id":1,"result":[[["mining.set_difficulty","01000004"],["mining.notify","01000004"]],"01000004",8],"error":null}
I0620 12:01:44.249419 23254 StratumSession.cc:178] recv(72): {"id":1,"method":"mining.subscribe","params":["btccom-agent/1.0.0-su"]}
I0620 12:01:44.249457 23254 StratumSession.cc:502] send(114) to  : {"id":1,"result":[[["mining.set_difficulty","01000001"],["mining.notify","01000001"]],"01000001",8],"error":null}
I0620 12:01:44.249480 23254 StratumSession.cc:178] recv(72): {"id":1,"method":"mining.subscribe","params":["btccom-agent/1.0.0-su"]}
I0620 12:01:44.249511 23254 StratumSession.cc:502] send(114) to  : {"id":1,"result":[[["mining.set_difficulty","01000002"],["mining.notify","01000002"]],"01000002",8],"error":null}
I0620 12:01:44.249531 23254 StratumSession.cc:178] recv(72): {"id":1,"method":"mining.subscribe","params":["btccom-agent/1.0.0-su"]}
I0620 12:01:44.249608 23254 StratumSession.cc:502] send(114) to  : {"id":1,"result":[[["mining.set_difficulty","01000003"],["mining.notify","01000003"]],"01000003",8],"error":null}
I0620 12:01:44.249635 23254 StratumSession.cc:178] recv(64): {"id":1,"method":"mining.authorize","params":["bitcoinrpc",""]}
I0620 12:01:44.249672 23254 StratumSession.cc:345] cannot find user id
I0620 12:01:44.249686 23254 StratumSession.cc:315] cannot switch user chain
W0620 12:01:44.249694 23254 StratumSessionBitcoin.cc:463] authorize failed, workerName:bitcoinrpc.__default__, password: , versionMask: 00000000, clientAgent: btccom-agent/1.0.0-su, clientIp: 10.1.2.33
I0620 12:01:44.249724 23254 StratumSession.cc:502] send(60) to bitcoinrpc.__default__ : {"id":1,"result":null,"error":[29,"Invalid username",null]}
I0620 12:01:44.249826 23254 StratumSession.cc:178] recv(64): {"id":1,"method":"mining.authorize","params":["bitcoinrpc",""]}
I0620 12:01:44.249856 23254 StratumSession.cc:345] cannot find user id
I0620 12:01:44.249867 23254 StratumSession.cc:315] cannot switch user chain
W0620 12:01:44.249876 23254 StratumSessionBitcoin.cc:463] authorize failed, workerName:bitcoinrpc.__default__, password: , versionMask: 00000000, clientAgent: btccom-agent/1.0.0-su, clientIp: 10.1.2.33
I0620 12:01:44.249900 23254 StratumSession.cc:502] send(60) to bitcoinrpc.__default__ : {"id":1,"result":null,"error":[29,"Invalid username",null]}
I0620 12:01:44.249946 23254 StratumSession.cc:178] recv(64): {"id":1,"method":"mining.authorize","params":["bitcoinrpc",""]}
I0620 12:01:44.249974 23254 StratumSession.cc:345] cannot find user id

and for tha last question,

Yes i am the administrator and can add and remove users.

Btcagent config file:
{
    "agent_listen_ip": "0.0.0.0",
    "agent_listen_port": 3333,
    "pools": [
        ["pool.hashpanel.com", 3333, "bitcoinrpc"]
    ]
}

Check the above information and see what is wrong here still i am not able to connect the miner
I have tried with password without password and any passable way no effiction

**Comment by YihaoPeng** [comment]
So, it seems that all the problems are in libcurl's `out of memory`. It makes sserver unable to get a list of users, so it messes up everything. Please refer to my solution described at https://github.com/btccom/btcpool/issues/311.
