### ISSUE TITLE
sserver难度设置

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#316]
我把sserver.cfg里的难度设置改为如下：
```
  #default difficulty (most of the GPU can do 2 to 8 but most of mining software does not check difficulty)
  default_difficulty = "4";

  #max difficulty (most of the GPU can do 2 to 8 but most of mining software does not check difficulty)
  max_difficulty = "4";

  #min difficulty (some GPU (GTX 1070) cannot have stable submission)
  min_difficulty = "4";
```
但是发现同样的GPU机器，在难度1和4的时候提交的share数是一样多的，好像这里设置的难度4并没有生效，请问这个stratum server难度应该怎么设置更高的值呢？谢谢！

**Comment by bmhjyu** [comment]
请问你的配置是 grin 吗？还有使用的挖矿软件及其版本是什么？这个附带的示例 `max_difficulty` 的设定表示最大难度固定为4，实际上可以任意扩大这个值。

**Comment by xwen01** [comment]
> 请问你的配置是 grin 吗？还有使用的挖矿软件及其版本是什么？这个附带的示例 `max_difficulty` 的设定表示最大难度固定为4，实际上可以任意扩大这个值。

是grin，后来我在矿机端抓包发现矿池发出的难度的确是4，是不是按照我上面贴的配置方式，难度就是固定4了？谢谢。

**Comment by bmhjyu** [comment]
> 是grin，后来我在矿机端抓包发现矿池发出的难度的确是4，是不是按照我上面贴的配置方式，难度就是固定4了？谢谢。

对的，可以将 `max_difficulty` 设置为一个非常大的十六进制值，这样矿池将可以自动向上调整难度。同时如果有很多算力较低的用户（比如单卡 1060  这种），可以将 `min_difficulty` 设置为1，矿池在自动调整难度之后能够减少他们的算力波动。

**Comment by xwen01** [comment]
> > 是grin，后来我在矿机端抓包发现矿池发出的难度的确是4，是不是按照我上面贴的配置方式，难度就是固定4了？谢谢。
> 
> 对的，可以将 `max_difficulty` 设置为一个非常大的十六进制值，这样矿池将可以自动向上调整难度。同时如果有很多算力较低的用户（比如单卡 1060 这种），可以将 `min_difficulty` 设置为1，矿池在自动调整难度之后能够减少他们的算力波动。

谢谢回复，你的意思现在是支持动态难度的对吧？如果我要支持类似nicehash这样的，某个算力非常大，需要高难度的，矿池也能自动调整吗？
如果不行的话，能否单独开一个端口，设置一个很高的难度呢？这个应该怎么操作呢？
谢谢~

**Comment by YihaoPeng** [comment]
运行两个sserver监听在不同端口。
普通用户：
```
  default_difficulty = "4";
  max_difficulty = "40000000";
  min_difficulty = "1";
```
NiceHash用户：
```
  default_difficulty = "200";
  max_difficulty = "40000000";
  min_difficulty = "200";
```

max_difficulty是象征性的最大值，通常不会达到。
NiceHash在 https://www.nicehash.com/pool-operators 要求Grin的难度>=512，所以是0x200。
```
GrinCuckaroo29 | >= 512
GrinCuckatoo31 | >= 512
```

**Comment by xwen01** [comment]
> 运行两个sserver监听在不同端口。
> 普通用户：
> 
> ```
>   default_difficulty = "4";
>   max_difficulty = "40000000";
>   min_difficulty = "1";
> ```
> 
> NiceHash用户：
> 
> ```
>   default_difficulty = "200";
>   max_difficulty = "40000000";
>   min_difficulty = "200";
> ```
> 
> max_difficulty是象征性的最大值，通常不会达到。这个值只要不超过 2^62 就好（超过的话，会出现用户可以利用的漏洞）。
> NiceHash在 https://www.nicehash.com/pool-operators 要求Grin的难度>=512，所以是0x200。
> 
> ```
> GrinCuckaroo29 | >= 512
> GrinCuckatoo31 | >= 512
> ```

谢谢！顺便问一下，btcpool支持多个币同时挖的吧？有什么需要注意的问题吗？

**Comment by YihaoPeng** [comment]
长时间没有回复
