### ISSUE TITLE
grin怎么配置？

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#318]
@YihaoPeng 我这边已经把grin的全节点和钱包节点都已部署完毕，矿池这边怎么对接啊，我看配置就那么几项，gbt，gw，job都没有相关配置，请大佬指点改怎使用。另外grin的grin-mine需要启动吗？

**Comment by sslazio2009** [comment]
这个直接用poolwatcher从grin节点拿题，不需要gbt gw job这些， grin节点要用改版的

**Comment by bxlkm** [comment]
@sslazio2009 grin节点要用改版的? 这个是什么意思，不太明白，哪里能够下载改版的grin。

**Comment by sslazio2009** [comment]
> @sslazio2009 grin节点要用改版的? 这个是什么意思，不太明白，哪里能够下载改版的grin。

https://github.com/btccom/grin   用这个

**Comment by YihaoPeng** [comment]
建议使用v1.0.2-btcpool分支的grin。https://github.com/btccom/grin/tree/v1.0.2-btcpool

**Comment by YihaoPeng** [comment]
没有新进展，暂时关闭
