### ISSUE TITLE
矿池重新部署，重启sserver以后算力恢复太慢？

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#322]
更新矿池最新版本，观察了一段时间用户太多的话，连接有的成功，有的失败，算力恢复也很慢，之前失败的用户也成功了，大概30分钟左右用户才能连接完，算力才慢慢恢复回来。这个问题早期版本没有发现时间太长，大概也就在10分钟内就恢复了。请问这个问题怎么解决？

**Comment by YihaoPeng** [comment]
https://github.com/btccom/btcpool/commit/e973484baaa8bb1266784074614a7e13aba83a4a
这个提交也许可以修复重启后矿机连接慢。

此外，https://github.com/btccom/btcpool/commit/b5a2ed3def4e917ef4a6510fa7aae4d406d46f3b 这个提交让sserver具有新特性，可以在被 `kill -SIGTERM` 时先不退出，而是先关闭监听端口，然后在1小时内缓慢关闭现有连接并退出。这样可以减少算力波动。

配合之前已经应用的“允许多个sserver复用监听端口”，现在可以这样升级：
1. 启动新的sserver监听到相同端口。
2. 通过`kill -SIGTERM pid`向旧sserver发送`SIGTERM`信号使其开始平滑退出。

此外，对于在这些提交之前构建的sserver，用`kill -9`强制结束也许可以让TCP协议栈发送RST，这样矿机就会尽快断开连接并重连。

**Comment by YihaoPeng** [comment]
此外，以前版本的sserver在退出时会崩溃，所以TCP协议栈应该会向矿机发送RST，此时恰好没有问题。不过我们后来修复了这个问题，所以变成发送FIN了。FIN将使连接进入半关闭状态，需要矿机的挖矿程序主动做出响应才能使连接彻底关闭。

https://github.com/btccom/btcpool/commit/e973484baaa8bb1266784074614a7e13aba83a4a 使sserver再次发送RST，应该可以避免FIN带来的连接关闭延迟。

**Comment by bxlkm** [comment]
@YihaoPeng 多谢老大，还有个很重要的问题，以后升级的话，怎么才能让sserver热重启啊，要不然总是会断开一段时间，上面的方法可以做到吗？ 我先把你fix的版本测试一下。

**Comment by YihaoPeng** [comment]
注意问题不是新进程导致的，而是旧进程导致的（发送FIN导致矿机需要一段时间才能得知连接已断开）。所以直接更新到新版本不能解决问题，你需要对旧版本使用`kill
-9`（也就是`kill -SIGKILL`）使其强制结束（这样才会发送RST而不是FIN）。
在此更新部署之后，就可以使用`kill
-SIGTERM`使旧版本平滑退出了。不过这个也并不是真的平滑，只是把断开连接分散到一小时之内了，可以减少用户看到的拒绝率。不过，更新后发送RST是可以加快矿机重连回来的速度。

bxlkm <notifications@github.com> 于 2019年6月21日周五 14:02写道：

**Comment by onigirisan** [comment]
思路上觉得之前stratum switcher代理的方式挺好的，但是stratum switcher废弃了，期待这个issue的后续更新

**Comment by YihaoPeng** [comment]
我们实现了端口复用和平滑退出，可以做到类似热更新的效果。

https://github.com/btccom/btcpool/issues/417
