### ISSUE TITLE
求助！！请问一下各位能够和BTC联合挖矿币种有哪些。

### ISSUE THREAD

**Issue by azure-sea** [btccom/btcpool#324]
请教一下各位, 我现在联合挖矿实现了BTC与域名币和ELA进行联合挖矿。根据博主的连接发现还有一个UNO币，请问还有没有其他币种能够支持的。
https://github.com/btccom/btcpool/blob/master/docs/MergedMining.md

**Comment by YihaoPeng** [comment]
之前在哪里看到过一个可以和比特币联合挖矿的币种列表，现在找不到了。

**Comment by YihaoPeng** [comment]
长时间没有回复
