### ISSUE TITLE
请问对云算力用户是如何处理的

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#325]
现在用云算力的用户越来越多，他们又不想难度有波动，云算力用户我们怎么处理

**Comment by YihaoPeng** [comment]
他们可以设置一个较高的“最低难度”，然后填写在密码里面，比如对于[NiceHash](https://www.nicehash.com/pool-operators)的SHA256难度要求：
```
md=1000000
```
NiceHash的DaggerHashimoto（以太坊）：
```
md=8589934592
```
> 我们的以太坊难度数值是NiceHash难度数值的2<sup>32</sup>倍，所以NiceHash要求难度为2时，我们的难度应该设为2*2<sup>32</sup>=8589934592

对于没有密码字段的BEAM币种，我们通过给云算力用户开一个单独的端口来实现，这个端口设置了满足NiceHash要求的高难度。

不过，我们现在有一个新计划，就是在同一sserver内自动检测云算力客户端（比如NiceHash），然后自动为其设置较高难度。代码会在最近提交。

--------------------------------

此外，目前避免难度变化的唯一方法就是把难度设置的高一点，使单个连接内的平均share时间长于sserver的预期时间。如果平均share时间短于预期（share提交过快），难度就会上升。

对特定用户支持固定难度（在share提交过快时不进行难度调整）是可能的，不过我们需要全面考察，考虑用户是否可以利用这种机制对矿池进行攻击，获取到额外的收益。

**Comment by rocqina** [comment]
md=1000000,设置了这个最小难度没问题。但是如果难度往上升，云算力用户是不是处理起来也有问题，云算力用户总是强调需要一个稳定的难度。不是很明白，云算力为什么就不能接受难度波动？

**Comment by SwimmingTiger** [comment]
我目前还没有遇到这样的用户。我们的NiceHash用户没有向我们抱怨难度上升的问题。
你应该问一下他们的云算力平台是不是有技术缺陷。目前NiceHash没有这种问题。

**Comment by SwimmingTiger** [comment]
目前，要实现固定难度只有一个方法，把最小、默认和最大难度设置为相同。

**Comment by rocqina** [comment]
是的，是这样做的。可能云算力还需要好好研究一下

> 目前，要实现固定难度只有一个方法，把最小、默认和最大难度设置为相同。
