### ISSUE TITLE
新提交的难度值版本，对于无效的share也计入难度统计的疑惑

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#334]
现在的难度统计更贴近矿机的真实算力，对矿池是好事。如果一个用户，网络不稳定，拒绝率高。以前的逻辑是只有accept的share才计入难度统计，现在是所有share都统计，所以这个用户如果网络不好，反而难度上升了，对网络不好的用户是不是不太友好。

**Comment by bmhjyu** [comment]
其实真实的情况应该是这样：在网络不太好的情况下，由于部分提交变成了 stale share 以前的逻辑会使难度降低，而新逻辑并不会使网络不好的用户难度上升，只是难度不会下降。

**Comment by rocqina** [comment]
对，我的意思也是难度不变了，相对于以前逻辑的下降的等于难度上升了。对于网络不好的矿工，实际上收益也没什么变化？但是对矿池收获的是高难度的提交，而以前是更多的低难度的提交，对矿池是有利的

**Comment by bmhjyu** [comment]
任务难度并不会影响矿工和矿池收益，虽然提交的难度上升了，但是提交的数量会变少。有影响的矿机的算力看起来波动会大一些，但是长期平均值仍然是和矿机理论算力相符的。

**Comment by rocqina** [comment]
好的，感谢
