### ISSUE TITLE
Error while running Docker

### ISSUE THREAD

**Issue by h2o10** [btccom/btcpool#337]
Hello,

I got the following errors. Please  let me  know how to solve the errors.

https://paste.ubuntu.com/p/BWv4CBDJsn/

**Comment by YihaoPeng** [comment]
`sserver` need a API server to download its user list. You can run this API server:
https://github.com/btccom/btcpool/tree/master/install/api-sample#how-to-quickly-create-a-web-server-based-on-the-script
