### ISSUE TITLE
搭建beam 矿池，cmake ....-DPOOL__WORK_WITH_STRATUM_SWITCHER=ON  miner 直连可以出块

### ISSUE THREAD

**Issue by EWIT521** [btccom/btcpool#338]
beam-miner 直连  矿池（-DPOOL__WORK_WITH_STRATUM_SWITCHER=ON） 可以正常在测试块网出块，请问，新版矿池已经不维护 DPOOL__WORK_WITH_STRATUM_SWITCHER=ON 相关的处理了？？？ 拿beam  为列，矿池带DPOOL__WORK_WITH_STRATUM_SWITCHER=ON  进行编译，矿工可以直连连接，不需要switcher 了，beam 可以通过switcher 连接矿池吗？

**Comment by bmhjyu** [comment]
这个功能是我们较旧版本的币种切换支持

- 目前我们已经放弃维护使用 switcher 的切换，最新的 master 代码无须使用它就可以支持一键切换，并且切换是完全不中断矿机连接，说明可以参照 https://github.com/btccom/btcpool/blob/master/docs/INSTALL-BTCPool.md#mining-coin-switcher
- 我们并没有可以和 Beam 切换的币种，目前支持切换的的币种只有 BTC/BCH/UBTC 以及 ETH/ETC 这两种组合。
- 目前 `-DPOOL__WORK_WITH_STRATUM_SWITCHER=ON` 也许可以正常工作，但是建议升级到最新代码并且使用无 switcher 的部署方式。

**Comment by YihaoPeng** [comment]
不要在BEAM中使用`-DPOOL__WORK_WITH_STRATUM_SWITCHER=ON`。使用`-DPOOL__WORK_WITH_STRATUM_SWITCHER=ON`会导致所有用户的`nonce prefix`都分配为`000000`，相当于所有用户都在同一个挖掘空间内挖矿，这会带来显著的算力损失。

**Comment by rocqina** [comment]
不检查nonce prefix，是不是就可以用了switcher了

**Comment by rocqina** [comment]
@YihaoPeng ，所有用户在同一个挖掘空间内挖矿，显著的算力损失，这句怎么理解？
