### ISSUE TITLE
部署最新版本eth etc问题？

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#339]
I0711 10:58:12.152782  2181 Kafka.cc:372] producer librdkafka version: 0.9.1
I0711 10:58:12.152796  2181 Kafka.cc:372] producer librdkafka version: 0.9.1
I0711 10:58:12.152839  2181 Kafka.cc:372] producer librdkafka version: 0.9.1
I0711 10:58:12.152987  2181 Kafka.cc:81] consumer librdkafka version: 0.9.1
W0711 10:58:12.153115  2181 StratumServerEth.cc:105] cannot read DAG cache file ./sserver-eth0-dagcache.dat
I0711 10:58:12.153396  2181 UserInfo.cc:45] UserInfo: user name will be case insensitive
I0711 10:58:12.153620  2181 StratumServer.cc:135] set max job lifetime to 300s
I0711 10:58:12.153919  2181 StratumServer.cc:140] set mining notify interval to 30s
I0711 10:58:12.154317  2181 Kafka.cc:167] add brokers: XXXX
I0711 10:58:12.154853  2181 Kafka.cc:174] create topic handle: EtcJob

**Comment by SwimmingTiger** [comment]
`cannot read DAG cache file ./sserver-eth0-dagcache.dat`不是错误（所以它的日志等级是warning）。只有sserver收到任务后，在推出时才会产生DAG缓存文件。这样第二次打开就不会有这样的提示了。

**Comment by bxlkm** [comment]
多谢老大，明白了。
