### ISSUE TITLE
打开supervisorctl进程状态错误FATAL，求问怎么解决

### ISSUE THREAD

**Issue by IloveFY** [btccom/btcpool#34]
错误如下，不知道是哪里没有配置好
![image](https://user-images.githubusercontent.com/20611887/29902370-5f0a693a-8e30-11e7-9528-89038311ff2f.png)

**Comment by dyzz** [comment]
请提供对应模块的日志便于分析

**Comment by IloveFY** [comment]
blkmaker
![image](https://user-images.githubusercontent.com/20611887/29904032-7effd1d6-8e39-11e7-8cdb-eb90acbcf319.png)
gbtmaker
![image](https://user-images.githubusercontent.com/20611887/29904076-aa789a64-8e39-11e7-801a-94777f4215c2.png)
poolwatcher
![image](https://user-images.githubusercontent.com/20611887/29904132-eac08802-8e39-11e7-9610-2f53a137f7ef.png)
slparser的日志是空的
好多报错都差不多。我是新手，不懂.....

**Comment by YihaoPeng** [comment]
看上去是连不上kafka集群。

**Comment by IloveFY** [comment]
![image](https://user-images.githubusercontent.com/20611887/29904406-44e2e3ec-8e3b-11e7-8502-6fa117027b85.png)
看来是的了.

**Comment by IloveFY** [comment]
您好，方便留个联系方式么，如果您有空闲时间，向您请教一下问题

**Comment by IloveFY** [comment]
qq或微信：328298557
