### ISSUE TITLE
YihaoPeng可以请你付费搭建个池么？

### ISSUE THREAD

**Issue by luchen7** [btccom/btcpool#340]
YihaoPeng可以请你付费搭建个池么？  如果可以 请加我微信957628

**Comment by luchen7** [comment]
如果是YihaoPeng  请加我微信的时候告诉我你的 ID  其他人我就不加了

**Comment by YihaoPeng** [comment]
目前我没有时间提供这样的服务，不过你可以考虑联系BTC.com的运营比如微信`muhuan19900922`来看看其他人是否可以帮你提供类似服务。
