### ISSUE TITLE
grin hard fork

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#341]
请问grin 7/17硬分叉之后，你们的grin fork版本还可以用吗？目前看到最新是2.0.0版本：

https://github.com/btccom/grin/tree/v2.0.0-btcpool

谢谢！

**Comment by bmhjyu** [comment]
该版本就是对应 2.0.0 的 fork，对应后端代码很快就会更新到开源仓库中。

**Comment by xwen01** [comment]
> 该版本就是对应 2.0.0 的 fork，对应后端代码很快就会更新到开源仓库中。

好的，只是想确认一下，那就是说只要git pull一下就可以了对吧？

**Comment by bmhjyu** [comment]
> > 该版本就是对应 2.0.0 的 fork，对应后端代码很快就会更新到开源仓库中。
> 
> 好的，只是想确认一下，那就是说只要git pull一下就可以了对吧？

是的，对应的 Cuckarood29 算法验证部分已经 push 到了 master 分支 https://github.com/btccom/btcpool/commit/7a4eea336f5965e57fdfaed4a5d6975f1a97ad14

**Comment by xwen01** [comment]
> > > 该版本就是对应 2.0.0 的 fork，对应后端代码很快就会更新到开源仓库中。
> > 
> > 
> > 好的，只是想确认一下，那就是说只要git pull一下就可以了对吧？
> 
> 是的，对应的 Cuckarood29 算法验证部分已经 push 到了 master 分支 [7a4eea3](https://github.com/btccom/btcpool/commit/7a4eea336f5965e57fdfaed4a5d6975f1a97ad14)

我在编译2.0.0版本的时候，出现这个错误：
```
Compiling grin_keychain v2.0.0 (/work/grin/keychain)
   Compiling croaring-sys v0.3.9
error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
  --> keychain/src/types.rs:17:5
   |
17 | use std::convert::TryFrom;
   |     ^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
   --> keychain/src/types.rs:511:2
    |
511 |     type Error = ();
    |     ^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
   --> keychain/src/types.rs:513:2
    |
513 |       fn try_from(value: u8) -> Result<Self, Self::Error> {
    |  _____^
514 | |         match value {
515 | |             0 => Ok(SwitchCommitmentType::None),
516 | |             1 => Ok(SwitchCommitmentType::Regular),
517 | |             _ => Err(()),
518 | |         }
519 | |     }
    | |_____^

error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
   --> keychain/src/types.rs:510:6
    |
510 | impl TryFrom<u8> for SwitchCommitmentType {
    |      ^^^^^^^^^^^

error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
   --> keychain/src/types.rs:513:41
    |
513 |     fn try_from(value: u8) -> Result<Self, Self::Error> {
    |                                            ^^^^^^^^^^^

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `grin_keychain`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
运行rustc --explain E0658结果如下：

An unstable feature was used.

Erroneous code example:

```
#[repr(u128)] // error: use of unstable library feature 'repr128'
enum Foo {
    Bar(u64),
}
```

If you're using a stable or a beta version of rustc, you won't be able to use
any unstable features. In order to do so, please switch to a nightly version of
rustc (by using rustup).

If you're using a nightly version of rustc, just add the corresponding feature
to be able to use it:

```
#![feature(repr128)]

#[repr(u128)] // ok!
enum Foo {
    Bar(u64),
}
```
请问这个怎么解决呢？谢谢

**Comment by bmhjyu** [comment]
@xwen01 你的编译问题升级 rustc 到 1.34 以后的版本应该可以解决，最简单的办法就是运行 `rustup update` 之后重新编译。

**Comment by xwen01** [comment]
> @xwen01 你的编译问题升级 rustc 到 1.34 以后的版本应该可以解决，最简单的办法就是运行 `rustup update` 之后重新编译。

升级1.36之后问题解决了。谢谢！
