### ISSUE TITLE
启动gbtmaker 错误

### ISSUE THREAD

**Issue by kolvin2016** [btccom/btcpool#342]
你好，编译成功后按照文档启动gbtmaker报错
F0712 17:31:15.338626 28592 GbtMakerMain.cc:140] gbtmaker init failure
*** Check failure stack trace: ***
    @     0x7f94ef11103d  google::LogMessage::Fail()
    @     0x7f94ef112ea3  google::LogMessage::SendToLog()
    @     0x7f94ef110bcb  google::LogMessage::Flush()
    @     0x7f94ef11388e  google::LogMessageFatal::~LogMessageFatal()
    @           0x407fe9  main
    @     0x7f94ed732830  __libc_start_main
    @           0x407649  _start
Aborted (core dumped)

**Comment by SwimmingTiger** [comment]
你可以阅读日志文件夹中的日志来确定问题。

**Comment by EthanHee** [comment]
也遇到了这种问题，楼主解决了吗？

**Comment by YihaoPeng** [comment]
通常都是缺少配置项。
我们已经修改了异常捕捉方式，现在堆栈跟踪不会只有LogMessage了，并且缺少的配置项名称也可以打印出来。
