### ISSUE TITLE
请教一下大牛poolwatcher（proxy）和sserver里面的这个proxy这两个服务的配置问题

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#343]

**Comment by sslazio2009** [comment]
这个poolwatcher（proxy）.cfg的配置和原来相比变动很大，请教一下这是实现的什么功能呢？sserver.cfg里面怎么配置呢？

**Comment by SwimmingTiger** [comment]
poolwatcher(proxy).cfg用于完全代理上游矿池的任务，把自己的矿池作为上游矿池的一个客户端。
sserver需要配置为使用4字节extra nonce 2，并且最高难度应该低于任务可能出现的最低难度（在`poolwatcher(proxy).cfg`的密码中填写`md=xxx`来控制上游矿池的最低难度）。

**Comment by sslazio2009** [comment]
> `poolwatcher(proxy).cfg`用于完全代理上游矿池的任务，把自己的矿池作为上游矿池的一个客户端。目前只能与`extra nonce 2`空间>=`8`的矿池相连。
> `sserver`需要配置为使用4字节`extra nonce 2`，并且最高难度应该低于任务可能出现的最低难度（在`poolwatcher(proxy).cfg`的密码中填写`md=xxx`来控制上游矿池的最低难度）。

按照我理解那是把自己矿池整合成一台超级大算力矿机与上游矿池打交道？答案还是由自己矿池校验满足了我们再看是不是满足上游矿池的要求？

**Comment by YihaoPeng** [comment]
是。对上游矿池的提交在自己矿池相当于爆块。所以任务难度不能高于爆块难度，不然算力浪费了。

**Comment by rocqina** [comment]
proxy的作用是没有blkmaker和gbtmaker的矿池，通过监控一另个矿池，完全从被监控矿池拿任务，并且提交爆块请求到被监控矿池，这么做的目的是什么，快速部署多个矿池到不同的区域吗？

**Comment by YihaoPeng** [comment]
充当代理，并且在代理内部具有算力统计功能。
并且这种部署也可以和正常矿池部署交替使用（比如，本来自己挖，某天不想自己挖了，于是代理到其他矿池。或者反过来，本来代理，某天独立了）。

**Comment by sslazio2009** [comment]
感谢

**Comment by sslazio2009** [comment]
> 充当代理，并且在代理内部具有算力统计功能。
> 并且这种部署也可以和正常矿池部署交替使用，只需要把poolwatcher(proxy)替换为gbt/job/blkmaker等即可（比如，本来自己挖，某天不想自己挖了，于是代理到其他矿池。或者反过来，本来代理，某天独立了）。

还想请教一个问题，这种方案理论上还是会存在幸运值的问题，转接出去上游矿池和自己矿给出的算力不一致，为什么当初不考虑实现成把上游难度下发给所有矿机根据上游返回结果来判断算力？这样算力就和上游完全吻合了。

**Comment by rocqina** [comment]
@SwimmingTiger @YihaoPeng 有个问题，没找到sserver的配置extranonce2的长度的地方？为什么要配置4字节的extranonce2

**Comment by sslazio2009** [comment]
> @SwimmingTiger @YihaoPeng 有个问题，没找到sserver的配置extranonce2的长度的地方？为什么要配置4字节的extranonce2

上游矿池的8个字节的ext2的高4位做sessionid用了，所以只能用4个字节

**Comment by rocqina** [comment]
这个如果上游矿池统计up的算力的话，会比下游矿池所有矿工的算力，损失太多了啊

**Comment by rocqina** [comment]
@SwimmingTiger 这个poolwatcher有bug，大量的core

**Comment by rocqina** [comment]
> > @SwimmingTiger @YihaoPeng 有个问题，没找到sserver的配置extranonce2的长度的地方？为什么要配置4字节的extranonce2
> 
> 上游矿池的8个字节的ext2的高4位做sessionid用了，所以只能用4个字节
还有就是下游sserver给矿工开放的extranonce2为4，是否够用，如果下游矿池的矿工用什么代理软件之类的？

**Comment by sslazio2009** [comment]
@rocqina   蚂蚁s9一秒钟能遍历nonce空间2的32次方3-4次，10秒钟一个nonce的话1个字节都足够了，extranonce2为4很充足了。下游矿工用代理得看代理的实现，需要拆分extranonce2且要求8位的那明显不行了，把4拆分实现代理或者不依赖sessionid自组的就行。

**Comment by rocqina** [comment]
蚂蚁s9矿机14t/s，大概2的44次方，怎么一秒遍历2的32次方的只有3-4次的？

**Comment by sslazio2009** [comment]
@rocqina   没事，给两个字节也够用了
