### ISSUE TITLE
收不到grin stratum job

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#344]
在升级到最新的btcpool和grin 2.0.0之后，发现poolwatcher收不到stratum job，下面是grin-server，grin-wallet和poolwatcher的日志：

grin-server.log:
```
20190721 17:11:13.228 INFO grin_api::handlers - Starting HTTP API server at 127.0.0.1:13413.
20190721 17:11:13.228 INFO grin_servers::grin::server - Starting dandelion monitor: 127.0.0.1:13413
20190721 17:11:13.228 WARN grin_servers::grin::server - Grin server started.
20190721 17:11:13.231 INFO grin_servers::common::types - DandelionEpoch: next_epoch: is_stem: true (90%), relay: None
20190721 17:11:13.234 INFO grin_servers::mining::stratumserver - (Server ID: 0) Starting stratum server with edge_bits = 31, proof_size = 42
20190721 17:11:13.234 WARN grin_servers::mining::stratumserver - Stratum server started on 0.0.0.0:13416
20190721 17:11:13.234 INFO grin_servers::mining::stratumserver - Start tokio stratum server
20190721 17:11:34.105 INFO grin_servers::common::adapters - Received 3 block headers from 46.4.91.48:3414
20190721 17:11:34.492 INFO grin_servers::common::adapters - Received 3 block headers from 35.181.35.93:3414
20190721 17:11:34.554 INFO grin_servers::grin::sync::syncer - synchronized at 781805673760515 @ 267783 [0000036b18a3]
```

grin-wallet.log:
```
20190721 16:44:48.713 INFO grin_wallet - This is Grin Wallet version 2.0.0 (git v2.0.0), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190721 16:44:54.558 INFO grin_wallet_impls - Using LMDB Backend for wallet
20190721 16:44:54.558 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 127.0.0.0:13415.
20190721 16:44:54.558 WARN grin_wallet_controller::controller - HTTP Foreign listener started.
20190721 16:53:01.819 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190721 16:53:01.819 INFO grin_wallet - Using wallet configuration file at /root/.grin/main/grin-wallet.toml
20190721 16:53:01.819 INFO grin_wallet - This is Grin Wallet version 2.0.0 (git v2.0.0), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190721 16:53:04.840 INFO grin_wallet_impls - Using LMDB Backend for wallet
20190721 16:53:04.840 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 0.0.0.0:13415.
20190721 16:53:04.840 WARN grin_wallet_controller::controller - HTTP Foreign listener started.
```

poolwatcher.INFO:
```
I0721 17:29:02.282450 23018 PoolWatcherMain.cc:130] BTC poolwatcher version 2019.06.25-17-beam-nonceprefix-check-9-gb19cc15
I0721 17:29:02.282851 23018 PoolWatcherMain.cc:68] PoolWatcher Type: GRIN
I0721 17:29:02.282899 23018 Kafka.cc:372] producer librdkafka version: 0.9.1
I0721 17:29:02.282994 23018 Kafka.cc:81] consumer librdkafka version: 0.9.1
I0721 17:29:02.283129 23018 Watcher.cc:214] Connection request to localhost:13415
I0721 17:29:02.283520 23018 Kafka.cc:451] add brokers: 127.0.0.1:9092
I0721 17:29:02.283586 23018 Kafka.cc:458] create topic handle: GrinJob
I0721 17:29:02.314301 23018 Kafka.cc:167] add brokers: 127.0.0.1:9092
I0721 17:29:02.314376 23018 Kafka.cc:174] create topic handle: GrinSolvedShare
I0721 17:29:02.345108 23025 WatcherGrin.cc:74] waiting for stratum jobs...
I0721 17:31:02.380743 23018 Watcher.cc:279] upsession read/write timeout, events: 65
I0721 17:31:02.380964 23018 Watcher.cc:214] Connection request to localhost:13415
I0721 17:31:02.381057 23018 Watcher.cc:134] reconnect server1
```

请问是我哪里没有配置正确吗？telnet 127.0.0.1 13415是可以连的

**Comment by bmhjyu** [comment]
从日志中可以看出 Grin 节点的 stratum server 监听端口是 13416，13415 是钱包的 API 端口。

```
20190721 17:11:13.234 WARN grin_servers::mining::stratumserver - Stratum server started on 0.0.0.0:13416
```

**Comment by xwen01** [comment]
> 从日志中可以看出 Grin 节点的 stratum server 监听端口是 13416，13415 是钱包的 API 端口。
> 
> ```
> 20190721 17:11:13.234 WARN grin_servers::mining::stratumserver - Stratum server started on 0.0.0.0:13416
> ```
谢谢回复！连13416端口可以了。
顺便问一下，之前测试的时候有一段时间poolwatcher收不到stratum job，但是miner连到sserver（8899端口）还是看到share accept，这种情况如何能够避免呢？

**Comment by bmhjyu** [comment]
这种情况是我们本身的设计，清理 sserver 旧任务时会保留至少一个任务，这样即使上游某些组件故障，用户仍然能够继续提交一段时间直到耗尽 nonce 空间或者有爆块发生。这样用户的算力不至于立刻出现大波动，产生不利影响（有些矿机提交一直被拒绝会停止工作，一个矿场的大量矿机在短时间内停止工作会对矿场供电造成冲击）。同时如果故障很快就修复，用户就没有感知，也不需要进行收益赔付之类的工作（这种情况下用户收益没有损失，损失的只是矿池的爆块收益）。

**Comment by xwen01** [comment]
> 这种情况是我们本身的设计，清理 sserver 旧任务时会保留至少一个任务，这样即使上游某些组件故障，用户仍然能够继续提交一段时间直到耗尽 nonce 空间或者有爆块发生。这样用户的算力不至于立刻出现大波动，产生不利影响（有些矿机提交一直被拒绝会停止工作，一个矿场的大量矿机在短时间内停止工作会对矿场供电造成冲击）。同时如果故障很快就修复，用户就没有感知，也不需要进行收益赔付之类的工作（这种情况下用户收益没有损失，损失的只是矿池的爆块收益）。

谢谢回复。你的意思是如果poolwatcher由于某种原因没有收到新的任务，sserver在一定时间之后就会自动不再发任务也不接收提交是吗？这个时间大概是多久呢？
我看到的现象是在poolwatcher收不到任务之后很长一段时间，miner都一直可以提交，并且显示share accepted，看到有半小时以上吧。

**Comment by bmhjyu** [comment]
> 谢谢回复。你的意思是如果poolwatcher由于某种原因没有收到新的任务，sserver在一定时间之后就会自动不再发任务也不接收提交是吗？这个时间大概是多久呢？
> 我看到的现象是在poolwatcher收不到任务之后很长一段时间，miner都一直可以提交，并且显示share accepted，看到有半小时以上吧。

不是这样，矿池的设计是 sserver 在这种情况下会一直重复发送最后一个任务，直到下列情况发生。

- 提交达到了最后这个任务的难度也就是爆块了，这时该任务就清除了，之后的提交会被判定为超时而之前的提交则会被接受。这个时间长度可以用 `<network difficulty> * 42 / <hashrate on sserver>` 来估算，半小时以上是很有可能的。
- 矿机耗尽了该任务的 nonce 空间，那么新的提交就会被判定为重复提交。对于 Grin 来说有 2^64 那么多，这在目前的硬件条件下很难发生。

**Comment by xwen01** [comment]
> > 谢谢回复。你的意思是如果poolwatcher由于某种原因没有收到新的任务，sserver在一定时间之后就会自动不再发任务也不接收提交是吗？这个时间大概是多久呢？
> > 我看到的现象是在poolwatcher收不到任务之后很长一段时间，miner都一直可以提交，并且显示share accepted，看到有半小时以上吧。
> 
> 不是这样，矿池的设计是 sserver 在这种情况下会一直重复发送最后一个任务，直到下列情况发生。
> 
> * 提交达到了最后这个任务的难度也就是爆块了，这时该任务就清除了，之后的提交会被判定为超时而之前的提交则会被接受。这个时间长度可以用 `<network difficulty> * 42 / <hashrate on sserver>` 来估算，半小时以上是很有可能的。
> * 矿机耗尽了该任务的 nonce 空间，那么新的提交就会被判定为重复提交。对于 Grin 来说有 2^64 那么多，这在目前的硬件条件下很难发生。

了解了，谢谢！
有个关于grin node的问题请教一下，我发现grin node时不时会不sync，在“Peers and Sync”窗口，会看到类似这样：
```
Longest Chain: 801944... D @ 275227 H vs Us: 801935... D @ 275224 H
```
会落后几个高度，过一会又会sync上，但是池子爆块就会有问题，爆块有可能会出现在旧的高度。请问这个有什么办法解决吗？另外，池子可以同时从几个不同的地方接收job吗？判断高度最高的接收，通过配置poolwatcher？
谢谢！

**Comment by SwimmingTiger** [comment]
目前只有BTC jobproxy模式的poolwatcher有“配置多个上游，只转发最高高度的任务“这个功能，我们可以考虑改进Grin和Beam的poolwatcher来实现类似的逻辑。

**Comment by xwen01** [comment]
谢谢回复！
