### ISSUE TITLE
请教isNiceHashAgent是什么用户

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#345]
云算力用户的处理吗

**Comment by sslazio2009** [comment]
nicehash是一个买卖云算力的网站

**Comment by rocqina** [comment]
咱俩说的不是一个应该，比特小鹿上面的云算力应该都是nicehash算法的。新的矿池代码更新有对nicehashagent的处理，我感觉像是专门处理云算力用户的

**Comment by bmhjyu** [comment]
NiceHash 使用的 stratum 协议有一些特别的地方，这个是通过 agent 来判断是否是 NiceHash 协议。

**Comment by rocqina** [comment]
这个nicehash协议通过agent能判断出来吗。dcr里面分nicehash和normal的两种，我记得并不能通过agent分出来

**Comment by bmhjyu** [comment]
> 这个nicehash协议通过agent能判断出来吗。dcr里面分nicehash和normal的两种，我记得并不能通过agent分出来

DCR 是特殊情况，因为这时的 agent 根本就区别不了，不同矿机就用了两种不一样的区块头拼接方式，并且他们都没有用 NiceHash 的 agent 。

**Comment by YihaoPeng** [comment]
sserver中实施了以下和NiceHash矿工有关的策略：
1. 根据User-Agent进行检测，如果发现是NiceHash，则给予更长的不活跃超时时间。
2. 对于BTC/BCH/LTC，给NiceHash矿工发送伪唯一`job id`。sserver发送的`job id`是循环的（目前是0到255），NiceHash矿工收到后可能引发问题，所以在前面添加时间戳来让id看起来唯一。收到id后会取模来还原短id。

对于DCR，存在两种不同且无法实现协议协商的挖矿方案（我们目前称为gominer和normal），所以在sserver配置文件中添加了选项来指定方案。NiceHash只能使用其中一种方案。

**Comment by rocqina** [comment]
明白了
