### ISSUE TITLE
我们目前还在使用StratumSwitcher，目前发现LTC拒绝率过高问题？

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#346]
大佬好：
       我在往期的问题里面搜索相近的问题发现最后把矛头指向StratumSwitcher。
 https://github.com/btccom/btcpool/issues/216
 https://github.com/btccom/btcpool/issues/203
能解释下如果使用StratumSwitcher的话，到底是什么问题导致的，怎么修复这个问题。多谢！！！

**Comment by SwimmingTiger** [comment]
目前sserver的多链模式已经实现了StratumSwitcher的所有功能。可以考虑切换到多链模式来减少问题。所有币种都支持多链模式，并且配置和StratumSwitcher中的一一对应。
https://github.com/btccom/btcpool/blob/master/src/bitcoin/cfg/sserver(multi-chains).cfg

`zookeeper_lock_path` = `ZKServerIDAssignDir`
`zookeeper_userchain_map` = `ZKSwitcherWatchDir`
`zookeeper_auto_reg_watch_dir` = `ZKAutoRegWatchDir`

至于大小写不敏感，不再需要类似`ZKUserCaseInsensitiveIndex`的映射表，只需把`case_insensitive`设为`true`即可。

-------------------

StratumSwitcher最大的问题在于，TCP流不是面向文本行的，连接可能在不完整的文本行处中断，这样在重连后发送的第一个报文就不是合法的JSON。这可能导致某些挖矿程序异常。

此外，StratumSwitcher处理sserver侧重连的逻辑也不太稳定，可能存在竞态条件导致出问题。

**Comment by bxlkm** [comment]
多谢老大。

**Comment by rocqina** [comment]
@SwimmingTiger 这怎么理解，tcp流不是面向问本行这句话怎么理解，tcp处理不都是面向字节流的吗，go和c++的有区别吗
