### ISSUE TITLE
grin提交share问题

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#348]
老大好：
       grin全节点是btccom的2.0全节点及钱包源代码编译的，使用官方grin-miner进行测试，目前矿池出现以下问题：
I0730 07:12:04.108268   207 StratumSessionGrin.cc:223] new stratum job mining.notify: share difficulty=1
I0730 07:12:04.108314   207 StratumSessionGrin.cc:241] {"id":"Stratum","jsonrpc":"2.0","method":"job","params":{"difficulty":1,"height":280582,"job_id":2581579595,"pre_pow":"00020000000000044806000000005d3fedc30000015d852aa998c45f2d597d5a90860f8fece09316fef0c80f3ab15ac127d2b90e9e2cd07c0ef3eb2f5da97dc1bb2190052eb0b6ae53b457ef20e5ede286ad05a16343246c08898abb87a2e4417a0f08f8f500154bba3c21c9062755171e9574fef950a6d51e2055604c66deb420430911243dba7dc8ee1e6427e3764154bb3a41297bae8857235f7e9efb65592c3171f97fdd2d125d046065fab65480b0253e6e059f4c93e6a7206db94d7f866ffc8f8e5a7120934819c3684927d68c669e000000000031686b000000000019e8010002e9278e1350dd00000275"}}
I0730 07:12:04.108340   207 StratumSession.cc:516] send(599) to aaa.002 : {"id":"Stratum","jsonrpc":"2.0","method":"job","params":{"difficulty":1,"height":280582,"job_id":2581579595,"pre_pow":"00020000000000044806000000005d3fedc30000015d852aa998c45f2d597d5a90860f8fece09316fef0c80f3ab15ac127d2b90e9e2cd07c0ef3eb2f5da97dc1bb2190052eb0b6ae53b457ef20e5ede286ad05a16343246c08898abb87a2e4417a0f08f8f500154bba3c21c9062755171e9574fef950a6d51e2055604c66deb420430911243dba7dc8ee1e6427e3764154bb3a41297bae8857235f7e9efb65592c3171f97fdd2d125d046065fab65480b0253e6e059f4c93e6a7206db94d7f866ffc8f8e5a7120934819c3684927d68c669e000000000031686b000000000019e8010002e9278e1350dd00000275"}}
I0730 07:12:13.692062   207 StratumSession.cc:182] recv(554): {"id":"0","jsonrpc":"2.0","method":"submit","params":{"edge_bits":29,"height":280582,"job_id":2581579595,"nonce":6574482141980042625,"pow":[3749245,9945210,16833600,45117353,81071990,91137030,96168070,102409276,125323127,142524905,150032113,150196378,158344466,162020640,192571269,220966497,233778301,234057518,244678721,245371146,256619317,262705868,280037387,284576873,289624776,295060919,341261569,357759121,372224200,386566173,390057220,392056475,396751003,412970982,413561599,428248225,428472724,445632267,452896366,483692653,485504624,535429421]}}
I0730 07:12:13.692324   207 StratumServerGrin.cc:46] checking share nonce: 5b3d40accedea581, pre_pow: 00020000000000044806000000005d3fedc30000015d852aa998c45f2d597d5a90860f8fece09316fef0c80f3ab15ac127d2b90e9e2cd07c0ef3eb2f5da97dc1bb2190052eb0b6ae53b457ef20e5ede286ad05a16343246c08898abb87a2e4417a0f08f8f500154bba3c21c9062755171e9574fef950a6d51e2055604c66deb420430911243dba7dc8ee1e6427e3764154bb3a41297bae8857235f7e9efb65592c3171f97fdd2d125d046065fab65480b0253e6e059f4c93e6a7206db94d7f866ffc8f8e5a7120934819c3684927d68c669e000000000031686b000000000019e8010002e9278e1350dd00000275, edge_bits: 1d
I0730 07:12:13.692813   207 StratumMinerGrin.cc:154] share not reached the diff: 629
I0730 07:12:13.692867   207 StratumSession.cc:516] send(109) to aaa.002 : {"id":"0","jsonrpc":"2.0","method":"submit","error":{"code":-32502,"message":"Failed to validate solution"}}
I0730 07:12:13.692883   207 StratumMinerGrin.cc:180] share(height: 280582, jobId: 6719350595129442304..., ip: 111.200.241.61, userId: 1, workerId: -3048893114065800652, time: 1564470733/2019-07-30 07:12:13, shareDiff: 629, networkDiff: 3030598259, nonce: 5b3d40accedea581, sessionId: 02000001, status: 34/Invalid Solution)
I0730 07:12:19.134816   207 StratumServerGrin.cc:201] broadcast stratum job 5d3fedd300000000
I0730 07:12:27.654261   207 StratumServerGrin.cc:201] broadcast stratum job 5d3feddb00000000

这种情况正常吗？难度值设置的都是1

**Comment by bmhjyu** [comment]
我注意到你的任务高度为280582且区块头版本为2，这时硬分叉已经发生，算法需要切换为 cuckarood29 才能正常提交。请问你的 grin miner 配置可以贴出来看一下吗？

**Comment by bxlkm** [comment]
我想问一下，grin矿池配置的时候我没有配置29或者31按照默认给的配置设置的没有问题吧。我看注释的意思是其他值是全部解析。
grin-miner.toml:
# Sample Server Configuration File for Grin-Miner
#
# Grin-Miner will look for this file in these places: in the following
# order:
#
# -The working directory
# -The directory in which the executable resides

#########################################
### LOGGING CONFIGURATION             ###
#########################################

[logging]

# Whether to log to stdout
log_to_stdout = true

# Log level for stdout: Critical, Error, Warning, Info, Debug, Trace
stdout_log_level = "Info"

# Whether to log to a file
log_to_file = true

# Log level for file: Critical, Error, Warning, Info, Debug, Trace
file_log_level = "Debug"

# Log file path
log_file_path = "grin-miner.log"

# Whether to append to the log file (true), or replace it on every run (false)
log_file_append = true

#########################################
### MINING CLIENT CONFIGURATION       ###
#########################################

[mining]

# whether to run the tui
run_tui = true

# listening grin stratum server url
stratum_server_addr = "xxxxxx:3333"

# login for the stratum server (if required)
stratum_server_login = "bbb.001"

# password for the stratum server (if required)
stratum_server_password = "123"

# whether tls is enabled for the stratum server
stratum_server_tls_enabled = false

#The directory in which mining plugins are installed
#if not specified, grin miner will look in the directory /deps relative
#to the executable

miner_plugin_dir = "plugins"

###############################################################
### CUCKAROO(D) (i.e. GPU-Friendly) MINER PLUGIN CONFIGURATION ###
###############################################################

# Multiple plugins can be specified, (e.g. a cpu
# miner and a gpu miner running in parallel)
# Use a single plugin instance per device, as
# demonstrated below.

# Multiple instances of the same plugin can be loaded
# and used with different devices. On CPU plugins
# you'll likely only be using a single instance
# but in CUDA plugins the device number can be set
# corresponding to the device ID. (use nvidia-smi to find this)

### CUCKAROO CPU SOLVERS (Asic Resist, or GPU-Friendly)

# The fastest cpu algorithm, but consumes the most memory

[[mining.miner_plugin_config]]
plugin_name = "cuckaroo_cpu_compat_29"
[mining.miner_plugin_config.parameters]
nthreads = 1

# As above, but for processors supporting avx2

#[[mining.miner_plugin_config]]
#plugin_name = "cuckaroo_cpu_avx2_29"
#[mining.miner_plugin_config.parameters]
#nthreads = 4

# CUCKAROO(D) CUDA SOLVER
#
# CUDA plugins are not built by default. To build:
#1) Ensure the latest cuda toolkit is installed
#   (nvcc should be in your PATH)
#   Wrong gcc? install gcc-5 g++-5; export CC=`which gcc-5`; # then build
#2) Ensure the 'build-cuda-plugin' feature is included in Cargo.toml, e.g:
#   cuckoo_miner = { path = "./cuckoo-miner", features = ["build-cuda-plugins"]}
#
# Parameters can be set individually for each device by using multiple
# instance of each plugin.  device 0 is used by default
#

# currently requires 5.5GB+ GPU memory
#[[mining.miner_plugin_config]]
#plugin_name = "cuckaroo_cuda_29"
# or, to mine at height >= 262080: plugin_name = "cuckarood_cuda_29"
#[mining.miner_plugin_config.parameters]
#device = 0
#cpuload = 1
#ntrims = 176
#genablocks = 4096
#genatpb = 128
#genbtpb = 128
#trimtpb = 512
#tailtpb = 1024
#recoverblocks = 1024
#recovertpb = 1024

# e.g. To enable multiple devices (copy params from above as needed)

#[[mining.miner_plugin_config]]
#plugin_name = "cuckaroo_cuda_29"
#[mining.miner_plugin_config.parameters]
#device = 1


# mean OpenCL supports both NVidia and AMD
# to install run ./install_ocl_plugins.sh script
#[[mining.miner_plugin_config]]
#plugin_name = "ocl_cuckaroo"
#[mining.miner_plugin_config.parameters]
# 0 for default, 1 for AMD, 2 for NVidia, specify if you have
# cards from both vendors
#platform = 0
# ID withing the platform
#device = 0

###############################################################
### CUCKATOO (i.e. ASIC-Friendly) MINER PLUGIN CONFIGURATION ##
###############################################################

#mean cpu
#[[mining.miner_plugin_config]]
#plugin_name = "cuckatoo_mean_cpu_compat_31"
#[mining.miner_plugin_config.parameters]
#nthreads = 4

#mean cpu avx2
#[[mining.miner_plugin_config]]
#plugin_name = "cuckatoo_mean_cpu_avx2_31"
#[mining.miner_plugin_config.parameters]

#mean cuda, will work on a 1080TI with expand rounds set to 2
#memory requirements are tight, don't drive a display
#off the same card while trying to mine with an 11GB card

#[[mining.miner_plugin_config]]
#plugin_name = "cuckatoo_mean_cuda_gtx_31"
#[mining.miner_plugin_config.parameters]
#device = 0
#expand = 3
#cpuload = 1
#ntrims = 176
#genablocks = 4096
#genatpb = 128
#genbtpb = 128
#trimtpb = 512
#tailtpb = 1024
#recoverblocks = 1024
#recovertpb = 1024

#mean cuda optimised to use slightly less memory,
#will work on a 2080TI with expand rounds set to 2
#as above, memory requirements are tight, don't drive a display
#off the same card while trying to mine with an 11GB card

#[[mining.miner_plugin_config]]
#plugin_name = "cuckatoo_mean_cuda_rtx_31"
#[mining.miner_plugin_config.parameters]
#device = 0
#expand = 3
#cpuload = 1
#ntrims = 176
#genablocks = 4096
#genatpb = 128
#genbtpb = 128
#trimtpb = 512
#tailtpb = 1024
#recoverblocks = 1024
#recovertpb = 1024

#lean cuda
#[[mining.miner_plugin_config]]
#plugin_name = "cuckatoo_lean_cuda_31"
#[mining.miner_plugin_config.parameters]
#expand = 0
#device = 0
#cpuload = 1
#ntrims = 176
#genablocks = 4096
#genatpb = 128
#genbtpb = 128
#trimtpb = 512
#tailtpb = 1024
#recoverblocks = 1024
#recovertpb = 1024

# lean OpenCL supports both NVidia and AMD
# very slow but requires ~ 3GB of RAM
# to install run ./install_ocl_plugins.sh script
#[[mining.miner_plugin_config]]
#plugin_name = "ocl_cuckatoo"
#[mining.miner_plugin_config.parameters]
# 0 for default, 1 for AMD, 2 for NVidia, specify if you have
# cards from both vendors
#platform = 0
# ID withing the platform
#device = 0
#edge_bits = 31

**Comment by bmhjyu** [comment]
我刚刚格式化了下你的恢复，发现这里面其实使用了未注释的 cuckaroo29 算法而不是 cuckarood29 算法，所以这就无法正常工作了。你需要根据硬件选择 cuckarood 开头的某一段 plugin 配置。

```
[[mining.miner_plugin_config]]
plugin_name = "cuckaroo_cpu_compat_29"
```

**Comment by bxlkm** [comment]
我是在mac上面测试的，应该怎么配置啊 请给出指示 多谢。

**Comment by bxlkm** [comment]
只要找到一个share就拒绝了，不知道应该怎么设置了。

**Comment by bmhjyu** [comment]
把之前的那一段里面的 `cuckaroo_cpu_compat_29` 换成 `cuckarood_cpu_compat_29` 应该就可以。

**Comment by bxlkm** [comment]
cuckarood_cpu_compat_29 我没有这个插件 ，是单独构建的吗？直接报错了。

**Comment by bmhjyu** [comment]
你需要更新最新的 master 分支自行构建，2.0.0 版本的没有 CPU 的 cuckarood29 插件，只有 GPU 的。
