### ISSUE TITLE
BTC联挖nmc,ela不爆块问题？

### ISSUE THREAD

**Issue by bxlkm** [btccom/btcpool#349]
老大好：
       请问一下btc爆块的情况下，应该会爆以上2种辅币的，有时候是很正常的，但有时候很奇怪的是btc爆块了，但是其他2种辅币没有，什么样的情况下会发生这样的情况？，联挖使用的是mergedMiningProxy。

**Comment by bmhjyu** [comment]
有一些排查的方法

* 首先你可以查看一下 mergedMiningProxy 的日志和数据库，看下 BTC 爆块时是否有对应的记录，如果有记录但是实际上没有爆块，那么说明产生孤块。这是完全可能的，因为联合挖矿产生的任务更新没有强制要求矿机也更新任务，所以确实有可能矿机还在挖的任务对应联合挖矿币种的旧块高。
* 如果没有记录，那么很可能联合挖矿信息可能没有正确填入挖矿任务。可以用区块浏览器查看那个没有爆联合挖矿区块的 BTC 区块 coinbase 交易的 input 内容，看里面有没有 `fabe6d6d` 这个联合挖矿的标记，如果没有则当时的任务没有包括联合挖矿。

**Comment by YihaoPeng** [comment]
长时间没有回应
