### ISSUE TITLE
BLOCK_REWARD is a const in Stratum.h

### ISSUE THREAD

**Issue by YihaoPeng** [btccom/btcpool#35]
```cpp
// TODO: update when next Halving
#define BLOCK_REWARD 1250000000ll
```

We may forget to update after next halving.

**Comment by YihaoPeng** [comment]
And the timestamp checking.

```cpp
/* TODO: increase timestamp check before 2020-01-01 */
    if (userId_ > 0 && workerHashId_ != 0 && share_ > 0 &&
        timestamp_ > 1467816952U /* 2016-07-06 14:55:52 UTC+0 */ &&
        timestamp_ < 1577836800U /* 2020-01-01 00:00:00 UTC+0 */ &&
        jobTime    > 1467816952U /* 2016-07-06 14:55:52 UTC+0 */ &&
        jobTime    < 1577836800U /* 2020-01-01 00:00:00 UTC+0 */) {
      return true;
    }
```

**Comment by certsblock** [comment]
Maybe we could use GetBlockSubsidy to auto compute the reward.
```c++
#include <chainparams.h>
#include "BitcoinUtils.h"

const CChainParams& chainparams = Params();
auto reward = GetBlockSubsidy(blockHeight, chainparams.GetConsensus());

```
It will no longer need checking timestamp, it will auto update after next halving.

**Comment by YihaoPeng** [comment]
`coinbasevalue` is a part of [getblocktemplate](https://github.com/bitcoin/bips/blob/master/bip-0022.mediawiki)'s result. We can use it directly.

**Comment by zheng9980419** [comment]
How does the LTC pool be built?

**Comment by YihaoPeng** [comment]
I have not tried LTC. Because its POW algorithm is different from Bitcoin, it may not be a simple link and the pool needs to be modified.

**Comment by zheng9980419** [comment]
How does the ETF pool be built?

**Comment by YihaoPeng** [comment]
The code of supporting Ethereum (ETH) is in review. And how to build or deploy is not determinate.

**Comment by zheng9980419** [comment]
ying yu tai lei . ni hui da jian etf me ? you mei you etf yuan ma

**Comment by YihaoPeng** [comment]
Sorry, I don't have.

**Comment by YihaoPeng** [comment]
Try fix it at https://github.com/btccom/btcpool/commit/72065532aa2c64235d6d669d6e91009b82cf7641
Not tested. I don't know if this will bring a lot of precision loss.

**Comment by YihaoPeng** [comment]
I have tested that the new calculation method will not lead to a difference in the earning of more than 1 satoshi.
When double is converted to an integer, rounding will be used, so there is a difference of up to 1 satoshi.
But the issue will keep open until the above commit was merged by master branch.
