### ISSUE TITLE
请问如何支持bitcoin1.8.1

### ISSUE THREAD

**Issue by mzspring** [btccom/btcpool#350]
请问如何支持bitcoin1.8.1, crypto目录已经没有libbitcoin_crypto.a
试图把bitcoin 1.6.0的libbitcoin_crypto.a放进去，编译不过

**Comment by bmhjyu** [comment]
Bitcoin 0.18.x 的静态链接库应当类似于 Bitcoin-ABC 了，需要自行修改 CMakeLists.txt 来适配。但是其实使用 Bitcoin 0.16.3 来构建矿池并且使用 0.18.x 的节点来挖矿是可行的，并不一定需要使用相同的版本。

**Comment by mzspring** [comment]
谢谢，这一块，官方或其他使用者，有做过测试么。btcpool官方有计划支持Bitcoin 0.18.x 么？

**Comment by mzspring** [comment]
谢谢，btcpool官方有计划支持Bitcoin 0.18.x么？使用 Bitcoin 0.16.3 来构建矿池并且使用 0.18.x 的节点来挖矿
现在是不是大家都是这样用。

**Comment by YihaoPeng** [comment]
比特币（BTC）从0.16起没有硬分叉，甚至没有软分叉，矿池后端链接到旧版本代码显然是毫无问题的。

升级到新版本代码看起来并无必要。

当然，你可以运行新版比特币节点，可能会更好，但这与矿池后端无关。对于矿池后端来说，比特币0.16的源代码只是它的依赖库而已。在还能继续用的情况下，没有必要升级。
