### ISSUE TITLE
stratum switcher 热更新

### ISSUE THREAD

**Issue by onigirisan** [btccom/btcpool#351]
现在最新的master已经支持，平滑重启，热更新sserver也仍然支持吗

**Comment by onigirisan** [comment]
刚有看到这个issue https://github.com/btccom/btcpool/issues/322 不知道有没有新的进展

**Comment by bmhjyu** [comment]
热更新 sserver 并不支持，之前的热更新是指 switcher 的热更新，sserver 本身从未支持热更新。虽然我们有意愿，但是 sserver 本身的复杂性使得热更新的实现也会很复杂，目前暂时还没有进行相应工作。

**Comment by onigirisan** [comment]
好的谢谢解答
