### ISSUE TITLE
请教一下数据库新增的share_stale和share_reject的问题

### ISSUE THREAD

**Issue by sslazio2009** [btccom/btcpool#356]
数据库的表里面share_reject分成了share_stale和share_reject，大部分的都是share_stale，拒绝率就降低很多了。是这两个参数能反应矿机或者矿池的什么问题吗所以要分开？反正没接受的不都应该显示给矿机拒绝吗？

**Comment by rocqina** [comment]
只能从代码注释中看到一点，就是share_stale是给予一定奖励的，但是比share_accept要少很多，share_reject是没有奖励的。具体比例不知道，需要大佬们进一步解释

**Comment by YihaoPeng** [comment]
我们计划在前端显示单独的stale曲线，并且还可以给reject曲线加上每种reject类型占比的鼠标提示。

**Comment by sslazio2009** [comment]
> 我们计划在前端显示单独的stale曲线，并且还可以给reject曲线加上每种reject类型占比的鼠标提示。
> 至于stale share的奖励，除了以太坊可以选择性开启，其他币种的stale都没有奖励。
> 
> 此外，对比特币来说返回的错误类型没有改变（因为协议建议使用`21 - Job not found (=stale)`），保持一致有助于避免矿机兼容性问题。对以太坊来说，错误代码一直是我们自定义的，所以改变了没关系。

请问对于btc来说如果未来升级矿池后端，前端还是维持原来的显示（算力和拒绝率曲线），那么拒绝率计算是（share_reject+share_reject）/（share_reject+share_reject+share_accept）吗？

**Comment by YihaoPeng** [comment]
> 请问对于btc来说如果未来升级矿池后端，前端还是维持原来的显示（算力和拒绝率曲线），那么拒绝率计算是（share_reject+share_reject）/（share_reject+share_reject+share_accept）吗？

是的。

-------------

此外对于比特币来说，share_stale是没有奖励的。对于以太坊来说，share_stale可以给奖励，取决于slparser的配置。
