### ISSUE TITLE
beam hard fork release

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#357]
请问，“BEAM Hard Fork #321321: BeamHash II” —— 这个有编译好的二进制下载吗？谢谢！

**Comment by YihaoPeng** [comment]
有docker镜像：
```
docker pull btccom/btcpool:2019.08.07-19-beam-hard-fork_btc-0.16.3
```
在镜像的`/work/package`目录有deb包，可以安装在Ubuntu18.04上。

**Comment by xwen01** [comment]
> 有docker镜像：
> 
> ```
> docker pull btccom/btcpool:2019.08.07-19-beam-hard-fork_btc-0.16.3
> ```
> 
> 在镜像的`/work/package`目录有deb包，可以安装在Ubuntu18.04上。
> 镜像也可以直接使用，参考
> https://github.com/btccom/btcpool/tree/master/docker/btcpool/deploy
> 
> 至于BEAM节点，目前还没有构建好的镜像发布，需要自己`docker build`一下。
> https://github.com/btccom/btcpool/tree/master/docker/beam-node/main-release-mining

谢谢回复。btcpool的话，我只要git pull一下重新编译就行了吧？
Beam节点我已经git clonel了mining-hard-fork branch，并且编译通过了，不过我关掉了qt_ui_wallet：```set(BEAM_QT_UI_WALLET FALSE)```，这个没关系吧？

**Comment by YihaoPeng** [comment]
> btcpool的话，我只要git pull一下重新编译就行了吧？
对。此外，statshttpd/slparser组件的mysql表结构改变了，这个之前忘记写在更新说明里了：
https://github.com/btccom/btcpool/blob/9c8bbd84b429b0fa9d59c46489440fb93d60b042/install/db.change.sql#L18-L54

**Comment by YihaoPeng** [comment]
`set(BEAM_QT_UI_WALLET FALSE)`没问题，也可以用以下编译选项：
```
cmake -DCMAKE_BUILD_TYPE=Release -DBEAM_NO_QT_UI_WALLET=ON .
```

**Comment by xwen01** [comment]
> `set(BEAM_QT_UI_WALLET FALSE)`没问题，也可以用以下编译选项：
> 
> ```
> cmake -DBEAM_NO_QT_UI_WALLET=ON .
> ```
> 
> 这样就不用改cmakefiles了。

好的。顺便请教一个之前遇到的问题，就是我编译了最新的btcpool之后，用beam的testnet测试挖了一下，池子记录爆块了，但是爆块的hash和区块链上的不匹配，等于是孤块，不过beam node和beam wallet用的是官方下载的版本。请问这个应该是我自己哪里没有配置对？还是说beam版本可能有问题？
谢谢。

**Comment by YihaoPeng** [comment]
如果你的beam节点不具有这个提交：
https://github.com/btccom/beam/commit/870ca8a559aa3beb35a883307437b9ac69d3de0b

则BTCPool没有任何办法知道爆块的真实hash，只有PoW Hash会被记录（具有一系列尾缀0，取决于区块难度，类似于BTC区块的前导0）。

通过向节点添加这个补丁：
https://github.com/btccom/beam/commit/e47cb8978297c43f440e129ac5f2e6b86090e46c
可以在同步时打印真实hash和PoW Hash，这样你就可以知道你爆的块是不是在主链了。

日志举例：
```
I 2019-08-13.15:39:47.524 Block Hash 315808 ffebf61c136fb6eae7ec2a26ea510b61be330ae7d52eeda44049041c00000000 c036463dc4bc31b15f93935fa9dd6c6cab3de8004633ed429ff3beed6afc2d24 valid
I 2019-08-13.15:39:47.525 Block Hash 315809 3ab9fef5cc198d378494853467027e9fdfd38ab2750bdb2fb67c1d5407000000 6363ee0631f8b6192a73452f78819bc596f97d84a9904dac0f28afe9c579a41f valid
I 2019-08-13.15:39:47.533 Block Hash 315810 a3debfbf64a692d5298fb475de0f3a68f692ce17fe67d045af3ac69207000000 39f19ced5607911729a4444df1e90eb57189ba2941b4cb2f54e0ecb6cf0d7a18 valid
```

通过日志生成把PoW Hash更新为真实hash的语句：
```
cat logs/node_*.log | grep 'Block Hash' | awk "{printf \"UPDATE found_blocks SET hash='\"\$7\"' WHERE hash='\"\$6\"'; -- \"\$5\"\n\"}" > update-beam-block-hash.sql
```

**Comment by xwen01** [comment]
> 如果你的beam节点不具有这个提交：
> [btccom/beam@870ca8a](https://github.com/btccom/beam/commit/870ca8a559aa3beb35a883307437b9ac69d3de0b)
> 
> 则BTCPool没有任何办法知道爆块的真实hash，只有PoW Hash会被记录（具有一系列尾缀0，取决于区块难度，类似于BTC区块的前导0）。PoW Hash无法在区块浏览器中查询。
> 
> 通过向节点添加这个补丁：
> [btccom/beam@e47cb89](https://github.com/btccom/beam/commit/e47cb8978297c43f440e129ac5f2e6b86090e46c)
> 可以在同步时打印真实hash和PoW Hash，这样你就可以知道你爆的块是不是在主链了。
> 
> 日志举例：
> 
> ```
> I 2019-08-13.15:39:47.524 Block Hash 315808 ffebf61c136fb6eae7ec2a26ea510b61be330ae7d52eeda44049041c00000000 c036463dc4bc31b15f93935fa9dd6c6cab3de8004633ed429ff3beed6afc2d24 valid
> I 2019-08-13.15:39:47.525 Block Hash 315809 3ab9fef5cc198d378494853467027e9fdfd38ab2750bdb2fb67c1d5407000000 6363ee0631f8b6192a73452f78819bc596f97d84a9904dac0f28afe9c579a41f valid
> I 2019-08-13.15:39:47.533 Block Hash 315810 a3debfbf64a692d5298fb475de0f3a68f692ce17fe67d045af3ac69207000000 39f19ced5607911729a4444df1e90eb57189ba2941b4cb2f54e0ecb6cf0d7a18 valid
> ```
> 
> 通过日志生成把PoW Hash更新为真实hash的SQL语句：
> 
> ```
> cat logs/node_*.log | grep 'Block Hash' | awk "{printf \"UPDATE found_blocks SET hash='\"\$7\"' WHERE hash='\"\$6\"'; -- \"\$5\"\n\"}" > update-beam-block-hash.sql
> ```

好的，那我试试mining-hard-fork版本，这个版本会记录爆块的真实hash对吧？
之前发现hash不匹配的同时，beam wallet里也没有看到balance增加，那说明应该不仅仅是记录hash不正确的问题了？

**Comment by YihaoPeng** [comment]
> 好的，那我试试mining-hard-fork版本，这个版本会记录爆块的真实hash对吧？

对。

> 之前发现hash不匹配的同时，beam wallet里也没有看到balance增加，那说明应该不仅仅是记录hash不正确的问题了？

嗯，有可能是孤块。可以用带有 https://github.com/btccom/beam/commit/e47cb8978297c43f440e129ac5f2e6b86090e46c.patch 补丁的节点重新同步，然后搜索日志来确认某个PoW Hash是否在主链。或者也可以看一看当时testnet beam node的日志，也许它直接拒绝了提交。

哦对了，刚想起来，以前的testnet挖矿参数和主链不相同，也就是说和现有的主链挖矿软件都不兼容。分叉后不知道有没有改变。你可以把挖矿软件直接连接到beam node的stratum端口来进行验证。

如果现在testnet还是不兼容主链挖矿软件，你还可以用这个分支：
https://github.com/btccom/beam/tree/private-testnet-hard-fork

这是我做的测试网络，挖矿参数与主链相同，爆块难度很低，分叉高度是50。

**Comment by xwen01** [comment]
> > 好的，那我试试mining-hard-fork版本，这个版本会记录爆块的真实hash对吧？
> 
> 对。
> 
> > 之前发现hash不匹配的同时，beam wallet里也没有看到balance增加，那说明应该不仅仅是记录hash不正确的问题了？
> 
> 嗯，有可能是孤块。可以用带有 https://github.com/btccom/beam/commit/e47cb8978297c43f440e129ac5f2e6b86090e46c.patch 补丁的节点重新同步，然后搜索日志来确认某个PoW Hash是否在testnet链。或者也可以看一看当时testnet beam node的日志，也许它直接拒绝了提交。
> 
> 哦对了，刚想起来，以前的testnet挖矿参数和主链不相同，也就是说现有的主链挖矿软件和testnet都不兼容，btcpool和testnet也不兼容。分叉后不知道有没有改变。你可以把挖矿软件直接连接到beam node的stratum端口来进行验证。
> 
> 如果现在testnet还是不兼容主链挖矿软件，你还可以用这个分支：
> https://github.com/btccom/beam/tree/private-testnet-hard-fork
> 
> 这是我做的测试网络，挖矿参数与主链相同，爆块难度很低，分叉高度是50。
> 修改方法：
> https://gist.github.com/SwimmingTiger/1fde11c8806db921ba4a2f77220509db

感谢回复！理论上讲，如果我部署了最新的btcpool和beam mining-hard-fork branch，直接上主链挖是没问题的吧？

**Comment by xwen01** [comment]
> > 好的，那我试试mining-hard-fork版本，这个版本会记录爆块的真实hash对吧？
> 
> 对。
> 
> > 之前发现hash不匹配的同时，beam wallet里也没有看到balance增加，那说明应该不仅仅是记录hash不正确的问题了？
> 
> 嗯，有可能是孤块。可以用带有 https://github.com/btccom/beam/commit/e47cb8978297c43f440e129ac5f2e6b86090e46c.patch 补丁的节点重新同步，然后搜索日志来确认某个PoW Hash是否在testnet链。或者也可以看一看当时testnet beam node的日志，也许它直接拒绝了提交。
> 
> 哦对了，刚想起来，以前的testnet挖矿参数和主链不相同，也就是说现有的主链挖矿软件和testnet都不兼容，btcpool和testnet也不兼容。分叉后不知道有没有改变。你可以把挖矿软件直接连接到beam node的stratum端口来进行验证。
> 
> 如果现在testnet还是不兼容主链挖矿软件，你还可以用这个分支：
> https://github.com/btccom/beam/tree/private-testnet-hard-fork
> 
> 这是我做的测试网络，挖矿参数与主链相同，爆块难度很低，分叉高度是50。
> 修改方法：
> https://gist.github.com/SwimmingTiger/1fde11c8806db921ba4a2f77220509db

你好，想请教一个跟这个话题不太相关的问题，btcpool可以有方法显示当前的幸运度（variance）吗？谢谢~

**Comment by xwen01** [comment]
> > 好的，那我试试mining-hard-fork版本，这个版本会记录爆块的真实hash对吧？
> 
> 对。
> 
> > 之前发现hash不匹配的同时，beam wallet里也没有看到balance增加，那说明应该不仅仅是记录hash不正确的问题了？
> 
> 嗯，有可能是孤块。可以用带有 https://github.com/btccom/beam/commit/e47cb8978297c43f440e129ac5f2e6b86090e46c.patch 补丁的节点重新同步，然后搜索日志来确认某个PoW Hash是否在testnet链。或者也可以看一看当时testnet beam node的日志，也许它直接拒绝了提交。
> 
> 哦对了，刚想起来，以前的testnet挖矿参数和主链不相同，也就是说现有的主链挖矿软件和testnet都不兼容，btcpool和testnet也不兼容。分叉后不知道有没有改变。你可以把挖矿软件直接连接到beam node的stratum端口来进行验证。
> 
> 如果现在testnet还是不兼容主链挖矿软件，你还可以用这个分支：
> https://github.com/btccom/beam/tree/private-testnet-hard-fork
> 
> 这是我做的测试网络，挖矿参数与主链相同，爆块难度很低，分叉高度是50。
> 修改方法：
> https://gist.github.com/SwimmingTiger/1fde11c8806db921ba4a2f77220509db

你好，我试了一下你发的这个分支：
https://github.com/btccom/beam/tree/private-testnet-hard-fork

发现beam-node不会同步：
```
I 2019-08-20.00:28:07.460 stratum server listens to 0.0.0.0:3333
I 2019-08-20.00:28:07.461 GenerateNewBlock: size of block = 294; amount of tx = 0
I 2019-08-20.00:28:07.461 Block generated: Height=1, Fee=0, Difficulty=03-000000(8), Size=294
I 2019-08-20.00:28:07.461 New job for external miner
I 2019-08-20.00:28:07.461 stratum server new job 1 will be sent to 0 connected peers
I 2019-08-20.00:28:07.461 +Peer 52.221.31.79:8100
I 2019-08-20.00:28:08.459 PI 95b07773ab7f82dd--35.157.180.66:8100 Rating 0 -> 1
I 2019-08-20.00:28:08.459 +Peer 35.157.180.66:8100
I 2019-08-20.00:28:08.619 Peer 52.221.31.79:8100 Connected
I 2019-08-20.00:28:08.620 Peer 52.221.31.79:8100 Auth. Type=N, ID=6e174ea6566cf53c
I 2019-08-20.00:28:08.621 52.221.31.79:8100 received PI
I 2019-08-20.00:28:08.621 deleted anonymous PI
I 2019-08-20.00:28:08.621 PI 6e174ea6566cf53c--0.0.0.0 New
I 2019-08-20.00:28:08.621 PI 6e174ea6566cf53c--0.0.0.0 Address changed to 52.221.31.79:8100
I 2019-08-20.00:28:08.621 PI 6e174ea6566cf53c--52.221.31.79:8100 connected, info updated
W 2019-08-20.00:28:08.621 52.221.31.79:8100: Incompatible peer cfg: cfa9cf691cfe775a
I 2019-08-20.00:28:08.621 -Peer 52.221.31.79:8100
I 2019-08-20.00:28:08.621 PI 6e174ea6566cf53c--52.221.31.79:8100 Rating 1024 -> 0
E 2019-08-20.00:28:08.621 on_new_message int(type)=0 ret=0
I 2019-08-20.00:28:08.847 Peer 35.157.180.66:8100 Connected
I 2019-08-20.00:28:08.848 Peer 35.157.180.66:8100 Auth. Type=N, ID=ed8b3c2dd0acd840
I 2019-08-20.00:28:08.849 35.157.180.66:8100 received PI
I 2019-08-20.00:28:08.849 PeerID is different
I 2019-08-20.00:28:08.849 PI ed8b3c2dd0acd840--0.0.0.0 New
I 2019-08-20.00:28:08.849 PI ed8b3c2dd0acd840--0.0.0.0 Address changed to 35.157.180.66:8100
I 2019-08-20.00:28:08.849 PI ed8b3c2dd0acd840--35.157.180.66:8100 connected, info updated
W 2019-08-20.00:28:08.849 35.157.180.66:8100: Incompatible peer cfg: cfa9cf691cfe775a
I 2019-08-20.00:28:08.849 -Peer 35.157.180.66:8100
I 2019-08-20.00:28:08.849 PI ed8b3c2dd0acd840--35.157.180.66:8100 Rating 1024 -> 0
E 2019-08-20.00:28:08.849 on_new_message int(type)=0 ret=0
I 2019-08-20.00:28:09.460 PI ef714eb446b23338--52.52.95.99:8100 Rating 0 -> 1
I 2019-08-20.00:28:09.460 +Peer 52.52.95.99:8100
I 2019-08-20.00:28:09.800 Peer 52.52.95.99:8100 Connected
I 2019-08-20.00:28:09.801 Peer 52.52.95.99:8100 Auth. Type=N, ID=72c5129333a139ea
I 2019-08-20.00:28:09.801 52.52.95.99:8100 received PI
I 2019-08-20.00:28:09.801 PeerID is different
I 2019-08-20.00:28:09.801 PI 72c5129333a139ea--0.0.0.0 New
I 2019-08-20.00:28:09.801 PI 72c5129333a139ea--0.0.0.0 Address changed to 52.52.95.99:8100
I 2019-08-20.00:28:09.801 PI 72c5129333a139ea--52.52.95.99:8100 connected, info updated
W 2019-08-20.00:28:09.801 52.52.95.99:8100: Incompatible peer cfg: cfa9cf691cfe775a
I 2019-08-20.00:28:09.801 -Peer 52.52.95.99:8100
I 2019-08-20.00:28:09.801 PI 72c5129333a139ea--52.52.95.99:8100 Rating 1024 -> 0
E 2019-08-20.00:28:09.801 on_new_message int(type)=0 ret=0
I 2019-08-20.00:28:10.461 PI 2c261fbb28ad87fa--52.74.254.40:8100 Rating 0 -> 1
I 2019-08-20.00:28:10.461 +Peer 52.74.254.40:8100
I 2019-08-20.00:28:10.626 Peer 52.74.254.40:8100 Connected
I 2019-08-20.00:28:10.628 Peer 52.74.254.40:8100 Auth. Type=N, ID=6e174ea6566cf53c
I 2019-08-20.00:28:10.628 52.74.254.40:8100 received PI
I 2019-08-20.00:28:10.628 PeerID is different
I 2019-08-20.00:28:10.628 PI 6e174ea6566cf53c--52.221.31.79:8100 Address changed to 52.74.254.40:8100
I 2019-08-20.00:28:10.628 Banned PI. Ignoring
I 2019-08-20.00:28:10.628 -Peer 52.74.254.40:8100
```
beam-node.cfg里：
```
peer=ap-nodes.testnet.beam.mw:8100,eu-nodes.testnet.beam.mw:8100,us-nodes.testnet.beam.mw:8100
```

请问这是什么问题呢？想用testnet测试一下btcpool的beam爆块，谢谢！
