### ISSUE TITLE
矿池不爆块

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#358]
请问，btcpool挖grin在一段时间正常爆块之后，突然出现长时间不爆块的情况，这种情况有可能是什么原因引起的呢？由于期间没有做任何修改，比较困惑，查看各个系统日志都正常。
谢谢！

**Comment by sslazio2009** [comment]
可以抓包观察矿机是否能正常连接，矿池题目是否正常时间下发，是否发错旧题每个字段是否正确，是否多个sserver下发题目对话id重复浪费算力。
再不行增加矿机，缩短理论爆块时间，grin还好加算力不贵，块也不贵。

**Comment by xwen01** [comment]
> 可以抓包观察矿机是否能正常连接，矿池题目是否正常时间下发，是否发错旧题每个字段是否正确，是否多个sserver下发题目对话id重复浪费算力。
> 再不行增加矿机，缩短理论爆块时间，grin还好加算力不贵，块也不贵。

感谢回复！从sserver的日志看，一直有矿机断开重连的情况，不过这个情况一直都有，爆块正常的时候也会观察到。sserver只有一个。
现在观察到的现象很奇怪就是当矿机多的时候，很长时间不爆块（variance 500%以上了），矿机少（几十台）反而爆块正常。除了你上面提到的几个问题，还有什么需要查的吗？
有什么可以优化的建议吗？比如sserver的max_job_lifetime是900秒，这个是否需要调小一点？extranonce的分配是+1的方式？这个是否需要优化？比如改为随机？
谢谢！
