### ISSUE TITLE
关于btcpool跨国算力融合共享StratumJob的问题请教

### ISSUE THREAD

**Issue by learsu** [btccom/btcpool#36]
比如有两个矿场分别位于中国和加拿大，我在中国部署了btcpool，我想把加拿大的算力融合在一起共享kafka中的StratumJob，是在加拿大部署sserver远程连接中国的kafka还是将zookeeper+kafka分别部署在中国和加拿大进行partitions，sserver只使用特定kafka的partitions？
PS：这套程序的模块化和模块间解耦可以当作教科书。

**Comment by YihaoPeng** [comment]
不好意思最近比较忙，现在才来得及回应。就跨国/跨地区kafka消息共享这个问题，我这边也很感兴趣，但是一直没有想到好的解决方法。我个人认为，国际联网是比较不可靠的（延迟高，经常性断流），依靠国际联网来传递kafka消息风险很高，所以我们这边都是在每个地区各自搭建一套完整的btcpool，并没有做整合。

如果真的想要整合的话，可以在最终展示算力的时候做整合，就是把两边数据库中的值加起来做为最终算力。

**Comment by learsu** [comment]
非常感谢YihaoPeng在百忙之中解答。每个地区各自搭建一套完整的btcpool只需要把stratum server设置不同的server id和全网每个miner都中唯一的uuid就可以保证任务不重叠吗？在跨区域的两个矿池中，如何才能让miner的任务没有其他miner任务重叠，规避算力浪费？
谢谢先，

**Comment by yockii** [comment]
这应该理解为完全独立的2个矿池，增加了总体的计算胜率而已

**Comment by YihaoPeng** [comment]
要让两个地区的两台矿机拥有一样的任务，必须满足以下全部条件：

1、两边的bitcoind内存池状态严格相同。
2、两边的gbtmaker在同一时刻调用了getblocktemplate（block template里面有时间戳）。
3、两边的jobmaker在同一时刻产生了job（coinbase2里面有时间戳）。
4、两边的矿机连在 server id 相同的两个 stratum server 上，并且恰好 session id 相等。

总的来说，以上4个条件全部达成的情况还是比较少的。

**Comment by learsu** [comment]
谢谢YihaoPeng的解答。

**Comment by YihaoPeng** [comment]
我刚刚突然想到一个简单的方法保证每个地区的job不重复：只需要在 [coinbase_info](https://github.com/btccom/btcpool/blob/ee35ab14df91837207086b17cc623fb9af254dce/src/jobmaker/jobmaker.cfg#L53) 里面加一个地区标识就可以了。比如 /BTC.COM/us/ 、 /BTC.COM/cn/ 等。

**Comment by learsu** [comment]
@YihaoPeng 这个方法很巧。利害
