### ISSUE TITLE
workerId为什么是负数

### ISSUE THREAD

**Issue by mzspring** [btccom/btcpool#364]
管理员老大你好：请教一下 workerId 是不是将矿工名做一下HASH。比如ABCD.001 将这个分解后，calcWorkerId(“ABCD”）一下。
但是sharelog打印出来的矿工号是负数或者和calcWorkerId得到的值不符合，不知为什么。

**Comment by YihaoPeng** [comment]
`calcWorkerId`返回的是`int64_t`，本来就是有符号的，是负数很正常。负数的概率为 50%

ABCD.001 将这个分解后，calcWorkerId(“ABCD”）一下，显然会与 worker id 不符合，因为我们说的 worker id 是 `001`，不是`ABCD`。我们称`ABCD`为`user name`或者`sub account name`，在数据库里通过`puid`表示。
