### ISSUE TITLE
sharelogger打的日志中有一个shareDiff: 4 这里4怎么来的

### ISSUE THREAD

**Issue by mzspring** [btccom/btcpool#365]
sharelogger打的日志中有一个shareDiff: 4 这里4怎么来的，如何计算出来的，含义是什么

**Comment by sslazio2009** [comment]
创始块难度的四倍，创世块除以计算结果hash

**Comment by mzspring** [comment]
> 
> 
> 创始块难度的四倍，创世块除以计算结果hash

好的，谢谢

**Comment by YihaoPeng** [comment]
准确的说，4是指“矿池难度1的4倍”，矿池把一个特定的hash目标（具有特定前导0的256位整数，比如对于比特币是`0x00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF`）设为难度1。如果难度1的hash目标与矿池任务要求达到的hash目标的比值为4，则这个任务的难度就为4（此时hash目标为`0x00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF / 4 = 0x000000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF`）。此时，如果矿机挖到一个小于该难度目标的share，则它的shareDiff就为4。
