### ISSUE TITLE
换了新版本以后ETH的拒绝率有点高

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#368]
几乎都是stale的。配置方面是按照默认提供的ETH配置。
 share_avg_seconds = 15;
  max_job_lifetime = 300;  // seconds
  default_difficulty = "800000000";
  max_difficulty = "4000000000000000";
  min_difficulty = "80000000";
  diff_adjust_period = 300;
对于eth13秒一个块， share_avg_seconds=15是保证一个块提交一次吗

**Comment by rocqina** [comment]
还有就是10秒一个块的话，job的生命周期300秒，还有意义吗

**Comment by YihaoPeng** [comment]
正常的范围应该是3%😂
你之前的版本应该是完全接收stale，把stale标记为`accept_stale`并且给予较少收益的版本。
现在的版本默认拒绝stale，完全不给收益。但是可以修改statshttpd和slparser的配置开启旧行为（`accept_stale=true;`）。

**Comment by YihaoPeng** [comment]
job的生命周期300秒没有意义，可以缩短。这里只是取了默认值(因为BTC是300秒)。
