### ISSUE TITLE
拒绝率计算的问题

### ISSUE THREAD

**Issue by onigirisan** [btccom/btcpool#371]
最新的master，statshttpd中把 stale share 从 reject share 中拆出
但是在ShareLogParser中计算拒绝率的时候公式仍然是：
 
rejectRate = (double)reject / (accept + reject);

这里是否改成以下公式会更适合
if(acceptStale_) {
  rejectRate = (double)reject / (accept + stale + reject);
} esle {
  rejectRate = (double)(reject + stale )/ (accept + stale + reject);
}

**Comment by SwimmingTiger** [comment]
我添加stale字段的目的就是将其从拒绝率中踢出去单独列出。所以目前的实现符合我的需要。如果你想继续在拒绝率中列出，可以考虑自己创建分支，或者编写代码提供选项控制程序行为。

**Comment by onigirisan** [comment]
好的，谢谢
