### ISSUE TITLE
请教eth的块奖励有方法能包含手续费吗

### ISSUE THREAD

**Issue by rocqina** [btccom/btcpool#372]
现在康斯坦丁之后写死的是2，没有包含手续费

**Comment by rocqina** [comment]
是不是因为gasused可以取得，但是每笔的gasprice不好取得,或者说平均的gasprice不好取得，所以没法统计手续费？

**Comment by rocqina** [comment]
getGasPrice*每个区块头的gasUsed，应该就是估算的这个区块的手续费

**Comment by de1acr0ix** [comment]
> getGasPrice*每个区块头的gasUsed，应该就是估算的这个区块的手续费

这里的问题在于，区块头的 gas used 字段是打包的所有交易使用的 gas 量总和，而每个交易的 gas price 并不一样，而 `eth_gasPrice` 获取的其实是最近若干个区块的 gas price 中位数，这样的计算方法必然有误差。

对于已经在链上的区块，`eth_getBlockByHash` 和 `eth_getBlockByNumber` 都有第二个可选参数可以让 RPC 返回区块内的所有交易，这样就不需要逐个交易调用来。

如果想知道待挖区块的奖励，也许再扩展一下 `eth_getWork` 直接统计返回要更简单些。虽然 `eth_getBlockByNumber` 是可以用 `pending` 当参数来获取待挖区块的信息，但是如前所述该用法已经被标为 deprecated 并且调用这个方法并不一定能得到正确结果。

**Comment by rocqina** [comment]
因为是延后一天结算，我们是出块后根据每笔交易后算的，可以很精确，不再矿池逻辑里。代挖区块的奖励，对我们结算现在看来不怎么重要

**Comment by BigPingge** [comment]
> 因为是延后一天结算，我们是出块后根据每笔交易后算术的，可以很精确，不再矿池逻辑里。代挖区块的奖励，对我们结算现在看来不怎么重要

您好，我最近在弄eth，遇到了点问题，能留个联系方式吗
