### ISSUE TITLE
Latest release, Build Error 

### ISSUE THREAD

**Issue by BobZombiE69** [btccom/btcpool#373]
The latest commits , has build error (on clean install ubuntu 16)
but older commits are ok.

`[ 59%] Building CXX object CMakeFiles/btcpool.dir/src/bitcoin/StratumServerBitcoin.cc.o
/work/btcpool.btc/src/bitcoin/JobMakerBitcoin.cc: In member function ‘virtual bool JobMakerHandlerBitcoin::initConsumerHandlers(const string&, std::vector<JobMakerConsumerHandler>&)’:
/work/btcpool.btc/src/bitcoin/JobMakerBitcoin.cc:91:35: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const std::__cxx11::basic_string<char>&; _U2 = int; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = int]’
       {def()->vcashRawGwTopic_, 0}};
                                   ^
compilation terminated due to -Wfatal-errors.
CMakeFiles/btcpool.dir/build.make:1791: recipe for target 'CMakeFiles/btcpool.dir/src/bitcoin/JobMakerBitcoin.cc.o' failed
make[2]: *** [CMakeFiles/btcpool.dir/src/bitcoin/JobMakerBitcoin.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:956: recipe for target 'CMakeFiles/btcpool.dir/all' failed
make[1]: *** [CMakeFiles/btcpool.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by BobZombiE69** [comment]
The last commit that i can build without error is

32eb021aa8fc47c03dd005b7005e08002f2f14f7

**Comment by de1acr0ix** [comment]
We have used some post-C++14 features (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4387) which is not yet supported in GCC 5.3. This is obviously a mistake and we will fix it (we did not discover it as we are using a newer compiler version).

**Comment by de1acr0ix** [comment]
It shall be fixed by 08fa2b86deb4c6c7e0948123b98cdd8be732906d.
