### ISSUE TITLE
BSV算力减少60%问题

### ISSUE THREAD

**Issue by ajspider** [btccom/btcpool#377]
我用btcpool 搭建完后，连接一台矿机，30秒才处理一个share 算力减少了60% 这是为什么，是哪些地方没设置好么。

**Comment by rocqina** [comment]
# how many seconds between two share submit
  share_avg_seconds = 10;

  # default difficulty (hex)
  default_difficulty = "4000";

  # max difficulty (hex)
  max_difficulty = "4000000000000000";

  # min difficulty (hex)
  min_difficulty = "40";

  # Adjust difficulty once every N second
  diff_adjust_period = 900;
参考一下这个配置

**Comment by YihaoPeng** [comment]
把默认难度降低10倍，这可以让你3秒收到一个share。但是算力并不会增加10倍，因为10个低难度share等于一个高难度share。
```
default_difficulty = "400";
```

算力是一段时间的share难度之和与达到难度1所需的运算次数之积，再比上这段时间的秒数所得到的值，它与share的数量没有直接关系，因为在矿机工况不发生变化的情况下，提交数量的减少意味着提交难度的增加，总算力还是不变。

https://github.com/btccom/btcpool/wiki/How-to-compute-a-worker's-hashrate-%7C-%E5%A6%82%E4%BD%95%E8%AE%A1%E7%AE%97%E7%9F%BF%E5%B7%A5%E7%9A%84%E5%93%88%E5%B8%8C%E9%80%9F%E7%8E%87

**Comment by YihaoPeng** [comment]
长时间没有新回应
