### ISSUE TITLE
CKB如何配置，需要启动那些服务？

### ISSUE THREAD

**Issue by bxlkm1** [btccom/btcpool#378]

**Comment by duguyifang** [comment]
ckb挖矿类似于别的币种，不同之处在于：使用nodebridge代替blkmaker和gwmaker,负责从ckb节点获取挖矿任务和提交爆块信息，nodebridge位于btcpool/rust目录.   

### nodebridge
- 编译方法:``cd rust && cargo build --release``
- 运行方法：``./nodebridge ckb --db_url mysql://useername:password@127.0.0.1:3306/bpool_local_db --job_topic CkbRawGw --kafka_brokers "127.0.0.1:9092" --rpc_addr http://127.0.0.1:8114 --rpc_interval "2000" --solved_share_topic CkbSolvedShare``

### 注意问题
- 具体配置参照ckb/cfg文件即可
- nodebridge是联合ckb源码编译，需要注意rust/nodebridgge/Cargo.toml中:
```ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.22.0" }   ```
```ckb-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.22.0" }```
应与当前所使用的ckb节点代码版本一致
- ckb的blkmaker模块现在只有写数据库功能，该功能在nodebridge中包含，无需使用。
- ckb在主网上线之前，版本时有改动，可能涉及区块结构调整，部分调整对挖矿模块改动较大，需要根据ckb节点调整重新编译nodebridge。

**Comment by bxlkm1** [comment]
@duguyifang 多谢指导，正好在部署测试中。

**Comment by ruyichang** [comment]
请问nodebridge的日志怎么设置，谢谢
