### ISSUE TITLE
git_describe build issue

### ISSUE THREAD

**Issue by bxlkm1** [btccom/btcpool#381]
使用master的某个版本，CMAKE时会出现以下问题而停止：
-- Git describe: ckb-before-version-30-g55685459
CMake Error at CMakeLists.txt:399 (list):
  list GET given empty list
CMake Error at CMakeLists.txt:400 (list):
  list REMOVE_AT given empty list

意味着必须是tag版本才可以吗？ 里面没有对应的类似这种v2.3.2-0-g2d76329格式。

**Comment by YihaoPeng** [comment]
只需要给分支随便加一个tag，以后就都能构建了，不用一直更新tag。
后来的版本解决了这个问题，没有tag也能构建，会产生默认版本号+git hash。
```
-- CMAKE_OBJCOPY: /usr/bin/objcopy
fatal: 没有发现名称，无法描述任何东西。
-- Git describe is empty, the base version will be used.
-- It is recommended to add a tag to the current commit.
-- version string: 2.3.0-e037e20a

------------------------------- Install & Package -------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /work/x/build
```
