### ISSUE TITLE
jobmaker经常出现rawgbt diff time is more than 60, ignore it

### ISSUE THREAD

**Issue by oyangjian** [btccom/btcpool#384]
最近版本  commitid 7ef7c2a0222114a0c2c4a766fa4e914cb605396a
使用bsv老出现：JobMaker老出现这种。
======gbtmaker=====
一直显示提交了
I1025 14:37:41.195593  7615 GbtMaker.cc:296] sumbit to Kafka, msg len: 6649464
I1025 14:37:51.462519  7615 GbtMaker.cc:254] gbt height: 605854, prev_hash: 00000000000000000569e44c4c9cfe510191b7b1592fab4daf3db1f66b8b186b, coinbase_value: 1252422256, bits: 1805f13f, mintime: 1571978803, version: 536870912|0x20000000, gbthash: 5035748bb75bae9454c988533429404d8ddc46bbe71649425f96fca358270a3d
I1025 14:37:51.502260  7615 GbtMaker.cc:296] sumbit to Kafka, msg len: 6673144

=====jobmaker====
老出现接收不到信息，有时候重启机器就可以的。

I1025 14:34:16.283169 12555 JobMakerBitcoin.cc:138] consume latest rawgbt messages done
I1025 14:34:16.283442 12555 JobMaker.cc:206] wait for worker 139820336654080 exiting
rkmessage 0x7f2a60003348
W1025 14:34:16.283633 12571 JobMakerBitcoin.cc:255] RawGbt Map is empty
rkmessage 0x7f2a60003478
rkmessage 0x7f2a600035a8
rkmessage (nil)
W1025 14:34:36.283212 12571 JobMakerBitcoin.cc:255] RawGbt Map is empty
rkmessage 0x7f2a600038a0
I1025 14:34:37.842247 12571 JobMaker.cc:121] received BsvRawGbt message len: 4480728
W1025 14:34:37.851382 12571 JobMakerBitcoin.cc:168] rawgbt diff time is more than 60, ignore it
rkmessage 0x7f2a600039a8
rkmessage (nil)
W1025 14:34:56.852439 12571 JobMakerBitcoin.cc:255] RawGbt Map is empty
rkmessage 0x7f2a60307990
I1025 14:35:01.985076 12571 JobMaker.cc:121] received BsvRawGbt message len: 4531640
W1025 14:35:01.992357 12571 JobMakerBitcoin.cc:168] rawgbt diff time is more than 60, ignore it
rkmessage (nil)
W1025 14:35:16.992872 12571 JobMakerBitcoin.cc:255] RawGbt Map is empty
rkmessage 0x7f2a60003cc0
I1025 14:35:19.175925 12571 JobMaker.cc:121] received BsvRawGbt message len: 4554184
W1025 14:35:19.183820 12571 JobMakerBitcoin.cc:168] rawgbt diff time is more than 60, ignore it
rkmessage (nil)
W1025 14:35:36.183725 12571 JobMakerBitcoin.cc:255] RawGbt Map is empty
rkmessage 0x7f2a60003fe0
I1025 14:35:39.891265 12571 JobMaker.cc:121] received BsvRawGbt message len: 4571332
W1025 14:35:39.898057 12571 JobMakerBitcoin.cc:168] rawgbt diff time is more than 60, ignore it

**Comment by rocqina** [comment]
这个版本bsv才有吗，你们之前版本没有出现这个现象吗？按理说根据配置10秒从全节点rpc拉取gbt的话，不应该会在jobmaker消费的时候出现60秒以上的间隔，查下gbt拉取日志正常吗

**Comment by oyangjian** [comment]
我拉了最新的版本。jobmaker作为消费者好像取kafka数据始终有问题.gbtmaker确定是发送到kafka了。jobmaker好像有时候取不到最新的gbtmaker发过来的数据。特别是把gtbmaker重启了 kafka重启了，80%概率跑一会儿就取不到最新数据，一直是老数据 BSV环境

=========gbtmaker====
I1026 11:20:19.182330   841 GbtMaker.cc:254] gbt height: 605980, prev_hash: 000000000000000003ceba809495aeeed1cea2029f1c989f58453a36b2a5740e, coinbase_value: 1256209564, bits: 1805f562, mintime: 1572056559, version: 536870912|0x20000000, gbthash: d30f5b2d4b121d35abba85a0308767412b496cc57788b548ebd7737e97143284
I1026 11:20:19.289872   841 GbtMaker.cc:296] sumbit to Kafka, msg len: 21195764

======jobmaker=====
W1026 11:18:53.532034  1035 JobMakerBitcoin.cc:272] bestKey is the same as last one: 5205334431086443
I1026 11:20:34.150912  1035 JobMakerBitcoin.cc:581] --------producer stratum job, jobId: 6751946433378648065, height: 605980--------

**Comment by oyangjian** [comment]
> 这个版本bsv才有吗，你们之前版本没有出现这个现象吗？按理说根据配置10秒从全节点rpc拉取gbt的话，不应该会在jobmaker消费的时候出现60秒以上的间隔，查下gbt拉取日志正常吗

刚开始搭建bsv 。确定gbt是正常的。kafka配置也是按照btcpool文档上面配置的，也是没问题的。感觉jobmaker作为consumer会延迟大概1个小时才能和gbt里面的hash对上。

**Comment by rocqina** [comment]
你这个log贴的太少也看不出什么问题。如果你确定gbt和jobmaker本身没问题的话，是不是你们kafka自己搭建的有问题？你可以环境都不变，回滚一下矿池版本看看是否还是这样。最新版本我只用了btc的，没有你说的问题

**Comment by oyangjian** [comment]
> 你这个log贴的太少也看不出什么问题。如果你确定gbt和jobmaker本身没问题的话，是不是你们kafka自己搭建的有问题？你可以环境都不变，回滚一下矿池版本看看是否还是这样。最新版本我只用了btc的，没有你说的问题

出现延迟比较大一般是什么问题。kafka配置如下。
# increate message size limit
message.max.bytes=60000000
replica.fetch.max.bytes=80000000
listeners=PLAINTEXT://:9092

=======jobmaker老出现gbtmaker和jobmaker延迟秒数>=3的情况======




I1028 16:53:01.140703 16150 JobMaker.cc:121] received BsvRawGbt message len: 2831540
W1028 16:53:01.142874 16150 JobMakerBitcoin.cc:174] rawgbt diff time is too large: 5 seconds
I1028 16:53:01.166298 16150 JobMakerBitcoin.cc:239] add rawgbt, height: 606302, gbthash: 5e98d2464bbb0f0e..., gbtTime(UTC): 2019-10-28 08:52:56, isEmpty:0
I1028 16:53:01.166734 16150 JobMaker.cc:127] handleMsg returns true, new stratum job

**Comment by oyangjian** [comment]
> 你这个log贴的太少也看不出什么问题。如果你确定gbt和jobmaker本身没问题的话，是不是你们kafka自己搭建的有问题？你可以环境都不变，回滚一下矿池版本看看是否还是这样。最新版本我只用了btc的，没有你说的问题

会不会是BSV消息太大了导致的?

**Comment by YihaoPeng** [comment]
@oyangjian 确实，kafka需要额外的配置才能正常传输超大数据。BSV建议开启`lightgbt`，修改`gbtmaker.cfg`：
```
lightgbt = true;
```

gbtmaker会采用`getminingcandidate`（BSV节点应该原生支持），可以避免产生巨大的消息。

**Comment by YihaoPeng** [comment]
此外，`rawgbt diff time is more than 60`还有一个很简单的原因，那就是服务器时间不同步。如果NTP出问题，很容易出现这种情况。
