### ISSUE TITLE
最新版本联挖辅币使用联挖模块写多余数据问题。

### ISSUE THREAD

**Issue by bxlkm1** [btccom/btcpool#391]
大佬好： 
       btc为例：
使用mergeproxy模块联挖nmc，ela，用gwmaker联挖vcash，blkmaker配置把表配置放开found_aux_block_table = "found_aux_blocks_btc";
aux_chain_name = "aux";
代码里默认chain_name会提交vcash字符串。
最后提交写数据库会有多余nmc和ela的数据项插入，chain_name是aux的数据，这个是bug吗？不是bug应该怎么解决。

**Comment by duguyifang** [comment]
1，插入表中的aux爆块信息只能说明有辅币爆块，但是当前逻辑下无法确定到底是哪一种辅币爆块，只能做一个记录。然后由mergeproxy模块记录具体爆块信息。
2，当只是和nmc、rsk、vcash联合挖矿并且不使用联合挖矿代理的时候,可以修改aux_chain_name = "nmc",此时就可以将数据存到一张表里边了。

**Comment by bxlkm1** [comment]
@duguyifang 是否可以做一个标记，是否使用联合挖矿代理然，然后配置一下，是否能够在插入nmc表的地方做个判断，还是有其他方法可以做到。

**Comment by YihaoPeng** [comment]
mergedMiningProxy目前已经可以记录币种了，可以以它写入的记录为准。

让 blkmaker 写到另一个表里，然后忽略 blkmaker 写入的数据即可。
