### ISSUE TITLE
DB里的group_id是怎么用的？

### ISSUE THREAD

**Issue by JiapingLi0527** [btccom/btcpool#392]
请教大牛，mining_workers表里的group_id的作用是什么？代码里能找到把group_id从0改为-puid的逻辑，但未能找到改为0的逻辑。什么时候会改为0？谢谢！

**Comment by YihaoPeng** [comment]
pool.btc.com的web会在用户删除不活跃worker的时候把group_id改为0。如果不想使用该字段，直接忽略即可。

**Comment by JiapingLi0527** [comment]
多谢回答！
