### ISSUE TITLE
ckb testnet

### ISSUE THREAD

**Issue by xwen01** [btccom/btcpool#394]
我尝试用btcpool测试ckb testnet，启动ckb:
```
ckb init -C ckb-testnet --chain testnet --force --ba-arg 0xxxxxxxxxxx0
ckb run
```
nodebridge Cargo.toml:
```
[package]
name = "nodebridge"
version = "0.1.0"
authors = ["Hanjiang Yu <hanjiang.yu@bitmain.com>"]
edition = "2018"

[dependencies]
ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.24.0" }
ckb-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.24.0" }
chrono = "0.4"
env_logger = "0.6"
failure = "0.1"
futures = "0.1"
jsonrpc-client-transports = "13.1"
jsonrpc-core = "13.1"
jsonrpc-core-client = "13.1"
log = "0.4"
mysql_async = "0.20"
rdkafka = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tokio = "0.1"
```
测试挖了一阵子都没有爆块，请问是否哪里配置不对呢？

**Comment by duguyifang** [comment]
ckb.v0.24.0测试网在切换到v0.25.2前的网络算力是60T左右，难度相对较高，长时间不出块是正常情况，不建议使用该版本testnet进行测试，本地测试建议使用ckb的dev链进行。或者使用v0.25.2测试网络

``` shell
wget https://github.com/nervosnetwork/ckb/releases/download/v0.23.0-rc1/ckb_v0.24.0-rc1_x86_64-unknown-linux-gnu.tar.gz
tar -xvf ckb_v0.24.0-rc1_x86_64-unknown-linux-gnu.tar.gz
cd ckb_v0.24.0-rc1_x86_64-unknown-linux-gnu
./ckb -C node1 init --chain dev
​
vi node1/specs/dev.toml
--------------------
[pow]
#func = "Dummy"
func = "Eaglesong"
--------------------
​
vi node1/ckb.toml
---------------------------
 [block_assembler]
 code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"//算法相关，打开不用修改
 args = "0xxxxxxxxxxxx"//钱包相关
 hash_type = "type"
 message = "0x"//矿池信息
--------------------------
./ckb -C node1 run
```

**Comment by xwen01** [comment]
> ckb.v0.24.0测试网在切换到v0.25.2前的网络算力是60T左右，难度相对较高，长时间不出块是正常情况，不建议使用该版本testnet进行测试，本地测试建议使用ckb的dev链进行。或者使用v0.25.2测试网络
> 
> ```shell
> wget https://github.com/nervosnetwork/ckb/releases/download/v0.23.0-rc1/ckb_v0.24.0-rc1_x86_64-unknown-linux-gnu.tar.gz
> tar -xvf ckb_v0.24.0-rc1_x86_64-unknown-linux-gnu.tar.gz
> cd ckb_v0.24.0-rc1_x86_64-unknown-linux-gnu
> ./ckb -C node1 init --chain dev
> ​
> vi node1/specs/dev.toml
> --------------------
> [pow]
> #func = "Dummy"
> func = "Eaglesong"
> --------------------
> ​
> vi node1/ckb.toml
> ---------------------------
>  [block_assembler]
>  code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"//算法相关，打开不用修改
>  args = "0xxxxxxxxxxxx"//钱包相关
>  hash_type = "type"
>  message = "0x"//矿池信息
> --------------------------
> ./ckb -C node1 run
> ```

谢谢。你提供的这个链接不能下载，用v0.25.2测试网络替换掉当前的测试网络就可以了对吧？我试试看。

**Comment by xwen01** [comment]
> ckb.v0.24.0测试网在切换到v0.25.2前的网络算力是60T左右，难度相对较高，长时间不出块是正常情况，不建议使用该版本testnet进行测试，本地测试建议使用ckb的dev链进行。或者使用v0.25.2测试网络
> 
> ```shell
> wget https://github.com/nervosnetwork/ckb/releases/download/v0.23.0-rc1/ckb_v0.24.0-rc1_x86_64-unknown-linux-gnu.tar.gz
> tar -xvf ckb_v0.24.0-rc1_x86_64-unknown-linux-gnu.tar.gz
> cd ckb_v0.24.0-rc1_x86_64-unknown-linux-gnu
> ./ckb -C node1 init --chain dev
> ​
> vi node1/specs/dev.toml
> --------------------
> [pow]
> #func = "Dummy"
> func = "Eaglesong"
> --------------------
> ​
> vi node1/ckb.toml
> ---------------------------
>  [block_assembler]
>  code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"//算法相关，打开不用修改
>  args = "0xxxxxxxxxxxx"//钱包相关
>  hash_type = "type"
>  message = "0x"//矿池信息
> --------------------------
> ./ckb -C node1 run
> ```

谢谢！使用v0.25.2测试网络可以爆块。
