### ISSUE TITLE
请问现在支持ckb-0.25.2了吗？

### ISSUE THREAD

**Issue by loloxiao** [btccom/btcpool#399]
请问现在支持ckb-0.25.2了吗？

**Comment by duguyifang** [comment]
因为ckb的nodebridge本身使用的是ckb的源代码进行区块构造，对矿池有影响的因素只有pow_hash和nonce两个字段，以及ckb所使用的算法，因此在以上因素不变的情况下，只需要修改：
```https://github.com/btccom/btcpool/blob/master/rust/nodebridge/Cargo.toml#L10```
```https://github.com/btccom/btcpool/blob/master/rust/nodebridge/Cargo.toml#L11```
即可支持最新版本。

**Comment by loloxiao** [comment]
好的 我试试，谢谢
