### ISSUE TITLE
linux build -  undefined reference to `__gmpn_sub_n'

### ISSUE THREAD

**Issue by savanahmclaughlinzaz** [btccom/btcpool#4]
Hey can you advice on this one, haven't found solution elsewhere

Building CXX object CMakeFiles/unittest.dir/test/gtest/gtest-all.cc.o
[100%] Building CXX object CMakeFiles/unittest.dir/test/TestStratumServer.cc.o
[100%] Built target statshttpd
[100%] Built target nmcauxmaker
[100%] [100%] Built target gbtmaker
Built target simulator
[100%] Built target slparser
[100%] Built target poolwatcher
[100%] Built target sharelogger
..../src/.bitcoin//srcsecp256k1/../libsbitcoin//src//secp256k1bitcoinlibsecp256k1.a//secp256k1(/libsecp256k1_la.-.libssecp256k1.olibs)/:libsecp256k1.a(libsecp256k1_la-secp256k1.o ): In functionIn /` secp256k1_num_set_binfunction' :`
secp256k1_num_set_bin'/libsecp256k1.awork:/
(/btcpoollibsecp256k1_la/worksrc/-/secp256k1.obtcpool)bitcoin/:src //bitcoinsecp256k1/Insecp256k1//srcsrc //num_gmp_impl.hnum_gmp_impl.hfunction::4949 ::  `undefinedundefined  secp256k1_num_set_binreferencereference  'to:to
 /` __gmpn_set_str`work__gmpn_set_str/'btcpool
'.
/...//srcsrc/srcbitcoin///secp256k1bitcoinbitcoin//secp256k1.//.libslibs/secp256k1libsecp256k1.a/(/libsecp256k1_lalibsecp256k1.a-srcsecp256k1.o()libsecp256k1_la/-:secp256k1.o num_gmp_impl.hIn) :function:  49In` :functionsecp256k1_num_mod_inverse ' :`
secp256k1_num_mod_inverse/undefinedwork'/: 
btcpool//worksrcreference//bitcoinbtcpool //secp256k1srcto// srcbitcoin/`/__gmpn_set_strnum_gmp_impl.h':secp256k1128/:
 src.undefined/ num_gmp_impl.h.reference: 128/:to  src`/undefinedbitcoin__gmpn_gcdext/ secp256k1'/reference.
libs. .//src/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `bitcoin/secp256k1_num_mod_inverse':
/work/btcpool/src/bitcoinsecp256k1/.libsto/ libsecp256k1.a`(__gmpn_gcdextlibsecp256k1_la/-'secp256k1.o
secp256k1.)/:. /srcsrcIn/ /bitcoinfunctionnum_gmp_impl.h /`secp256k1:secp256k1_num_get_bin/'.:128
libs//:libsecp256k1.awork (/undefinedbtcpool /libsecp256k1_lasrc-referencesecp256k1.o/)bitcoin /to:secp256k1 / srcIn` /functionnum_gmp_impl.h__gmpn_gcdext: 34`':secp256k1_num_get_bin '
:undefined
 .reference/.work /to/ btcpoolsrc/`src__gmpn_get_str/'/bitcoinbitcoin
/./.secp256k1//secp256k1srcsrc///bitcoinnum_gmp_impl.h.:/34secp256k1libs/:. /undefinedlibsecp256k1.alibs(/ libsecp256k1.areference(libsecp256k1_lalibsecp256k1_la- secp256k1.oto- )secp256k1.o:` )__gmpn_get_strIn':
 .In. /functionsrc/ bitcoin /`function__gmpn_subsecp256k1'/:. libs
//`usrlibsecp256k1.a/(secp256k1_num_get_binlibsecp256k1_lainclude-/'x86_64:secp256k1.o
-)/linux:- workIngnu //functionbtcpoolgmp.h/: 2097`:__gmpn_sub 'undefined: srcreference
 //bitcointo/ usr`/secp256k1include__gmpn_sub_n/'/
x86_64src-linux-gnu/num_gmp_impl.h/gmp.h:34:2097: : undefined reference to `__gmpn_sub_nundefined reference'
 to `__gmpn_get_strcollect2: error: ld returned 1 exit status
'collect2: error: ld returned 1 exit status

../src/bitcoin/secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `__gmpn_sub':
/usr/include/x86_64-linux-gnu/gmp.h:2097: undefined reference to `__gmpn_sub_n'
collect2: error: ld returned 1 exit status
make[2]: *** [sserver] Error 1make[2]: 
*** [blkmaker] Error 1
make[1]: *** [CMakeFiles/sserver.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/blkmaker.dir/all] Error 2
make[2]: *** [jobmaker] Error 1
make[1]: *** [CMakeFiles/jobmaker.dir/all] Error 2
Linking CXX executable unittest
../src/bitcoin/secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_set_bin':
/work/btcpool/src/bitcoin/secp256k1/src/num_gmp_impl.h:49: undefined reference to `__gmpn_set_str'
../src/bitcoin/secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_mod_inverse':
/work/btcpool/src/bitcoin/secp256k1/src/num_gmp_impl.h:128: undefined reference to `__gmpn_gcdext'
../src/bitcoin/secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_get_bin':
/work/btcpool/src/bitcoin/secp256k1/src/num_gmp_impl.h:34: undefined reference to `__gmpn_get_str'
../src/bitcoin/secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `__gmpn_sub':
/usr/include/x86_64-linux-gnu/gmp.h:2097: undefined reference to `__gmpn_sub_n'
collect2: error: ld returned 1 exit status
make[2]: *** [unittest] Error 1
make[1]: *** [CMakeFiles/unittest.dir/all] Error 2
make: *** [all] Error 2

**Comment by bitkevin** [comment]
Will you give more information? What kind of OS did you use? what's your gcc version? openssl version?

**Comment by savanahmclaughlinzaz** [comment]
Bellow are specification, you may share requirements for build as well :)
###################################################################################lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
###################################################################################gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
###############################################################################
openssl version -a
OpenSSL 1.0.1f 6 Jan 2014
built on: Fri Sep 23 12:19:57 UTC 2016
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: cc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/lib/ssl"
##################################################################################

**Comment by bitkevin** [comment]
I think `ld` can't link to the `libgmp`, so try replace one line `CMakeLists.txt`: 

```
# old
set(THRID_LIBRARIES ${OPENSSL_CRYPTO_LIBRARY} ${OPENSSL_SSL_LIBRARY} ${Boost_LIBRARIES} ${LIBCONFIGPP_LIBRARY} ${LIBZMQ_LIBRARIES} ${GLOG_LIBRARIES}          ${CURL_LIBRARIES} ${KAFKA_LIBRARIES} ${LIBEVENT_LIB} ${LIBEVENT_PTHREADS_LIB} ${secp256k1_LIBRARIES} pthread mysqlclient)

# replace to this:
set(THRID_LIBRARIES ${OPENSSL_CRYPTO_LIBRARY} ${OPENSSL_SSL_LIBRARY} ${Boost_LIBRARIES} ${LIBCONFIGPP_LIBRARY} ${LIBZMQ_LIBRARIES} ${GLOG_LIBRARIES}          ${CURL_LIBRARIES} ${KAFKA_LIBRARIES} ${LIBEVENT_LIB} ${LIBEVENT_PTHREADS_LIB} ${secp256k1_LIBRARIES} pthread mysqlclient gmp)
```

**Comment by savanahmclaughlinzaz** [comment]
it seems to solve it thanks for advice :). I am closing the ticket.
