### ISSUE TITLE
ckb的jobmaker报错

### ISSUE THREAD

**Issue by loloxiao** [btccom/btcpool#403]
/work/btcpool/build/run_jobmaker/jobmaker -c /work/btcpool/build/run_jobmaker/jobmaker.cfg -l /work/btcpool/build/run_jobmaker/log_jobmaker
F1212 15:51:39.463992  6662 Utils.h:174] config section missing key: vcash_rawgw_topic
*** Check failure stack trace: ***
    @     0x7f4438db45cd  google::LogMessage::Fail()
    @     0x7f4438db6433  google::LogMessage::SendToLog()
    @     0x7f4438db415b  google::LogMessage::Flush()
    @     0x7f4438db6e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x411272  readFromSetting<>()
    @           0x41528a  createGbtJobMakerDefinition()
    @           0x415bf7  createJobMakers()
    @           0x411cb5  main
    @     0x7f44366bb830  __libc_start_main
    @           0x4135b9  _start
    @              (nil)  (unknown)
Aborted

**Comment by loloxiao** [comment]
I have fixed it .

**Comment by benslaney** [comment]
did you commit your change? i'm coming across this error now in the single-chain--server branch
