### ISSUE TITLE
After server restart the stats shows 5 times higher !!!

### ISSUE THREAD

**Issue by BobZombiE69** [btccom/btcpool#407]
Can you please help me ?
After i restarted the server , when the server booted completely in the sserver log,  all the miners rejected and jobmaker.log shows error **"rawgbt diff time is more than 60, ignore it"**

then after 5 minutes the error goes away and miners start connecting again **BUT ONLY the last 8 hours of the stats of pool  shows  5 times higher than real stats !!! ** 
the new stats (after restart ) is ok 

i tried to delete the sql data base and run "./slparser  -d 20191212" ... to 20191220
but it makes things worse ! now all the last week stats is about 5 times higher !
for example during past week the pool hash rate was 300 PH/s , but now in the stats and in the sql data base it's 1500 PH/s !!!
Also all the miners earnings show about 5 times higher !!! for example a user earned 1 BCH but now it shows 5 BCH !!!

**Comment by BobZombiE69** [comment]
more details , after  more investigations , 
i restored mysql last night backup , and i can see that the problem started from last night exactly at 00:00 UTC ,  (and recorded in the 20191220  sharelog file)  until the machine restart

**Comment by YihaoPeng** [comment]
If you are in doubt about the integrity of sharelog-xxx.bin, please start another sharelogger process, use the new kafka group id, and write the sharelog file to another directory. Then try to consum it with slparser.
