### ISSUE TITLE
EU Grin Server not accepting connections

### ISSUE THREAD

**Issue by Moebius26** [btccom/btcpool#411]
Server us-grin.ss.btc.com always gives me a "time out" when trying to connect .. no matter which port I try..
I have created a new subaccount for the US server .. and connecting to that one works fine .. 
You might want to have a look at the EU server and see if there is anything wrong with it.
Tks

**Comment by YihaoPeng** [comment]
I'm sorry for this, but here is the BTCPool mining backend developer community, we may not be able to deal with the pool.btc.com deployment issue feedback here in time.
