### ISSUE TITLE
如何计算矿工的算力

### ISSUE THREAD

**Issue by xingchenzi** [btccom/btcpool#413]
矿工提交nonce后，如何计算矿工的算力。

**Comment by langubtc** [comment]
https://github.com/btccom/btcpool/wiki/How-to-compute-a-worker's-hashrate-%7C-%E5%A6%82%E4%BD%95%E8%AE%A1%E7%AE%97%E7%9F%BF%E5%B7%A5%E7%9A%84%E5%93%88%E5%B8%8C%E9%80%9F%E7%8E%87
