### ISSUE TITLE
worker_name is not populated in bpool_local_db

### ISSUE THREAD

**Issue by attilaaf** [btccom/btcpool#414]
All of the fields in the db get populated when a client connects to sserver just fine *except the worker_name is NULL*

Does anyone know how to get the worker_name to populate into the DB?

Thanks in advance

**Comment by YihaoPeng** [comment]
statshttpd can update it, but the method it uses is not efficient enough. Consider running this independent update program:

https://github.com/btccom/btcpool/tree/master/tools/worker_update
