### ISSUE TITLE
How to calculate and payout earnings for each worker?

### ISSUE THREAD

**Issue by attilaaf** [btccom/btcpool#416]
Does anyone know how to calculate payout for earnings per each worker by their job shares?

Any information at all is appreciated.

**Comment by BobZombiE69** [comment]
if you read the docs , it says that this software use PPS mining system.
So you can see the users "earn" is already calculated and ready for you in the database.
BUT you may want to decrease it by some percent for example -4% as mining fee commission for yourself.

If you are looking for pplns and .... then you have to develop it yourself

**Comment by YihaoPeng** [comment]
see mysql table `bpool_local_db`.`stats_workers_day`, the field `earn` is what you want (unit: satoshi for BTC, ether for ETH).
