### ISSUE TITLE
sserver重新部署

### ISSUE THREAD

**Issue by shaodan** [btccom/btcpool#417]
你好，我在重启sserver的时候发现：
1. 账户算力下降，猜测是不是断线重连会造成矿机不稳定，甚至掉板
2. 重启之后大量矿机重新接入造成网络和CPU压力
3. 重连之后矿机会有很多过期的提交

所以想请教一下：
1. sserver 支持热更新部署么（保持和矿机的会话）？
2. 有没有好的负载均衡方案？

谢谢🙏

**Comment by YihaoPeng** [comment]
目前sserver支持多个进程在同一个端口监听了，所以可以先启动一个新进程，然后对旧进程执行：
```
kill -SIGTERM xxx
```
这样旧进程会关闭监听，然后一段时间丢一个连接，连接会逐渐转移到新进程上。
