### ISSUE TITLE
rejected share: Invalid version mask

### ISSUE THREAD

**Issue by DebugFuture** [btccom/btcpool#425]
客户挖bsv的时候，有些矿机提交的share被拒绝了，具体日志如下：

I0219 21:17:34.537726 11894 StratumSessionBitcoin.cc:472] authorize success, userId: xxx, wokerHashId: xxx, workerName: xxx, password: 123, versionMask: 00000000, clientAgent: bmminer-2-0-0, clientIp: xxx, chain: default

I0219 21:57:50.857401 11894 StratumMinerBitcoin.cc:434] rejected share: Invalid version mask, worker: xxx, versionMask: 40000000, share(jobId: xxx, ip: xxx, userId: xxx, workerId: xxx, time: 1582120670857/52105-05-29 20:07:37, height: 622755, blkBits: 1802868a/435349846697.561279, shareDiff: 32768, nonce: 2f9acb68, sessionId: xxx, versionMask: 40000000, status: 33/Invalid version mask)
I0219 21:57:55.717847 11894 StratumMinerBitcoin.cc:434] rejected share: Invalid version mask, worker: xxx, versionMask: 80000000, share(jobId: xxx, ip: xxx, userId: xxx, workerId: xxx, time: 1582120675717/52105-05-29 21:28:37, height: 622755, blkBits: 1802868a/435349846697.561279, shareDiff: 32768, nonce: abf8fe7c, sessionId: xxx, versionMask: 80000000, status: 33/Invalid version mask)

我们配置的version_mask是536862720，看日志是矿机修改了非法的bit，请问下这个需要改吗？btc和bsv，推荐version_mask设置为多少呢？

**Comment by YihaoPeng** [comment]
40000000
80000000
c0000000

看到这样的version mask，请让客户更新固件。客户正在使用旧版本固件，里面包含与比特币区块链不兼容的version mask。

因为比特币区块链要求version不能小于0x20000000，而version是一个有符号32位整数，所以这两个version mask将导致version变为负数，小于0，爆块成为孤块。
80000000
c0000000
