### ISSUE TITLE
sserver中新增的Management模块

### ISSUE THREAD

**Issue by onigirisan** [btccom/btcpool#427]
请问这个模块是什么用途，是消费其他服务写入的kfk消息切换chain吗？

**Comment by Apichat11oat** [comment]
Good

**Comment by YihaoPeng** [comment]
这里有个文档：
https://github.com/btccom/btcpool/wiki/%E5%9F%BA%E4%BA%8EKafka%E7%9A%84%E9%9B%86%E4%B8%AD%E5%BC%8Fsserver%E4%BF%A1%E6%81%AF%E6%9F%A5%E8%AF%A2%E6%8E%A7%E5%88%B6%E6%8E%A5%E5%8F%A3

**Comment by onigirisan** [comment]
好的谢谢
