### ISSUE TITLE
bch中getblocktemplatelight 调用问题

### ISSUE THREAD

**Issue by EthanHee** [btccom/btcpool#432]
源码src/bitcoin/GbtMaker.cc    第408行的函数如下：

> #if defined(CHAIN_TYPE_BCH) || defined(CHAIN_TYPE_BSV)
> void GbtMaker::runLightGbt() {
>   auto threadListenBitcoind =
>       std::thread(&GbtMaker::threadListenBitcoind, this);
> 
>   while (running_) {
>     std::this_thread::sleep_for(1s);
>     submitRawGbtLightMsg(true);
>   }
> 
>   if (threadListenBitcoind.joinable())
>     threadListenBitcoind.join();
> }
> 
> #endif

该函数中 调用的这个方法 GbtMaker::threadListenBitcoind 依然使用的的是 submitRawGbtMsg，不是应该使用 submitRawGbtLightMsg 方法吗？

是有别的考虑，还是有笔误呢？

**Comment by YihaoPeng** [comment]
https://github.com/btccom/btcpool/blob/c1788f795934a7896d2a71cb1e6af49e77f4d161/src/gbtmaker/GbtMakerMain.cc#L142-L150

**Comment by EthanHee** [comment]
当runLightGbt==true,且接收到zmq消息的时候,调用的仍然是submitRawGbtMsg,而不是submitRawGbtLightMsg.

**Comment by onigirisan** [comment]
@YihaoPeng zmq接受到消息的时候，调用的是原生gbt
threadListenBitcoind -> submitRawGbtMsg
https://github.com/btccom/btcpool/blob/4f93d2db454e7555978a0cc0eb2fc26986d4a9aa/src/bitcoin/GbtMaker.cc#L397-L419

**Comment by YihaoPeng** [comment]
已合并修改，感谢提供修复。
