### ISSUE TITLE
rejected share: Stale share

### ISSUE THREAD

**Issue by 857487** [btccom/btcpool#434]
```
I0327 15:32:53.404191 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000001fb19c0035cad9a1ba151316187830c5888d527bb0a529669ac16, diff: 33084, networkDiff: 13912901, by: fff.__default__
I0327 15:32:54.132182 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 0000000000005383f8d961c599616919cec63c98efe3b5b1ba235851ef50f62f, diff: 200884, networkDiff: 13912901, by: eee.__default__
I0327 15:32:55.331727 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 0000000000012e6b3ca4c2b36709dc74a1a463ff61950354794709b9b6a84a34, diff: 55475, networkDiff: 13912901, by: fff.__default__
I0327 15:32:57.409952 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000000e2369106f2aef310ab8d4f70616fd84b0170b5b533bdfe114e33, diff: 74164, networkDiff: 13912901, by: fff.__default__
I0327 15:32:57.669836 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 0000000000004167c80f1cdf0a5fb3a726b24a931ee44c1797be6356806e9a76, diff: 256507, networkDiff: 13912901, by: fff.__default__
I0327 15:32:59.701045 11859 StratumServerBitcoin.cc:625] >>>> found a new block: 000000000000011533632f6d42eb322f4215db68f1d90f31c12402c749d10e36, jobId: 6808787447913119745, userId: 6, by: fff.__default__ <<<<
I0327 15:32:59.701100 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000000011533632f6d42eb322f4215db68f1d90f31c12402c749d10e36, diff: 15493832, networkDiff: 13912901, by: fff.__default__
I0327 15:33:02.291980 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000001a0eb05816cf2c4cc7e845d65ccf9c5a7f8158267d7c1d14ae5b2, diff: 40240, networkDiff: 13912901, by: fff.__default__
I0327 15:33:02.292098 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294382/2020-03-27 07:33:02, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 82d45c1e, sessionId: 02000007, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:04.233633 11836 StratumServer.cc:371] remove expired stratum job, id: 6808786245322276865, time: 2020-03-27 07:28:04
I0327 15:33:04.295866 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000001c21f8a494878f355593a0fc4da6d7b85bec9bca2b192d8d6c25d, diff: 37271, networkDiff: 13912901, by: fff.__default__
I0327 15:33:04.296005 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294384/2020-03-27 07:33:04, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 2d53b8ea, sessionId: 02000005, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:04.944916 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 0000000000019d4050d32a8a07bf8600f51efc2075c5ef570460cd89ca123726, diff: 40597, networkDiff: 13912901, by: fff.__default__
I0327 15:33:04.945077 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294384/2020-03-27 07:33:04, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 1399da8d, sessionId: 02000012, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:05.778975 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000001845f977146d5a090e8c5de420a10322e8338f4ec06e6821d242a, diff: 43198, networkDiff: 13912901, by: fff.__default__
I0327 15:33:05.779083 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294385/2020-03-27 07:33:05, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 1f32bd01, sessionId: 0200000a, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:06.481626 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000001455e2755cdc7e274f8c15fd71ee878902ac501dfb5fe6b07d23a, diff: 51563, networkDiff: 13912901, by: fff.__default__
I0327 15:33:06.481730 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294386/2020-03-27 07:33:06, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 31a329f6, sessionId: 02000006, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:07.776194 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 0000000000001fca4276b97f3f23875e3cc31786910c1d3f80c14d383111215f, diff: 527742, networkDiff: 13912901, by: ddd.__default__
I0327 15:33:07.776386 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: ddd.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 138.197.204.233, userId: 4, workerId: 8113131267054106046, time: 1585294387/2020-03-27 07:33:07, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 131072, nonce: 16f373bd, sessionId: 02000000, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:09.665098 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 00000000000059b3a2447650dbb1b881e652fa947adb381229fa0e4c2b9298cd, diff: 187030, networkDiff: 13912901, by: fff.__default__
I0327 15:33:09.665218 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294389/2020-03-27 07:33:09, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 5cf20469, sessionId: 0200000a, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:10.719856 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 00000000000048524b50f86f34179100dba93e025c118cc743408c706a5798db, diff: 231977, networkDiff: 13912901, by: fff.__default__
I0327 15:33:10.719969 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294390/2020-03-27 07:33:10, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 0bc59bbe, sessionId: 02000007, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:10.733809 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000001f1ee4f8ed209d86d6a8c1e80935a381cd333ef4531812af4b693, diff: 33693, networkDiff: 13912901, by: fff.__default__
I0327 15:33:10.733942 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294390/2020-03-27 07:33:10, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: c4487194, sessionId: 02000009, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:11.141037 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 0000000000001992b804a9d7146dc5dae77a977b568344c6a8ebacc602ec80a7, diff: 656038, networkDiff: 13912901, by: ddd.__default__
I0327 15:33:11.141134 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: ddd.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 138.197.204.233, userId: 4, workerId: 8113131267054106046, time: 1585294391/2020-03-27 07:33:11, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 131072, nonce: 4b40c6b7, sessionId: 02000000, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:13.085903 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000001c9c85dc010fc5556672c720be0ca3052120e30e2a8337916dc0c, diff: 36648, networkDiff: 13912901, by: fff.__default__
I0327 15:33:13.085989 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 0000000000006d4cd64b17d5c637ce5e9b57b007981dd691e60520390e8f7734, diff: 153494, networkDiff: 13912901, by: fff.__default__
I0327 15:33:13.086061 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294393/2020-03-27 07:33:13, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: a571becd, sessionId: 02000005, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:13.086146 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294393/2020-03-27 07:33:13, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 5adfeb95, sessionId: 02000005, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:13.441313 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 0000000000007b7056c25c8bdc8b18925bcc3ed6713d4ba390d850761dba8477, diff: 135913, networkDiff: 13912901, by: eee.__default__
I0327 15:33:13.441416 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: eee.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 138.197.204.233, userId: 5, workerId: 8113131267054106046, time: 1585294393/2020-03-27 07:33:13, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 131072, nonce: c9a62ecf, sessionId: 02000004, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:14.436846 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 0000000000004ba3dd40500102f96cc3dcf32da692f764032da72b3984b63994, diff: 221799, networkDiff: 13912901, by: fff.__default__
I0327 15:33:14.436976 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294394/2020-03-27 07:33:14, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 05184341, sessionId: 02000009, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:18.474339 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000000a9ba94b4f4282fed53d20fdf4f43aa0fe9b9eaed48b74beb81e1, diff: 98845, networkDiff: 13912901, by: fff.__default__
I0327 15:33:18.474520 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294398/2020-03-27 07:33:18, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 546758df, sessionId: 02000012, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:19.287020 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 000000000000e510f326b81da9c0c5bf664c83f91bb7be99d9efa8b79edbaa7d, diff: 73240, networkDiff: 13912901, by: fff.__default__
I0327 15:33:19.287132 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294399/2020-03-27 07:33:19, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: 49a5dea9, sessionId: 02000009, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:19.289775 11859 StratumServerBitcoin.cc:635] high diff share, blkhash: 00000000000153d3af3ea97c54f35743003148e4d25e5d9e46716e2a83266af2, diff: 49369, networkDiff: 13912901, by: fff.__default__
I0327 15:33:19.289829 11836 StratumMinerBitcoin.cc:395] rejected share: Stale share, worker: fff.__default__, versionMask: 00000000, share(jobId: 6808787447913119745, ip: 91.210.105.199, userId: 6, workerId: 8113131267054106046, time: 1585294399/2020-03-27 07:33:19, height: 1671201, blkBits: 1a0134b3/13912901.293988, shareDiff: 32768, nonce: e8f86f2c, sessionId: 02000012, versionMask: 00000000, status: 37/Stale share)
I0327 15:33:21.252468 11836 StratumServer.cc:371] remove expired stratum job, id: 6808786318336720897, time: 2020-03-27 07:28:21
I0327 15:33:21.252511 11836 StratumServer.cc:371] remove expired stratum job, id: 6808786318336721153, time: 2020-03-27 07:28:21
I0327 15:33:21.252524 11836 StratumServer.cc:371] remove expired stratum job, id: 6808786318336721409, time: 2020-03-27 07:28:21

```

**Comment by 857487** [comment]
#
# block maker cfg
#
# @since 2016-07
# @copyright btc.com
#

# submit block hex
bitcoinds = (
{
  rpc_addr    = "http://192.168.1.10:18332";
  rpc_userpwd = "xxx:xxx";  # username:password
}
# ,
# {
# rpc_addr    = "http://10.0.0.1:8332";
# rpc_userpwd = "bitcoinrpc:xxxxxxxxxxxxxxxxxxxxxxxxxx";  # username:password
# }
);

kafka = {
  brokers = "127.0.0.1:9092"; # "10.0.0.1:9092,10.0.0.2:9092,..."
};

#
# pool mysql db: table.found_blocks
#
pooldb = {
  host = "127.0.0.1";
  port = 3306;
  username = "root";
  password = "xxx";
  dbname = "bpool_local_db";
};

blk_makers = (
  {
    chain_type = "BTC";
    enabled = true;
    nodes = (
      {
        rpc_addr = "http://192.168.1.10:18332";
        rpc_userpwd = "xxx:xxx";
      }
    );
    rawgbt_topic = "RawGbt";
    solved_share_topic = "SolvedShare";
    auxpow_solved_share_topic = "AuxPowSolvedShare";
    rsk_solved_share_topic = "RskSolvedShare";
    job_topic = "BtcJob";
    found_aux_block_table = "found_nmc_blocks";
  },
  {
    chain_type = "ETH"; //blockchain short name
    enabled = false; //enable worker
    nodes = (
      {
        rpc_addr = "http://127.0.0.1:8545";
        rpc_userpwd = "user:pass";
      }
    );
    #solved share topic
    solved_share_topic = "EthSolvedShare";

    # The hard fork Constantinople of Ethereum mainnet
    constantinople_height = 7280000;
  },
  {
    chain_type = "SIA"; //blockchain short name
    enabled = false; //enable worker
    nodes = (
      {
        rpc_addr = "http://127.0.0.1:9980/miner/header";
        rpc_userpwd = "user:pass";
      }
    );
    #solved share topic
    solved_share_topic = "SiaSolvedShare";
  },
  {
    chain_type = "BTM"; //blockchain short name
    enabled = false; //enable worker
    nodes = (
      {
        rpc_addr = "http://127.0.0.1:9888/submit-work";
        rpc_userpwd = "user:pass";
      }
    );
    #solved share topic
    solved_share_topic = "BytomSolvedShare";
  }
);

**Comment by 857487** [comment]
#
# job maker cfg
#
# @since 2016-06
# @copyright btc.com
#

job_workers = (
  {
    id = 1;
    chain_type = "BTC";
    enabled = true;

    testnet = true; // is using testnet3

    # payout address
    # the private key of my2dxGb5jz43ktwGxg2doUaEb9WhZ9PQ7K is cQAiutBRMq4wwC9JHeANQLttogZ2EXw9AgnGXMq5S3SAMmbX2oLd
    payout_address = "xxx";
    # coinbase info with location ID (https://github.com/btccom/btcpool/issues/36)
    coinbase_info = "region1/Project BTCPool/";

    # block version, default is 0 means use the version which returned by bitcoind
    # or you can specify the version you want to signal.
    # more info: https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki
    # Example: 
    #  0                     : use bitcoind block version,
    #  536870912(0x20000000) : bip9 support (with empty version bits)
    #  536870914(0x20000002) : bip141(segwit), bit 1
    # 
    block_version = 0;

    rawgbt_topic = "RawGbt";

    auxpow_gw_topic = "AuxPowBlock"; // kafka topic of merge mining auxpow work
    rsk_rawgw_topic = "RskRawGw"; // kafka topic of RSK merge mining
	vcash_rawgw_topic = "VcashRawGw";

    job_topic = "BtcJob";

    job_interval = 20; // send stratum job interval (seconds)
    max_job_delay = 20; // max job dealy (seconds)

    # max non-empty gbt life cycle time (seconds)
    gbt_life_time = 90;

    # max empty gbt life cycle time seconds
    # CAUTION: the value SHOULD >= 10. If non-empty job not come in 10 seconds, 
    #          jobmaker will always make a previous height job until its arrival 
    empty_gbt_life_time = 15;

    # policy used to determine the pace of merge mining jobs to be sent.
    # 0: merge mining `getwork` does not trigger job updates (RSK and Namecoin).
    # 1: update job when the `notify` flag in RSK `getwork` is true or the block height in Namecoin `getwork` higher than before.
    # 2: update job when the current block hash of a merge mining `getwork` is different from before (RSK and Namecoin).
    merged_mining_notify = 1; # (1 is recommended and default)

    zookeeper_lock_path = "/locks/jobmaker_btc";
    file_last_job_time = "/work/btcpool/build/run_jobmaker/btc_lastjobtime.txt";
  },
  {
    id = 1;
    chain_type = "ETH";
    chain_name = "FOUNDATION"; // CLASSIC (ETC Main Network) or FOUNDATION (ETH Main Network)
    enabled = false;

    rawgw_topic = "EthRawGw";
    job_topic = "EthJob";

    job_interval = 20; // send stratum job interval (seconds)
    max_job_delay = 20; // max job dealy (seconds)
    work_life_time = 60; // max getWork life cycle time (seconds)

    zookeeper_lock_path = "/locks/jobmaker_eth";
    file_last_job_time = "/work/btcpool/build/run_jobmaker/eth_lastjobtime.txt";
  },
  {
    id = 1;
    chain_type = "BTM";
    enabled = false;

    rawgw_topic = "BytomRawGw";
    job_topic = "BytomJob";

    job_interval = 20; // send stratum job interval (seconds)
    max_job_delay = 20; // max job dealy (seconds)
    work_life_time = 90; // max getWork life cycle time (seconds)

    zookeeper_lock_path = "/locks/jobmaker_bytom";
    file_last_job_time = "/work/btcpool/build/run_jobmaker/bytom_lastjobtime.txt";
  },
  {
    id = 1;
    chain_type = "SIA";
    enabled = false;

    rawgw_topic = "SiaRawGw";
    job_topic = "SiaJob";

    job_interval = 30; // send stratum job interval (seconds)
    max_job_delay = 60; // max job dealy (seconds)
    work_life_time = 90; // max getWork life cycle time (seconds)

    zookeeper_lock_path = "/locks/jobmaker_sia";
    file_last_job_time = "/work/btcpool/build/run_jobmaker/sia_lastjobtime.txt";
  }
);

kafka = {
  brokers = "127.0.0.1:9092"; # "10.0.0.1:9092,10.0.0.2:9092,..."
};

zookeeper = {
  brokers = "127.0.0.1:2181"; # "10.0.0.1:2181,10.0.0.2:2181,..."
};

**Comment by 857487** [comment]
#
# gbt maker cfg
#
# @since 2016-06
# @copyright btc.com
#

gbtmaker = {
  # rpc call interval seconds
  rpcinterval = 5;

  # check zmq when startup
  is_check_zmq = true;

  rawgbt_topic = "RawGbt";

  # use RPC `getblocktemplatelight`, only for bch
  lightgbt = false; # if unspecified, default false
};

bitcoind = {
  # bitcoind MUST with zmq options: -zmqpubhashblock, -zmqpubhashtx
  # '-zmqpubhashtx' will use to check zmq is working when startup gbtmaker
  zmq_addr = "tcp://192.168.1.10:15101";
  # reconnect if no new messages are received after the following number of seconds
  zmq_timeout = 1200;

  # rpc settings
  rpc_addr    = "http://192.168.1.10:18332";
  rpc_userpwd = "xxx:xxx";  # username:password
};

kafka = {
  brokers = "127.0.0.1:9092"; # "10.0.0.1:9092,10.0.0.2:9092,..."
};

**Comment by 857487** [comment]
#
# stratum server cfg
#
# @since 2016-06
# @copyright btc.com
#

# is using testnet3
testnet = true;

kafka = {
  brokers = "127.0.0.1:9092"; # "10.0.0.1:9092,10.0.0.2:9092,..."
};

zookeeper = {
  brokers = "127.0.0.1:2181"; # "10.0.0.1:2181,10.0.0.2:2181,..."
};

sserver = {
  # serverType
  type = "BTC";
  
  ip = "0.0.0.0";
  port = 3333;

  # should be global unique, range: [1, 255]
  # If the id is 0, try to automatically assign one from zookeeper.
  id = 0;
  # The lock path used when automatically assigning an id
  zookeeper_lock_path = "/locks/sserver_btc";

  # write last mining notify job send time to file, for monitor
  file_last_notify_time = "./sserver_lastnotifytime.txt";

  # the connection will be closed if the miner does not send any message
  # to the sserver within the specified seconds.
  tcp_read_timeout = 600;

  # how many seconds between two share submit
  share_avg_seconds = 10;

  # the lifetime of a job
  # It should not be too short, otherwise the valid share will be rejected due to job not found.
  max_job_lifetime = 300;

  # the job interval
  # sserver will push latest job if there are no new jobs for this interval
  mining_notify_interval = 30;

  # default difficulty (hex)
  default_difficulty = "4096";

  # max difficulty (hex)
  max_difficulty = "17179869184";

  # min difficulty (hex)
  min_difficulty = "4096";

  # Adjust difficulty once every N second
  diff_adjust_period = 900;

  # When exiting, the connection will be closed gradually within the specified time.
  # Set to 0 to disable this feature.
  shutdown_grace_period = 3600;

  nicehash = {
    # Set to true if you want to force minimal difficulty for whole sserver
    forced = false;

    # Fallback value when ZooKeeper is not available
    min_difficulty = "10000";

    # Read NiceHash minimal difficulty from this ZooKeeper node
    min_difficulty_zookeeper_path = "/nicehash/sha256/min_difficulty"
  };
  
  #
  # version_mask, uint32_t
  #          2(0x00000002) : allow client change bit 1
  #         16(0x00000010) : allow client change bit 4
  #  536862720(0x1fffe000) : allow client change bit 13 to 28
  #
  #  version_mask = 0;
  #  version_mask = 16;
  #  version_mask = 536862720; // recommended, BIP9 security
  #  ...
  #
  version_mask = 536862720;

  # it could be 4 ~ 8
  # it should be 4 if you want proxy stratum jobs with poolwatcher(proxy).cfg
  extra_nonce2_size = 8;

  # Send ShareBitcoinBytesV1 to share_topic to keep compatibility with legacy statshttpd/sharelogger.
  use_share_v1 = false;
  
  # topics
  job_topic = "BtcJob";
  share_topic = "BtcShare";
  solved_share_topic = "BtcSolvedShare";
  auxpow_solved_share_topic = "AuxSolvedShare"; # auxpow (eg. Namecoin) solved share topic
  rsk_solved_share_topic = "RskSolvedShare";
  common_events_topic = "BtcCommonEvents";

  ########################## dev options #########################

  # if enable simulator, all share will be accepted. for testing
  enable_simulator = false;

  # if enable it, all share will make block and submit. for testing
  enable_submit_invalid_block = false;

  # if enable, difficulty sent to miners is always dev_fixed_difficulty. for development
  enable_dev_mode = false;

  # difficulty to send to miners. for development
  dev_fixed_difficulty = 0.005;
  
  ###################### end of dev options ######################
};

users = {
  #
  # https://example.com/get_user_id_list?last_id=0
  # {"err_no":0,"err_msg":null,"data":{"jack":1,"terry":2}}
  #
  # There is a demo: https://github.com/btccom/btcpool/issues/16#issuecomment-278245381
  #
  list_id_api_url = "http://192.168.1.20/apidemo.php";

  # Make the user name case insensitive
  case_insensitive = true;

  # Enable single user mode.
  # In this mode, all sub-accounts connected to the sserver will become the worker name prefix for a specified user.
  # Example, a worker "user2.11x20" will become "user1.user2.11x20".
  #single_user_mode = false;
  #single_user_name = "user1";
  #single_user_puid = 1;
};

prometheus = {
  # whether prometheus exporter is enabled
  enabled = true
  # address for prometheus exporter to bind
  address = "0.0.0.0"
  # port for prometheus exporter to bind
  port = 9100
  # path of the prometheus exporter url
  path = "/metrics"
};

log = {
  # hide "client connect" log with the prefix
  #hide_ip_prefix = "100.122.";
};

management = {
  enabled = true; # default: true

  kafka_brokers = "127.0.0.1:9092"; # "10.0.0.1:9092,10.0.0.2:9092,..."
  controller_topic = "BtcManController";
  processor_topic = "BtcManProcessor";

  auto_switch_chain = false;
};

**Comment by 857487** [comment]
错误日志和配置以上，用的是0.16.3的钱包编译的，搜索了以往的答案，并没有解决这个问题，请开发者解答一下，谢谢！

**Comment by 857487** [comment]
![image](https://user-images.githubusercontent.com/39867693/77844092-0049d480-71d6-11ea-9754-464c2d382d83.png)
这是打开模拟器以后用ccminer工作的日志

**Comment by YihaoPeng** [comment]
爆块后，如果还没有收到下一个块的任务，当前任务就会一直stale。仅针对爆块sserver。
