### ISSUE TITLE
bash: ./gwmaker: No such file or directory

### ISSUE THREAD

**Issue by lilwil** [btccom/btcpool#436]
Ubuntu16.04.1 64位
提示这个错误，
bash: ./gwmaker: No such file or directory
之前在执行
 make -j$(nproc)
出现
 error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

**Comment by YihaoPeng** [comment]
文档过时，实际上我们仅在 Ubuntu 18.04 中进行测试。
你还可以在docker中进行构建
https://github.com/btccom/btcpool/tree/master/docker/btcpool/deploy
