### ISSUE TITLE
BSV和NMC,ELA,UNO联合挖矿只爆块BSV

### ISSUE THREAD

**Issue by gjgjgjgj** [btccom/btcpool#446]
你好，BSV和NMC,ELA,UNO联合挖矿时，只爆块BSV，辅链币都不爆块。之前只联合挖矿NMC不使用mergedMiningProxy时可正确爆块BSV和NMC，请问
·
    1. mergedMiningProxy只有RPC监听端口，那么nmcauxmaker的is_check_zmq，zmq_addr填什么？(我目前 is_check_zmq = false, zmq_addr = "tcp://127.0.0.1:8999" 和 rpc_addr 相同内容)
·
    2. mergedMiningProxy有每个链的paytoaddress填写了，那么nmcauxmaker的payout_address填什么？（我目前填写了NMC的一个地址）

谢谢大牛帮忙解答一下。

**Comment by linzhm** [comment]
呃，BSV 没有联合挖矿项目的。

**Comment by gjgjgjgj** [comment]
> 呃，BSV 没有联合挖矿项目的。

@linzhm 
我看https://github.com/btccom/btcpool/blob/master/docs/MergedMining.md 中的如下表格以为BSV可以和NMC，ELA，UNO联合挖矿。所以当前项目只支持NMC，ELA，UNO和BTC联合挖矿吗？

Blockchain | Parent Chain Algorithm | Frequently-Used Parent Chain
-- | -- | --
NameCoin | SHA256 | BTC, BCH, UBTC, BSV
ELastos | SHA256 | BTC, BCH, UBTC, BSV
Unobtanium | SHA256 | BTC, BCH, UBTC, BSV
Dogecoin | Scrypt | LTC

**Comment by YihaoPeng** [comment]
NMC的爆块难度接近于BTC，比BSV高得多。所以挖BSV不爆NMC很正常啊。

如果很久都没有辅链爆块，可以检查blkmaker有没有辅链任务提交。如果没有，检查你的爆块是否达到了任意辅链的爆块难度。正常情况下，只要难度达到辅链中难度最小的那个链的爆块难度，blkmaker就会有联合挖矿提交。

is_check_zmq 填什么？我建议填 false，因为 true 会导致重启时阻塞。
zmq_addr 填什么？因为 mergedMiningProxy 还没有实现 ZMQ 消息代理，所以我建议你填写价值最高的那个币种的 ZMQ 地址。这样在它爆块时，你可以及时更新任务。

**Comment by YihaoPeng** [comment]
考虑为 mergedMiningProxy 实现 ZMQ 消息代理

**Comment by gjgjgjgj** [comment]
@YihaoPeng 感谢解答。
