### ISSUE TITLE
getnetworkinfo interface are not found in eth rpc, what can i do? Please

### ISSUE THREAD

**Issue by chunqizhi** [btccom/btcpool#459]
Log file created at: 2020/08/25 16:02:59
Running on machine: localhost.localdomain
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0825 16:02:59.827081  4046 GbtMakerMain.cc:98] BTC gbtmaker version 2.3.0-d16a45f
I0825 16:02:59.828033  4046 Kafka.cc:368] producer librdkafka version: 0.9.1
I0825 16:02:59.828178  4046 Kafka.cc:442] add brokers: 127.0.0.1:9092
I0825 16:02:59.828214  4046 Kafka.cc:449] create topic handle: BtcRawGbt
I0825 16:02:59.883919  4046 BitcoinUtils.cc:265] getnetworkinfo: {"jsonrpc":"2.0","id":"1","error":{"code":-32601,"message":"the method getnetworkinfo does not exist/is not available"}}
E0825 16:02:59.883958  4046 BitcoinUtils.cc:277] getnetworkinfo missing some fields
I0825 16:02:59.907829  4046 BitcoinUtils.cc:300] getinfo: {"jsonrpc":"2.0","id":"1","error":{"code":-32601,"message":"the method getinfo does not exist/is not available"}}
E0825 16:02:59.907855  4046 BitcoinUtils.cc:312] getinfo missing some fields
F0825 16:02:59.907869  4046 GbtMakerMain.cc:139] gbtmaker init failure

**Comment by duguyifang** [comment]
在eth中，是使用gwmaker或者nodebridge从节点获取任务的。
nodebridge需要配合我们打过patch的eth源码https://github.com/btccom/go-ethereum使用。

**Comment by chunqizhi** [comment]
> gwmaker

Nice! Thanks!
