### ISSUE TITLE
关于子账户实时算力的问题请教

### ISSUE THREAD

**Issue by learsu** [btccom/btcpool#46]
请问用什么方法计算子账户的实时算力、24小时算力和矿池的总算力？谢谢先

**Comment by YihaoPeng** [comment]
> `^`为乘方运算符
* 1 share = 2^32次哈希运算
* 一段时间内的有效算力 (hash/s) = share_accept * 2^32 (hash次数) / 经过的时间 (s)

**Comment by learsu** [comment]
非常感谢
