### ISSUE TITLE
本地测试，爆块了，但kafka未记录

### ISSUE THREAD

**Issue by BigPingge** [btccom/btcpool#463]
1 ![image](https://user-images.githubusercontent.com/40760279/91527388-47c8be00-e938-11ea-8da8-1213adcfbecc.png)
这是我sserver的日志，已经计算成功了，发送slovedshare也已经成功。但是我用./kafka-console-consumer.sh --zookeeper=127.0.0.1:2181 --topic=EthSolvedShare查看的时候却没有任何信息。
2.启动statshttpd，读不到kafka的内容。同样用./kafka-console-consumer.sh --zookeeper=127.0.0.1:2181 --topic=EthShareLog查看，却可以读到里面的内容.
希望有大佬指点一下

**Comment by duguyifang** [comment]
你可以使用以下配置文件进行测试：
jobmaker.cfg
```
job_workers = (
  {
    id = 1;
    chain_type = "ETH";
    chain_name = "FOUNDATION"; // CLASSIC (ETC Main Network) or FOUNDATION (ETH Main Network)
    enabled = true;

    rawgw_topic = "EthRawGw";
    job_topic = "EthJob";

    job_interval = 8; // send stratum job interval (seconds)
    max_job_delay = 20; // max job dealy (seconds)
    work_life_time = 60; // max getWork life cycle time (seconds)

    zookeeper_lock_path = "/locks/jobmaker_eth";
    file_last_job_time = "/work/btcpool.etc/build/run_jobmaker/etc_lastjobtime.txt";
  }
);

kafka = {
  brokers = "127.0.0.1:9092";
};

zookeeper = {
  brokers = "127.0.0.1:2181";
};
```
blkmaker.cfg
```
#
# block maker cfg
#
# @since 2016-07
# @copyright btc.com
#

kafka = {
  brokers = "127.0.0.1:9092";
};

#
# pool mysql db: table.found_blocks
#
pooldb = {
  host = "127.0.0.1";
  port = 3306;
  username = "root";
  password = "root";
  dbname = "bpool_local_db";
};

blk_makers = (
  {
    chain_type = "ETH"; //blockchain short name
    enabled = true; //enable worker
    nodes = (
      {
        rpc_addr = "http://127.0.0.1:8545/";
        rpc_userpwd = "";
      }
   );
    #solved share topic
    solved_share_topic = "EthSolvedShare";
  }
);
```
simulator.cfg
```
#
# miners simulator cfg
#
# @since 2016-07
# @copyright btc.com
#

simulator = {
  # how many connects will connect to the stratum server
  number_clients = 5;

  # stratum sever host & port
  ss_ip = "localhost";
  ss_port = 3333;
  enable_tls = false;

  # miner's username
  username = "aaa";

  # miner's name prefix
  # so the full name will be: <username>.<minername_prefix>-<increase_ID>
  minername_prefix = "simulator";

  # miner's password
  # used to set difficulty with "d=xxx" and/or "md=xxx"
  passwd = "";

  type = "ETH";
};

```
sserver.cfg
```
//
// stratum server cfg
//
// @since 2016-06
// @copyright btc.com
//

# is using testnet3
testnet = false;
zookeeper = {
  brokers = "127.0.0.1:2181";
};

kafka = {
  brokers = "127.0.0.1:9092";
};

sserver = {
  # serverType
  type = "ETH";

  ip = "0.0.0.0";
  port = 3333;

  // should be global unique, range: [1, 255]
  id = 1;

  // write last mining notify job send time to file, for monitor
  file_last_notify_time = "/work/btcpool/build/run_sserver/sserver_lastnotifytime.txt";

  # the connection will be closed if the miner does not send any message
  # to the sserver within the specified seconds.
  tcp_read_timeout = 600;
  
  // how many seconds between two share submit
  share_avg_seconds = 15;

  # the lifetime of a job
  # It should not be too short, otherwise the valid share will be rejected due to job not found.
  max_job_lifetime = 300;  // seconds

  #default difficulty
  default_difficulty = "80";

  #max difficulty
  max_difficulty = "4000000000000000";

  #min difficulty
  min_difficulty = "1";

  # Adjust difficulty once every N second
  diff_adjust_period = 300;

  nicehash = {
    # Set to true if you want to force minimal difficulty for whole sserver
    forced = false;

    # Fallback value when ZooKeeper is not available
    min_difficulty = "200000000";

    # Read NiceHash minimal difficulty from this ZooKeeper node
    min_difficulty_zookeeper_path = "/nicehash/daggerhashimoto/min_difficulty"
  };

  # kafaka consumer topic
  job_topic = "EthJob";

  #share topic
  share_topic = "EthShareLog";
  
  #solved share topic
  solved_share_topic = "EthSolvedShare";

  # common events topic
  # example: miner connected, miner disconnected, ...
  common_events_topic = "EthCommonEvents";

  # Whether stale shares will be accepted
  accept_stale = true;

  ########################## dev options #########################

  # if enable simulator, all share will be accepted. for testing
  enable_simulator = false;

  # if enable it, all share will make block and submit. for testing
  enable_submit_invalid_block = false;

  # if enable, difficulty sent to miners is always dev_fixed_difficulty. for development
  enable_dev_mode = false;

  # difficulty to send to miners. for development
  dev_fixed_difficulty = 80000000.0;

  ###################### end of dev options ######################
};

users = {
  //
  // https://example.com/get_user_id_list?last_id=0
  // {"err_no":0,"err_msg":null,"data":{"jack":1,"terry":2}}
  //
  list_id_api_url = "http://localhost:8000/get-user-list.php";

  # Make the user name case insensitive
  case_insensitive = true;

  # remove the suffix appended to the user name
  # example: tiger_eth -> tiger, aaa_bbb_ccc -> aaa_bbb
  strip_user_suffix = true;
  user_suffix_separator = "_";
};
management = {
  enabled = true; # default: true

  kafka_brokers = "127.0.0.1:9092"; # "10.0.0.1:9092,10.0.0.2:9092,..."
  controller_topic = "BtcManController";
  processor_topic = "BtcManProcessor";

  auto_switch_chain = false;
};
prometheus = {
  # whether prometheus exporter is enabled
  enabled = true
  # address for prometheus exporter to bind
  address = "0.0.0.0"
  # port for prometheus exporter to bind
  port = 8080
  # path of the prometheus exporter url
  path = "/metrics"
};
```
测试爆块的话可以开启这几个测试开关：
```
  ########################## dev options #########################

  # if enable simulator, all share will be accepted. for testing
  enable_simulator = false;

  # if enable it, all share will make block and submit. for testing
  enable_submit_invalid_block = false;

  # if enable, difficulty sent to miners is always dev_fixed_difficulty. for development
  enable_dev_mode = false;

  # difficulty to send to miners. for development
  dev_fixed_difficulty = 80000000.0;

  ###################### end of dev options ######################
```
对于kafka的话主要保证各组件topic名的对应关系。

**Comment by BigPingge** [comment]
> 你可以使用以下配置文件进行测试：
> jobmaker.cfg
> 
> ```
> job_workers = (
>   {
>     id = 1;
>     chain_type = "ETH";
>     chain_name = "FOUNDATION"; // CLASSIC (ETC Main Network) or FOUNDATION (ETH Main Network)
>     enabled = true;
> 
>     rawgw_topic = "EthRawGw";
>     job_topic = "EthJob";
> 
>     job_interval = 8; // send stratum job interval (seconds)
>     max_job_delay = 20; // max job dealy (seconds)
>     work_life_time = 60; // max getWork life cycle time (seconds)
> 
>     zookeeper_lock_path = "/locks/jobmaker_eth";
>     file_last_job_time = "/work/btcpool.etc/build/run_jobmaker/etc_lastjobtime.txt";
>   }
> );
> 
> kafka = {
>   brokers = "127.0.0.1:9092";
> };
> 
> zookeeper = {
>   brokers = "127.0.0.1:2181";
> };
> ```
> 
> blkmaker.cfg
> 
> ```
> #
> # block maker cfg
> #
> # @since 2016-07
> # @copyright btc.com
> #
> 
> kafka = {
>   brokers = "127.0.0.1:9092";
> };
> 
> #
> # pool mysql db: table.found_blocks
> #
> pooldb = {
>   host = "127.0.0.1";
>   port = 3306;
>   username = "root";
>   password = "root";
>   dbname = "bpool_local_db";
> };
> 
> blk_makers = (
>   {
>     chain_type = "ETH"; //blockchain short name
>     enabled = true; //enable worker
>     nodes = (
>       {
>         rpc_addr = "http://127.0.0.1:8545/";
>         rpc_userpwd = "";
>       }
>    );
>     #solved share topic
>     solved_share_topic = "EthSolvedShare";
>   }
> );
> ```
> 
> 仿真器
> 
> ```
> #
> # miners simulator cfg
> #
> # @since 2016-07
> # @copyright btc.com
> #
> 
> simulator = {
>   # how many connects will connect to the stratum server
>   number_clients = 5;
> 
>   # stratum sever host & port
>   ss_ip = "localhost";
>   ss_port = 3333;
>   enable_tls = false;
> 
>   # miner's username
>   username = "aaa";
> 
>   # miner's name prefix
>   # so the full name will be: <username>.<minername_prefix>-<increase_ID>
>   minername_prefix = "simulator";
> 
>   # miner's password
>   # used to set difficulty with "d=xxx" and/or "md=xxx"
>   passwd = "";
> 
>   type = "ETH";
> };
> ```
> 
> sserver.cfg
> 
> ```
> //
> // stratum server cfg
> //
> // @since 2016-06
> // @copyright btc.com
> //
> 
> # is using testnet3
> testnet = false;
> zookeeper = {
>   brokers = "127.0.0.1:2181";
> };
> 
> kafka = {
>   brokers = "127.0.0.1:9092";
> };
> 
> sserver = {
>   # serverType
>   type = "ETH";
> 
>   ip = "0.0.0.0";
>   port = 3333;
> 
>   // should be global unique, range: [1, 255]
>   id = 1;
> 
>   // write last mining notify job send time to file, for monitor
>   file_last_notify_time = "/work/btcpool/build/run_sserver/sserver_lastnotifytime.txt";
> 
>   # the connection will be closed if the miner does not send any message
>   # to the sserver within the specified seconds.
>   tcp_read_timeout = 600;
>   
>   // how many seconds between two share submit
>   share_avg_seconds = 15;
> 
>   # the lifetime of a job
>   # It should not be too short, otherwise the valid share will be rejected due to job not found.
>   max_job_lifetime = 300;  // seconds
> 
>   #default difficulty
>   default_difficulty = "80";
> 
>   #max difficulty
>   max_difficulty = "4000000000000000";
> 
>   #min difficulty
>   min_difficulty = "1";
> 
>   # Adjust difficulty once every N second
>   diff_adjust_period = 300;
> 
>   nicehash = {
>     # Set to true if you want to force minimal difficulty for whole sserver
>     forced = false;
> 
>     # Fallback value when ZooKeeper is not available
>     min_difficulty = "200000000";
> 
>     # Read NiceHash minimal difficulty from this ZooKeeper node
>     min_difficulty_zookeeper_path = "/nicehash/daggerhashimoto/min_difficulty"
>   };
> 
>   # kafaka consumer topic
>   job_topic = "EthJob";
> 
>   #share topic
>   share_topic = "EthShareLog";
>   
>   #solved share topic
>   solved_share_topic = "EthSolvedShare";
> 
>   # common events topic
>   # example: miner connected, miner disconnected, ...
>   common_events_topic = "EthCommonEvents";
> 
>   # Whether stale shares will be accepted
>   accept_stale = true;
> 
>   ########################## dev options #########################
> 
>   # if enable simulator, all share will be accepted. for testing
>   enable_simulator = false;
> 
>   # if enable it, all share will make block and submit. for testing
>   enable_submit_invalid_block = false;
> 
>   # if enable, difficulty sent to miners is always dev_fixed_difficulty. for development
>   enable_dev_mode = false;
> 
>   # difficulty to send to miners. for development
>   dev_fixed_difficulty = 80000000.0;
> 
>   ###################### end of dev options ######################
> };
> 
> users = {
>   //
>   // https://example.com/get_user_id_list?last_id=0
>   // {"err_no":0,"err_msg":null,"data":{"jack":1,"terry":2}}
>   //
>   list_id_api_url = "http://localhost:8000/get-user-list.php";
> 
>   # Make the user name case insensitive
>   case_insensitive = true;
> 
>   # remove the suffix appended to the user name
>   # example: tiger_eth -> tiger, aaa_bbb_ccc -> aaa_bbb
>   strip_user_suffix = true;
>   user_suffix_separator = "_";
> };
> management = {
>   enabled = true; # default: true
> 
>   kafka_brokers = "127.0.0.1:9092"; # "10.0.0.1:9092,10.0.0.2:9092,..."
>   controller_topic = "BtcManController";
>   processor_topic = "BtcManProcessor";
> 
>   auto_switch_chain = false;
> };
> prometheus = {
>   # whether prometheus exporter is enabled
>   enabled = true
>   # address for prometheus exporter to bind
>   address = "0.0.0.0"
>   # port for prometheus exporter to bind
>   port = 8080
>   # path of the prometheus exporter url
>   path = "/metrics"
> };
> ```
> 
> 测试爆块的话可以开启这几个测试开关：
> 
> ```
>   ########################## dev options #########################
> 
>   # if enable simulator, all share will be accepted. for testing
>   enable_simulator = false;
> 
>   # if enable it, all share will make block and submit. for testing
>   enable_submit_invalid_block = false;
> 
>   # if enable, difficulty sent to miners is always dev_fixed_difficulty. for development
>   enable_dev_mode = false;
> 
>   # difficulty to send to miners. for development
>   dev_fixed_difficulty = 80000000.0;
> 
>   ###################### end of dev options ######################
> ```
> 
> 对于kafka的话主要保证各组件主题名的对应关系。

非常感谢，问题一已经解决了。但是那第二个问题，我kafka里面有数据，ShareLogger还是读不到。能加我qq1095205711详谈一下吗
