### ISSUE TITLE
关于表found_blocks中的height字段出现重复的

### ISSUE THREAD

**Issue by BigPingge** [btccom/btcpool#467]
hegiht表示挖到的区块的高度。矿机运行了一段时间，发现表中记录如下：
![image](https://user-images.githubusercontent.com/40760279/92438534-98afa080-f1db-11ea-804a-dd0a0cc1a299.png)
理论上记录的区块只会出现一次啊，如果出现了重复，要通过什么方法查看这个块是哪个矿工爆的

**Comment by de1acr0ix** [comment]
出块时间短的币种（比如这个例子里面的 ETH）有超过一个矿工在差不多相同时刻爆块的可能性还是有的，甚至同一个矿工连续爆同一高度的块也是有可能的（矿机是并行执行大量碰撞所以很可能有两个 nouce 都符合难度要求）。你这个 ETH 的块高如此之小，显然是一个自行设定的私有测试链，那么它的难度通常就很低，这种可能就更大了，这属于正常现象。

**Comment by BigPingge** [comment]
> 出块时间短的币种（一个这个例子里面的ETH）有超过一个矿工在差不多相同时刻爆块的可能还是有的，甚至同一个矿工连续爆同一高度的块也是有可能的（矿机是你这个ETH的块高如此之小，看起来是一个自行设定的私有测试链，那么它的通常通常就很低，这种可能就名义了，这属于正常现象。

明白了，非常感谢解答
