### ISSUE TITLE
Nervos CKB miner unable to find job on connection: getLatestStratumJobEx fail

### ISSUE THREAD

**Issue by pranavt61** [btccom/btcpool#471]
I am working on a [Nervos open-source project](https://talk.nervos.org/t/insight-automated-stratum-v2-mining-pool-for-nervos/4870) which involves the BTCPool code base. I am trying to run a CKB Nervos mining pool, however, I am running into a problem with connecting miners to the pool.

This is the BTCPool output:
![Screen Shot 2020-11-16 at 5 45 14 PM](https://user-images.githubusercontent.com/22437126/99468952-a29a0200-28f6-11eb-90e2-d4cb8104c9c2.png)

This is the output from the [miner](https://github.com/leifjacky/ckb-gominer-demo):
![Screen Shot 2020-11-16 at 5 45 56 PM](https://user-images.githubusercontent.com/22437126/99468993-b5acd200-28f6-11eb-884c-1e4e1b533e86.png)

It looks like it is failing to find jobs for the miner.

I followed the build instructions on the github README. I have kafka and zookeeper running fine, as well as a MySQL database.

Any suggestions to fix this issue? Any help would be appreciated.

**Comment by duguyifang** [comment]
How to configure ckb mining pool, please see this issue: #378 
have you started ckb-nodebridge to get work from ckb-node?

**Comment by pranavt61** [comment]
I am running the nodebridge now, but running into a couple of problems

1) The nodebridge cannot connect to kafka, even though it is reachable from the docker container
![Screen Shot 2020-11-30 at 4 57 22 PM](https://user-images.githubusercontent.com/22437126/100683446-3cb56d80-332d-11eb-9120-d48049cb4482.png)
`nodebridge_1  | [2020-12-01T01:04:29Z ERROR rdkafka::client] librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.27.0.7:9092 failed: Connection refused (after 4ms in state CONNECT)`

2) The nodebridge cannot get the block template from the ckb node
![Screen Shot 2020-11-30 at 4 58 43 PM](https://user-images.githubusercontent.com/22437126/100683525-62427700-332d-11eb-8007-c9fdb7cc96ae.png)
`nodebridge_1  | [2020-12-01T01:02:13Z ERROR nodebridge::ckb] Failed to get block template: Server returned rpc error Server error: RPCModuleIsDisabled: This RPC method is in the module `Miner`. Please modify `rpc.modules` and `block_assembler` in ckb.toml and restart the ckb node to enable it.`

I submitted the second issue to the [CKB Repo](https://github.com/nervosnetwork/ckb/issues/2378) already, but any help on the matter would be appreciated.

**Comment by pranavt61** [comment]
Nodebridge is up and creating RawJobs for kafka:
`/usr/bin/nodebridge ckb --db_url mysql://root:root@mysql:3306/BTCPOOL_CKB --job_topic CkbRawGw --kafka_brokers "kafka:19092" --rpc_addr http://ckb-node:8114 --rpc_interval "2000" --solved_share_topic CkbSolvedShare`

![Screen Shot 2020-12-02 at 5 34 22 PM](https://user-images.githubusercontent.com/22437126/100952099-b764c100-34c4-11eb-82e3-a3695e8f357b.png)

However, I am still getting the same error. When connecting a miner. 
![Screen Shot 2020-12-02 at 5 34 58 PM](https://user-images.githubusercontent.com/22437126/100952248-0874b500-34c5-11eb-9319-dfecc183080b.png)

It seems these are the two places in the code where it is throwing errors:

src/StratumServer.cc:185
![Screen Shot 2020-12-02 at 5 36 40 PM](https://user-images.githubusercontent.com/22437126/100952501-7e791c00-34c5-11eb-9f17-9bb0b4688e86.png)


src/ckb/StratumSessionCkb.cc:62
![Screen Shot 2020-12-02 at 5 36 01 PM](https://user-images.githubusercontent.com/22437126/100952405-5db0c680-34c5-11eb-806e-f6874e6ccf58.png)

**Comment by duguyifang** [comment]
it means that the sserver didn't get  job from Kafka, you should check whether your jobmaker have received job and sent job to kafka or not.

**Comment by pranavt61** [comment]
Nodebridge is sending messages to Kafka, here is the kafka dashboard output:
![Screen Shot 2020-12-02 at 5 34 22 PM](https://user-images.githubusercontent.com/22437126/100959909-23025a80-34d4-11eb-92aa-6bfd93a64516.png)

Is this the right topic?

No other topics are being populated by nodebridge, only CKBRawGw. When switching the nodebridge's `--job_topic` from CKBRawGw to CKBJob, I get a parsing error from BTCPool.

Here is my job_workers config:
![Screen Shot 2020-12-02 at 7 29 22 PM](https://user-images.githubusercontent.com/22437126/100960277-d2d7c800-34d4-11eb-8953-98d8931cc8e9.png)

**Comment by pranavt61** [comment]
### We've updated our repo so we can recreate this error more reliably with docker-compose: 
https://github.com/insight-nervos/btcpool-docker-compose#local-miner

### To get the docker-compose up and running with the test miner use this command:
`docker-compose -f docker-compose.yml -f docker-compose.override.ckb-miner.yml up -d`

Wait at least 30 seconds for all of the applications to come up and running

### To make sure the miner is running, use this command:
`docker-compose -f docker-compose.yml -f docker-compose.override.ckb-miner.yml logs ckb-miner`

#### The expected output is:
![Screen Shot 2020-12-08 at 6 08 41 PM](https://user-images.githubusercontent.com/22437126/101564735-8979f380-3980-11eb-8d65-b358a44552d9.png)

### To find the error in the btcpool logs, use this command:
`docker-compose -f docker-compose.yml -f docker-compose.override.ckb-miner.yml logs btcpool`

#### The expected output is:
![Screen Shot 2020-12-08 at 6 10 07 PM](https://user-images.githubusercontent.com/22437126/101564836-bc23ec00-3980-11eb-83d7-da249fda0e83.png)

#### The main docker compose file is here: `./docker-compose.yml`
#### The btcpool config is located here: `./btcpool/config/sserver.cfg`. 

##### Again thank you so much for your time, any help on this issue would be greatly appreciated.

**Comment by duguyifang** [comment]
btcpool-ckb must  Contain the following components: 
1)， nodebridge get rawjob from ckb-node and send rawjob to `CkbRawGw`,you can start it with the following command:   
 `./nodebridge ckb --db_url mysql://useername:password@127.0.0.1:3306/bpool_local_db --job_topic CkbRawGw --kafka_brokers "127.0.0.1:9092" --rpc_addr http://127.0.0.1:8114 --rpc_interval "2000" --solved_share_topic CkbSolvedShare`
2),，jobmaker get raw job from `CkbRawGw`  and check the data and remove the duplicate, and then send job to `CkbJob` topic .
3),，sserver get job from  `CkbJob` , and then send job to ckbminer, and when ckbminer submited a solved share ,sserver will send this share to `solved_share_topic `.
the cfg of jobmaker and sserver, you can find it in [ckb-cfg](https://github.com/btccom/btcpool/tree/master/src/ckb/cfg)

**Comment by pranavt61** [comment]
Looks like I was missing the jobmaker program in the docker-compose. Thank you!
