### ISSUE TITLE
这个版本有问题呀

### ISSUE THREAD

**Issue by learsu** [btccom/btcpool#51]
I0116 19:22:41.017634  4544 StratumServer.cc:159] start job repository consume thread
I0116 19:22:41.025430  4521 StratumServer.cc:446] update users count: 5
I0116 19:22:41.032752  4521 Kafka.cc:421] add brokers: kafka1:9092,kafka2:9093,kafka3:9094
I0116 19:22:41.032845  4521 Kafka.cc:428] create topic handle: ShareLog
I0116 19:22:41.063551  4521 Kafka.cc:421] add brokers: kafka1:9092,kafka2:9093,kafka3:9094
I0116 19:22:41.063633  4521 Kafka.cc:428] create topic handle: SolvedShare
I0116 19:22:41.094233  4521 Kafka.cc:421] add brokers: kafka1:9092,kafka2:9093,kafka3:9094
I0116 19:22:41.094477  4521 Kafka.cc:428] create topic handle: NMCSolvedShare
I0116 19:22:41.124956  4521 Kafka.cc:421] add brokers: kafka1:9092,kafka2:9093,kafka3:9094
I0116 19:22:41.125020  4521 Kafka.cc:428] create topic handle: CommonEvents
I0116 19:25:48.418354  4521 StratumSession.cc:235] client connect, ip: 192.168.1.2
E0116 19:25:48.418558  4521 StratumSession.cc:317] decode line fail, not a json string
I0116 19:25:48.419358  4521 StratumServer.cc:982] got an error on the socket: Connection reset by peer
I0116 19:25:48.419924  4521 StratumSession.cc:235] client connect, ip: 192.168.1.2
W0116 19:25:49.423190  4521 StratumServer.cc:125] getLatestStratumJobEx fail

guiminer无法正常测试，sserver.INFO中不再显示以前的remove过期Job了。

**Comment by YihaoPeng** [comment]
检查你的gbtmaker和jobmaker是否正常工作。

**Comment by learsu** [comment]
kafka队列有问题，gbtmaker生成RawGbt没有正常进队列，造成jobmaker取RawGbt时出现RawGbt Map is empty。谢谢@YihaoPeng

**Comment by HelloJasonZhang** [comment]
@learsu 问下怎么解决这个错误的？ 能不能给一个联系方式交流下。

**Comment by SwimmingTiger** [comment]
sserver没有接收到任务。
可能原因是jobmaker没有产生任务。
可能原因是gbtmaker没有产生区块模板。
但是也有可能是kafka发生问题导致gbtmaker没有正常写入（这时候不会报错。）

可以通过kafka控制台消费器进行测试：
/work/kafka/bin/kafka-console-consumer.sh --zookeeper=127.0.0.1:2181 --topic=RawGbt
如果运行后没有看到任何内容，说明kafka可能有问题或者gbtmaker配置错误。
