### ISSUE TITLE
API is not working and/or documentation needs improved

### ISSUE THREAD

**Issue by StefanM98** [btccom/btcpool#53]
After trying multiple different GET requests the only response I manage to get is this: 
{"err_no":20001,"err_msg":"permissions denied"}

This is the path that the documentation provides:
https://${Endpoint}/${Version}/${Path}

For example:
https://us-pool.api.btc.com/v1/realtime/hashrate

Even after passing in the access key and puid I do not get any results. Any suggestions or improvements would be greatly appreciated.

**Comment by YangWangBitmain** [comment]
![image](https://user-images.githubusercontent.com/26923630/35610219-650a4b82-069b-11e8-8e11-c9ed9c35054f.png)
hi,if you pass in the correct `puid` and `ak` ,it will work.

**Comment by StefanM98** [comment]
I apologize for the mistake. It seems that there was a problem with my access key and it has been resolved. Thank you.
