### ISSUE TITLE
 Error when building solution

### ISSUE THREAD

**Issue by ignaciopulicedonatto** [btccom/btcpool#60]
I've downloaded the master branch and followed the instructions explained in INSTALL-BTCPool.md. Ran _cmake_ for the release build with 4 jobs. When I try to run the _make_ command I'm getting the following errors:
- JobMaker.cc:88:51: error: ‘IsValidDestinationString’ was not declared in this scope
- JobMaker.cc:93:57: error: ‘DecodeDestination’ was not declared in this scope

To avoid those error I just commented the **#ifdef CHAIN_TYPE_SBTC** in **BitcoinUtils.cc** and  **BitcoinUtils.h** .

**Comment by YihaoPeng** [comment]
What is the Bitcoin node version of your link?
`IsValidDestinationString()` and `DecodeDestination()` is existed in there versions:
* bitcoin v0.16.0rc1 (or later)
* bitcoin-abc v0.16.2 (or later)
* UnitedBitcoin 1.0.7.0 (or later)
These two functions is inexistence in SuperBitcoin so I wrote a special version for it.

**Comment by ignaciopulicedonatto** [comment]
0.14.2, so yes. that is the problem. I tested it again with the new bitcoin version and works fine. 
Thanks ! .
