### ISSUE TITLE
Why use calcWorkerId?

### ISSUE THREAD

**Issue by schua** [btccom/btcpool#68]
I'm interested in the codes.
I noticed that every worker name has a workerid, which is calced by a hash function.(code comment link to a Birthday_attack wiki page).

Is that just for speed optimization or has any other concerns?

**Comment by YihaoPeng** [comment]
It's for speed optimization. And we need a fixed length data in sharelog or the sharelog parser will be more complex.

**Comment by schua** [comment]
Thanks for your information :)
