### ISSUE TITLE
Error block submit in  bitcoin testnet:{"result":"inconclusive","error":null,"id":"1"}

### ISSUE THREAD

**Issue by devfans** [btccom/btcpool#72]
Testing in bitcoin testnet and got several:
{"result":"inconclusive","error":null,"id":"1"}

Is it a known issue?

**Comment by YihaoPeng** [comment]
```
testnet = true;
```
must be set at
`build/run_jobmaker/jobmaker.cfg`
`build/run_sserver/sserver.cfg`
for bitcoin testnet3 mining.

If you still have the problem, please tell me the version of the bitcoin source code you linked to, and paste your `build/run_sserver/sserver.cfg`.

**Comment by devfans** [comment]
The code version is commit: 206e610db7e885d1da11f7d17312242935700eba
Yes, i set `testnet = true` in those files.
Here's my `sserver.cfg`
```
testnet = true;

kafka = {
  brokers = "ip:9092";
};

sserver = {
  ip = "0.0.0.0";
  port = 3339;

  // should be global unique, range: [1, 255]
  id = 1;

  // write last mining notify job send time to file, for monitor
  file_last_notify_time = "/path-to-sserver_lastnotifytime.txt";

  // if enable simulator, all share will be accepted. for testing
  enable_simulator = false;

  // if enable it, all share will make block and submit. for testing
  enable_submit_invalid_block = false;

  // how many seconds between two share submit
  share_avg_seconds = 10;
};

users = {
  //
  // https://example.com/get_user_id_list?last_id=0
  // {"err_no":0,"err_msg":null,"data":{"jack":1,"terry":2}}
  //
  list_id_api_url = "http://ip/GetUserList";
};
```
Seems about 50% of the block submit got this error.

**Comment by YihaoPeng** [comment]
I want to know the bitcoin's version your linked to BTCPool.
You know you need download a bitcoin's source code before building BTCPool.
The consensus rule about how to build a block is provided by the bitcoin's source code, not BTCPool.
The block may invalid if the bitcoin's source code your linked to BTCPool not match your actual running node.

Please provide the bitcoin node's version that your running, and the bitcoin source code's version that your linked to BTCPool.

**Comment by devfans** [comment]
The version of the bitcoin source code i was using is the latest release: https://github.com/bitcoin/bitcoin/archive/v0.16.0.tar.gz

Thanks!

**Comment by dyzz** [comment]
looks like late blocks, you could provide some log with jobmaker and sserver.

**Comment by devfans** [comment]
I checked around the invalid blocks, seems the issue only happened when the testnet net diff was set to 1, `(one nBits sample : 486604799)`, so the reason could be too many block submits at the same time from miners and mine was late. Please let me know your thoughts, thanks for your time!

**Comment by YihaoPeng** [comment]
It is entirely possible. The situation occurs if the miner has the ability to found multiple blocks before switching jobs. For example, mining in a regression test network.

**Comment by devfans** [comment]
I see, thanks. So the issue can be closed I think. Thank you very much!
