### ISSUE TITLE
URL of github link in "build BTCPool that linking to Bitcoin"

### ISSUE THREAD

**Issue by nono1981** [btccom/btcpool#73]
"git clone https://github.com/bitcoin/bitcoin.git" seems wrong, 
should be this one? 
"git clone https://github.com/btccom/btcpool.git"

**Comment by zhanghuahua0708** [comment]
yeah, the right is  " git clone https://github.com/btccom/btcpool.git "

**Comment by YihaoPeng** [comment]
I have corrected this mistake. Thank you. :smiley:
