### ISSUE TITLE
怎么设置多个gbtMaker

### ISSUE THREAD

**Issue by zhanghuahua0708** [btccom/btcpool#74]
在btcpool架构图里面，是可以布置多个bitcoind节点的，所以我们需要设置数量相同的GBTMaker用来同步。所以，是不是意味着我们需要布置多个btcpool?毕竟一个btcpool服务器里面只有一个gbtMaker?

**Comment by zhanghuahua0708** [comment]
在Benchmark-100000.md里面，common server只有一个gbtmaker, 也就只有一个bitcoind节点。从孤块率上考虑，bitcoind数量应该是尽量多一点吧。当然这个会产生大量的数据，可能影响性能。所以，我想了解，你们有没有测试过设置多个bitcoind的情况？对btcpool会产生什么影响？是否需要增多其他的服务？

**Comment by YihaoPeng** [comment]
我们正在使用两个bitcoind和两个gbtmaker，没有增加其他的服务。如果觉得数据量大，可以把每个gbtmaker的提交时间间隔减少为原来的一半。
