### ISSUE TITLE
Problem compiling with bitcoin0.16.0

### ISSUE THREAD

**Issue by sensha** [btccom/btcpool#79]
I'm trying to compile the pool against bitcoin-0.16.0 and i'm getting the following types of compilation errors.
```
/src/GbtMaker.cc:179: undefined reference to `base_blob<256u>::ToString[abi:cxx11]() const'
/src/Stratum.cc:245: undefined reference to `base_blob<256u>::GetHex[abi:cxx11]() const'
```
Some searching has led me down the path of using libdb4.8, but even after installing that i'm still getting the same compilation errors. These methods do exist in the bitcoin source, what am I doing wrong?

**Comment by sensha** [comment]
solved it by recompiling bitcoin with libdb4.8 instead of 5.3

**Comment by YihaoPeng** [comment]
OK, thank you for your feedback :smiley:
