### ISSUE TITLE
Payout system

### ISSUE THREAD

**Issue by webchi** [btccom/btcpool#83]
Hi! Is there any preferred payout system? PPLNS? PPS? Or another?

**Comment by dyzz** [comment]
It's free of choice. You need to implement your own with share log. PPS might be easier.

**Comment by webchi** [comment]
Also found rskd config for gwmaker https://github.com/btccom/btcpool/blob/7baa93acc6381a0658217994adaf3acdcb80b0dd/src/gwmaker/gwmaker.cfg#L16
Is it necessary to run pool?
