### ISSUE TITLE
sharelogger append  more shares to bin file

### ISSUE THREAD

**Issue by schua** [btccom/btcpool#86]
Hello. I found a strange things.
If the sharelogger program is stopped and then restart,  it will reread all share messages from kafka (from offset 0) and append them to the share bin files.
The question is:  these share messages has been written to bin files before.  They are supposed to be discarded.
Is that normal?
Or it is just a error caused by kafka setup ?
Thanks.

**Comment by SwimmingTiger** [comment]
Sharelogger uses kafka high level comsumer, it stores the offset to kafka's offset topic and grouped by `kafka_group_id` in `sharelogger.cfg`.

If `kafka_group_id` changed, or kafka's offset topic lost or broken, sharelogger will lose its offset and re-comsume from the first.

**Comment by schua** [comment]
Thanks. 
When restart all services, 
I found it neet to start kafka first then sharelogger.
