### ISSUE TITLE
How to set the value of block_version in jobmaker.cfg?

### ISSUE THREAD

**Issue by u2mithrandir** [btccom/btcpool#88]
According to the comment，if block_version is 0, jobmaker will use the the version which returned by bitcoind. So, should I always set this value as 0? In which case should I set block_version as the other value instead of 0?

**Comment by YihaoPeng** [comment]
If you want to use BIP9 to vote, you can set a non-zero value. Otherwise, it can always be set to 0.

At present, BIP9 has lost its function on BTC. Version is being used for ASICBoost mining. :rolling_on_the_floor_laughing: 

So, just set it be 0.
